// P0-5: hash-chain logic, mirrored in TS against golden vectors from the real database.
//
// The chain itself lives in SQL (migration 20260713200000): a BEFORE INSERT trigger on
// graph_patches computes entry_hash = sha256(immutable columns + prev_hash), and
// verify_patch_chain(branch_id) walks a branch reporting the first broken link. The two
// golden vectors below were generated by running the ACTUAL migration on PostgreSQL 16
// in-session (2026-07-13) — they pin the exact preimage serialization (jsonb::text
// normalization included) and algorithm, so a silent edit to either side breaks here.
import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';

interface ChainRow {
  id: string;
  branchId: string;
  sequence: number;
  patchType: string;
  actorType: string;
  actorId: string | null;
  summary: string;
  /** payload::text exactly as jsonb renders it (keys sorted, ", "/": " separators) */
  payloadText: string;
  /** preconditions::text or null */
  preconditionsText: string | null;
  /** extract(epoch from created_at)::text — always 6 decimal places */
  epochText: string;
  prevHash: string | null;
  entryHash: string;
}

/** TS mirror of compute_patch_entry_hash (migration 20260713200000). */
function computePatchEntryHash(r: Omit<ChainRow, 'entryHash'>): string {
  const preimage = [
    r.id,
    r.branchId,
    String(r.sequence),
    r.patchType,
    r.actorType,
    r.actorId ?? '',
    r.summary,
    r.payloadText,
    r.preconditionsText ?? '',
    r.epochText,
    r.prevHash ?? '',
  ].join('|');
  return createHash('sha256').update(preimage, 'utf8').digest('hex');
}

/** TS mirror of verify_patch_chain semantics. */
function verifyChain(rows: ChainRow[]): { status: 'no_chain' | 'intact' | 'broken'; brokenAtSequence?: number } {
  if (rows.length === 0) return { status: 'no_chain' };
  let expectedPrev: string | null = null;
  for (const r of [...rows].sort((a, b) => a.sequence - b.sequence)) {
    if (r.prevHash !== expectedPrev) return { status: 'broken', brokenAtSequence: r.sequence };
    if (computePatchEntryHash(r) !== r.entryHash) return { status: 'broken', brokenAtSequence: r.sequence };
    expectedPrev = r.entryHash;
  }
  return { status: 'intact' };
}

// Golden vectors — verbatim DB output (payload::text, preconditions::text, epoch::text,
// prev_hash, entry_hash) from the live migration run.
const ROW_1: ChainRow = {
  id: 'a0000000-0000-4000-8000-000000000001',
  branchId: 'b0000000-0000-4000-8000-000000000110',
  sequence: 1,
  patchType: 'add_node',
  actorType: 'human',
  actorId: null,
  summary: 'Add API node',
  payloadText: '{"id": "n1", "type": "backend-service"}',
  preconditionsText: '[{"path": "nodes", "type": "value_exists"}]',
  epochText: '1782900000.000000',
  prevHash: null,
  entryHash: 'b9924425ea674d3327067c25ddeb1aae536c67a071fa86b7aa01b23470fc472c',
};

const ROW_2: ChainRow = {
  id: 'a0000000-0000-4000-8000-000000000002',
  branchId: 'b0000000-0000-4000-8000-000000000110',
  sequence: 2,
  patchType: 'add_edge',
  actorType: 'ai',
  actorId: 'c0000000-0000-4000-8000-000000000001',
  summary: 'Connect nodes',
  payloadText: '{"id": "e1", "source": "n1", "target": "n2"}',
  preconditionsText: null,
  epochText: '1782900300.123456',
  prevHash: 'b9924425ea674d3327067c25ddeb1aae536c67a071fa86b7aa01b23470fc472c',
  entryHash: 'fb45ae8b63ee36bcf589b7b3d6190045fd2fa481b88c39307ee41748ec63e1d3',
};

describe('P0-5: TS mirror matches the database hash chain (golden vectors)', () => {
  it('recomputes row 1 entry_hash exactly (null actor, preconditions present, first link)', () => {
    expect(computePatchEntryHash(ROW_1)).toBe(ROW_1.entryHash);
  });

  it('recomputes row 2 entry_hash exactly (actor uuid, fractional-second timestamp, linked)', () => {
    expect(computePatchEntryHash(ROW_2)).toBe(ROW_2.entryHash);
  });

  it('row 2 prev_hash links to row 1 entry_hash', () => {
    expect(ROW_2.prevHash).toBe(ROW_1.entryHash);
  });
});

describe('P0-5: chain verification semantics', () => {
  it('the golden chain verifies intact', () => {
    expect(verifyChain([ROW_1, ROW_2])).toEqual({ status: 'intact' });
  });

  it('an empty branch is no_chain, never broken (branch delete/merge is legitimate)', () => {
    expect(verifyChain([])).toEqual({ status: 'no_chain' });
  });

  it('a mutated payload is detected at that exact row', () => {
    const tampered = { ...ROW_2, payloadText: '{"id": "e1", "source": "n1", "target": "EVIL"}' };
    expect(verifyChain([ROW_1, tampered])).toEqual({ status: 'broken', brokenAtSequence: 2 });
  });

  it('a re-pointed prev_hash is detected at that exact row', () => {
    const repointed = { ...ROW_2, prevHash: 'ab'.repeat(32) };
    expect(verifyChain([ROW_1, repointed])).toEqual({ status: 'broken', brokenAtSequence: 2 });
  });

  it('removing a middle row breaks the link of the next row (history cannot be thinned)', () => {
    expect(verifyChain([ROW_2])).toEqual({ status: 'broken', brokenAtSequence: 2 });
  });
});
