// The product as the hosted homepage shows it (owner design 2026-10-07): the V3
// app's Work destination on its Workflows tab, its Requirements tab, and the
// Architecture destination, drawn from the "Homepage Redesign" canvas. It is an
// illustration, so its insides are hidden from assistive technology and out of the
// tab order; the chips above it are the control (AuthLandingPage).
import type { CSSProperties } from 'react';
import type { ProductView } from './landing-content.js';

const NAV_ON: CSSProperties = { background: '#2e3350', color: '#E6E9EF', fontWeight: 600 };
const NAV_OFF: CSSProperties = { background: 'transparent', color: '#8a8f9e', fontWeight: 500 };
// The selected tab is a shade darker than the brand accent so its white label reads
// at 4.5:1 (WCAG AA); the accent itself gives white text under 3:1.
const TAB_ON: CSSProperties = { background: '#6466d0', color: '#ffffff', fontWeight: 600 };
const TAB_OFF: CSSProperties = { background: 'transparent', color: '#8a8f9e', fontWeight: 500 };

function frameValues(view: ProductView, onView: (next: ProductView) => void) {
  return {
    workNav: view === 'arch' ? NAV_OFF : NAV_ON,
    archNav: view === 'arch' ? NAV_ON : NAV_OFF,
    tabFlows: view === 'flows' ? TAB_ON : TAB_OFF,
    tabReqs: view === 'reqs' ? TAB_ON : TAB_OFF,
    showFlows: () => onView('flows'),
    showReqs: () => onView('reqs'),
    showArch: () => onView('arch'),
  };
}

const LABELS: Record<ProductView, string> = {
  flows: 'NodeSpec Work, Workflows: a refund workflow in three stages, each traced from its outcome through a requirement and a service to the file that implements it.',
  reqs: 'NodeSpec Work, Requirements: seven requirements with their proven criteria, and the record of one with its criteria, tasks and tests.',
  arch: 'NodeSpec Architecture: a payments system on AWS and Vercel, with the service an agent holds and the requirements it serves.',
};

/** The 1200 by 720 desktop app, scaled down by the stylesheet on narrower screens. */
export function ProductFrameDesktop({ view, onView }: { view: ProductView; onView: (next: ProductView) => void }) {
  const v = frameValues(view, onView);
  return (
    <div className="lp-frame lp-frame-desktop" role="img" aria-label={LABELS[view]}>
      <div className="lp-frame-float">
        <div className="lp-frame-shadow">
          <div aria-hidden="true" style={{ width: '1200px', height: '720px', boxSizing: 'border-box', display: 'flex', flexDirection: 'column', background: '#0f1117', color: '#E6E9EF', overflow: 'hidden', fontSize: '13px' }}>
            <header style={{ "height": "52px", "flexShrink": "0", "boxSizing": "border-box", "display": "flex", "alignItems": "center", "padding": "0 20px", "borderBottom": "1px solid #1e2130", "background": "#12141c" }}>
            <div style={{ "flexGrow": "1", "flexBasis": "0", "minWidth": "0", "display": "flex", "alignItems": "center", "gap": "12px" }}>
            <div style={{ "width": "18px", "height": "18px", "borderRadius": "5px", "background": "#8B8FE6" }}></div>
            <span style={{ "fontSize": "13px", "fontWeight": "650" }}>Payments Platform</span>
            <div style={{ "display": "inline-flex", "alignItems": "center", "gap": "6px", "padding": "3px 10px", "borderRadius": "999px", "border": "1px solid #2a2e3f", "background": "#1a1d26" }}>
            <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="#8a8f9e" strokeWidth="2.2" strokeLinecap="round" aria-hidden="true"><circle cx="6" cy="6" r="3"></circle><circle cx="6" cy="18" r="3"></circle><path d="M6 9v6"></path><circle cx="18" cy="8" r="3"></circle><path d="M18 11v1a4 4 0 0 1-4 4H9"></path></svg>
            <span style={{ "fontFamily": "'JetBrains Mono', ui-monospace, monospace", "fontSize": "11px", "fontWeight": "700", "color": "#c9cdd8" }}>main</span>
            </div>
            </div>
            <nav aria-label="Destinations" style={{ "display": "flex", "gap": "4px", "padding": "3px", "borderRadius": "9px", "background": "#1a1d26", "border": "1px solid #1e2130" }}>
            <button type="button" tabIndex={-1} onClick={v.showFlows} style={{ "display": "inline-flex", "alignItems": "center", "padding": "6px 16px", "borderRadius": "6px", "border": "none", "fontSize": "12.5px", "cursor": "pointer", ...v.workNav }}>Work</button>
            <button type="button" tabIndex={-1} onClick={v.showArch} style={{ "display": "inline-flex", "alignItems": "center", "padding": "6px 16px", "borderRadius": "6px", "border": "none", "fontSize": "12.5px", "cursor": "pointer", ...v.archNav }}>Architecture</button>
            <span style={{ "display": "inline-flex", "alignItems": "center", "padding": "6px 16px", "borderRadius": "6px", "color": "#8a8f9e", "fontSize": "12.5px", "fontWeight": "500" }}>Export</span>
            </nav>
            <div style={{ "flexGrow": "1", "flexBasis": "0", "minWidth": "0", "display": "flex", "alignItems": "center", "justifyContent": "flex-end", "gap": "14px" }}>
            <span style={{ "display": "inline-flex", "alignItems": "center", "gap": "8px", "height": "32px", "padding": "0 14px", "borderRadius": "8px", "border": "1px solid #5c4a1f", "background": "#3d2f1a", "color": "#fbbf24", "fontSize": "12.5px", "fontWeight": "600" }}>Agents <span style={{ "display": "inline-flex", "alignItems": "center", "justifyContent": "center", "minWidth": "18px", "height": "18px", "padding": "0 5px", "borderRadius": "999px", "background": "#fbbf24", "color": "#241b08", "fontSize": "11px", "fontWeight": "700" }}>2</span></span>
            </div>
            </header>
            {view === 'flows' && (

              <div style={{ "flexGrow": "1", "minHeight": "0", "display": "flex", "flexDirection": "column", "padding": "14px 20px 18px", "gap": "12px" }}>
              <div style={{ "display": "flex", "gap": "4px", "alignSelf": "flex-start", "padding": "4px", "borderRadius": "10px", "background": "#1a1d26", "border": "1px solid rgba(42,46,63,.6)" }}>
              <span style={{ "padding": "6px 14px", "borderRadius": "7px", "background": "#6466d0", "color": "#ffffff", "fontSize": "12.5px", "fontWeight": "600" }}>Workflows</span>
              <button type="button" tabIndex={-1} onClick={v.showReqs} style={{ "padding": "6px 14px", "borderRadius": "7px", "border": "none", "background": "transparent", "color": "#8a8f9e", "fontSize": "12.5px", "fontWeight": "500", "cursor": "pointer" }}>Requirements</button>
              <span style={{ "padding": "6px 14px", "borderRadius": "7px", "color": "#8a8f9e", "fontSize": "12.5px", "fontWeight": "500" }}>Plan</span>
              </div>
              <div style={{ "position": "relative", "flexGrow": "1", "minHeight": "0", "borderRadius": "14px", "overflow": "hidden", "background": "radial-gradient(120% 90% at 50% 4%, #141a2e 0%, #0a0c13 56%, #07080d 100%)" }}>
              <div aria-hidden="true" style={{ "position": "absolute", "inset": "0", "boxShadow": "inset 0 0 200px 46px rgba(0,0,0,.66)", "zIndex": "3", "pointerEvents": "none" }}></div>

              <div style={{ "position": "absolute", "top": "12px", "left": "0", "right": "0", "zIndex": "4", "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "7px" }}>
              <div style={{ "display": "flex", "gap": "3px", "padding": "4px", "borderRadius": "12px", "background": "rgba(17,20,31,.82)", "border": "1px solid rgba(255,255,255,.09)" }}>
              <span style={{ "borderRadius": "9px", "padding": "7px 15px", "fontSize": "11.5px", "fontWeight": "650", "background": "rgba(139,143,230,.9)", "color": "#ffffff" }}>User Journey</span>
              <span style={{ "borderRadius": "9px", "padding": "7px 15px", "fontSize": "11.5px", "fontWeight": "650", "color": "#9aa2c0" }}>Constraints</span>
              </div>
              <div style={{ "display": "flex", "gap": "4px", "padding": "4px", "borderRadius": "12px", "background": "rgba(17,20,31,.82)", "border": "1px solid rgba(255,255,255,.09)" }}>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "6px", "borderRadius": "9px", "padding": "6px 10px", "fontSize": "11px", "fontWeight": "650", "background": "rgba(139,143,230,.9)", "color": "#ffffff" }}><span style={{ "width": "7px", "height": "7px", "borderRadius": "50%", "background": "#4fc98f" }}></span>Refund a charge</span>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "6px", "borderRadius": "9px", "padding": "6px 10px", "fontSize": "11px", "fontWeight": "650", "color": "#9aa2c0" }}><span style={{ "width": "7px", "height": "7px", "borderRadius": "50%", "background": "#e8a33d" }}></span>Checkout</span>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "6px", "borderRadius": "9px", "padding": "6px 10px", "fontSize": "11px", "fontWeight": "650", "color": "#9aa2c0" }}><span style={{ "width": "7px", "height": "7px", "borderRadius": "50%", "background": "#60a5fa" }}></span>Payouts</span>
              </div>
              </div>

              {/* the scene: one plane per workflow, the focused one in front */}
              <div style={{ "position": "absolute", "inset": "0", "perspective": "1500px", "perspectiveOrigin": "50% 30%", "zIndex": "1" }}>
              {/* a workflow behind */}
              <div aria-hidden="true" style={{ "position": "absolute", "left": "50%", "top": "92px", "width": "1060px", "height": "500px", "marginLeft": "-530px", "transform": "translateZ(-520px) translateY(-70px) rotateY(-12deg)", "opacity": ".22", "filter": "blur(.4px)" }}>
              <div style={{ "position": "absolute", "left": "140px", "top": "20px", "width": "190px", "height": "46px", "borderRadius": "12px", "background": "rgba(22,25,34,.78)", "border": "1.5px solid rgba(255,255,255,.18)" }}></div>
              <div style={{ "position": "absolute", "left": "468px", "top": "20px", "width": "240px", "height": "46px", "borderRadius": "12px", "background": "rgba(22,25,34,.78)", "border": "1.5px solid rgba(255,255,255,.18)" }}></div>
              <div style={{ "position": "absolute", "left": "846px", "top": "20px", "width": "190px", "height": "46px", "borderRadius": "12px", "background": "rgba(22,25,34,.78)", "border": "1.5px solid rgba(255,255,255,.18)" }}></div>
              <div style={{ "position": "absolute", "left": "140px", "top": "106px", "width": "190px", "height": "74px", "borderRadius": "10px", "background": "rgba(22,25,34,.78)", "border": "1.5px solid rgba(139,143,230,.4)" }}></div>
              <div style={{ "position": "absolute", "left": "463px", "top": "106px", "width": "250px", "height": "74px", "borderRadius": "10px", "background": "rgba(22,25,34,.78)", "border": "1.5px solid rgba(139,143,230,.4)" }}></div>
              <div style={{ "position": "absolute", "left": "846px", "top": "106px", "width": "190px", "height": "74px", "borderRadius": "10px", "background": "rgba(22,25,34,.78)", "border": "1.5px solid rgba(139,143,230,.4)" }}></div>
              <span style={{ "position": "absolute", "left": "0", "top": "30px", "fontSize": "14px", "fontWeight": "700", "color": "#c9cdd8" }}>Checkout</span>
              </div>

              {/* the focused workflow */}
              <div style={{ "position": "absolute", "left": "50%", "top": "96px", "width": "1060px", "height": "500px", "marginLeft": "-530px", "transformStyle": "preserve-3d", "transformOrigin": "50% 40%", "animation": "lp-sway 16s ease-in-out infinite" }}>
              <svg width="1060" height="500" viewBox="0 0 1060 500" style={{ "position": "absolute", "left": "0", "top": "0" }} aria-hidden="true">
              <defs>
              <linearGradient id="g-ho" gradientUnits="userSpaceOnUse" x1="0" y1="66" x2="0" y2="106"><stop offset="0" stopColor="#9aa2c0"></stop><stop offset="1" stopColor="#8B8FE6"></stop></linearGradient>
              <linearGradient id="g-or" gradientUnits="userSpaceOnUse" x1="0" y1="180" x2="0" y2="222"><stop offset="0" stopColor="#8B8FE6"></stop><stop offset="1" stopColor="#5aa9e6"></stop></linearGradient>
              <linearGradient id="g-rn" gradientUnits="userSpaceOnUse" x1="0" y1="288" x2="0" y2="330"><stop offset="0" stopColor="#5aa9e6"></stop><stop offset="1" stopColor="#5fd39a"></stop></linearGradient>
              <linearGradient id="g-nc" gradientUnits="userSpaceOnUse" x1="0" y1="388" x2="0" y2="430"><stop offset="0" stopColor="#5fd39a"></stop><stop offset="1" stopColor="#c07ae0"></stop></linearGradient>
              </defs>
              <g fill="none" strokeWidth="3" strokeLinecap="round" opacity=".38">
              <path d="M235,66 L235,106" stroke="url(#g-ho)"></path>
              <path d="M941,66 L941,106" stroke="url(#g-ho)"></path>
              <path d="M235,180 L235,222" stroke="url(#g-or)"></path>
              <path d="M588,180 C588,201 691,201 691,222" stroke="url(#g-or)"></path>
              <path d="M941,180 L941,222" stroke="url(#g-or)"></path>
              <path d="M235,288 L235,330" stroke="url(#g-rn)"></path>
              <path d="M691,288 L691,330" stroke="url(#g-rn)"></path>
              <path d="M941,288 L941,330" stroke="url(#g-rn)"></path>
              <path d="M235,388 L235,430" stroke="url(#g-nc)"></path>
              <path d="M691,388 L691,430" stroke="url(#g-nc)"></path>
              <path d="M941,388 L941,430" stroke="rgba(139,147,179,.6)" strokeDasharray="7 6"></path>
              </g>
              <g fill="none" strokeWidth="3.4" strokeLinecap="round">
              <path d="M588,66 L588,106" stroke="url(#g-ho)"></path>
              <path d="M588,180 C588,201 485,201 485,222" stroke="url(#g-or)"></path>
              <path d="M485,288 L485,330" stroke="url(#g-rn)"></path>
              <path d="M485,388 L485,430" stroke="url(#g-nc)"></path>
              </g>
              <g fill="none" stroke="#ffffff" strokeWidth="2" strokeLinecap="round" strokeDasharray="3 117" opacity=".8">
              <path d="M588,66 L588,106" style={{ "animation": "lp-flow 2.6s linear infinite" }}></path>
              <path d="M588,180 C588,201 485,201 485,222" style={{ "animation": "lp-flow 2.6s linear .4s infinite" }}></path>
              <path d="M485,288 L485,330" style={{ "animation": "lp-flow 2.6s linear .8s infinite" }}></path>
              <path d="M485,388 L485,430" style={{ "animation": "lp-flow 2.6s linear 1.2s infinite" }}></path>
              </g>
              </svg>

              <span style={{ "position": "absolute", "left": "6px", "top": "135px", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "fontWeight": "700", "letterSpacing": ".1em", "color": "#8B8FE6", "opacity": ".75" }}>OUTCOME</span>
              <span style={{ "position": "absolute", "left": "6px", "top": "248px", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "fontWeight": "700", "letterSpacing": ".1em", "color": "#5aa9e6", "opacity": ".75" }}>REQUIREMENT</span>
              <span style={{ "position": "absolute", "left": "6px", "top": "352px", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "fontWeight": "700", "letterSpacing": ".1em", "color": "#5fd39a", "opacity": ".75" }}>ARCHITECTURE</span>
              <span style={{ "position": "absolute", "left": "6px", "top": "448px", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "fontWeight": "700", "letterSpacing": ".1em", "color": "#c07ae0", "opacity": ".75" }}>CODE</span>

              {/* stage heads */}
              <div style={{ "position": "absolute", "left": "140px", "top": "20px", "width": "190px", "height": "46px", "boxSizing": "border-box", "borderRadius": "12px", "background": "rgba(32,36,50,.97)", "border": "1.5px solid rgba(255,255,255,.18)", "display": "flex", "alignItems": "center", "gap": "10px", "padding": "0 12px", "opacity": ".55" }}><span style={{ "width": "24px", "height": "24px", "boxSizing": "border-box", "borderRadius": "50%", "border": "2.5px solid #4ade80", "background": "rgba(255,255,255,.06)", "display": "grid", "placeItems": "center", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700" }}>1</span><span style={{ "fontSize": "13.5px", "fontWeight": "650", "color": "#EEF0FF" }}>Customer asks</span></div>
              <div style={{ "position": "absolute", "left": "468px", "top": "20px", "width": "240px", "height": "46px", "boxSizing": "border-box", "borderRadius": "12px", "background": "rgba(32,36,50,.97)", "border": "1.5px solid rgba(255,255,255,.28)", "display": "flex", "alignItems": "center", "gap": "10px", "padding": "0 12px", "boxShadow": "0 0 0 4px rgba(139,143,230,.14)" }}><span style={{ "width": "24px", "height": "24px", "boxSizing": "border-box", "borderRadius": "50%", "border": "2.5px solid #fbbf24", "background": "rgba(255,255,255,.06)", "display": "grid", "placeItems": "center", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700" }}>2</span><span style={{ "fontSize": "13.5px", "fontWeight": "650", "color": "#EEF0FF" }}>Refund issued</span></div>
              <div style={{ "position": "absolute", "left": "846px", "top": "20px", "width": "190px", "height": "46px", "boxSizing": "border-box", "borderRadius": "12px", "background": "rgba(32,36,50,.97)", "border": "1.5px solid rgba(255,255,255,.18)", "display": "flex", "alignItems": "center", "gap": "10px", "padding": "0 12px", "opacity": ".55" }}><span style={{ "width": "24px", "height": "24px", "boxSizing": "border-box", "borderRadius": "50%", "border": "2.5px solid #f87171", "background": "rgba(255,255,255,.06)", "display": "grid", "placeItems": "center", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700" }}>3</span><span style={{ "fontSize": "13.5px", "fontWeight": "650", "color": "#EEF0FF" }}>Ledger updated</span></div>

              {/* outcomes */}
              <div style={{ "position": "absolute", "left": "140px", "top": "106px", "width": "190px", "height": "74px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "8px 10px 8px 14px", "overflow": "hidden", "opacity": ".5" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#8B8FE6" }}></span><div style={{ "display": "flex", "justifyContent": "space-between", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#8B8FE6" }}><span>OUTCOME</span><span style={{ "fontFamily": "Inter, sans-serif", "color": "#4ade80", "fontWeight": "600" }}>ready to close</span></div><div style={{ "fontSize": "12px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "5px" }}>A refund link sits on every paid order</div></div>
              <div style={{ "position": "absolute", "left": "463px", "top": "106px", "width": "250px", "height": "74px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid #8B8FE6", "padding": "8px 10px 8px 14px", "overflow": "hidden" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#8B8FE6" }}></span><div style={{ "display": "flex", "justifyContent": "space-between", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#8B8FE6" }}><span>OUTCOME</span><span style={{ "fontFamily": "Inter, sans-serif", "color": "#fbbf24", "fontWeight": "600" }}>being built</span></div><div style={{ "fontSize": "12px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "5px" }}>Part of a charge comes back within 90 days</div></div>
              <div style={{ "position": "absolute", "left": "846px", "top": "106px", "width": "190px", "height": "74px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "8px 10px 8px 14px", "overflow": "hidden", "opacity": ".5" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#8B8FE6" }}></span><div style={{ "display": "flex", "justifyContent": "space-between", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#8B8FE6" }}><span>OUTCOME</span><span style={{ "fontFamily": "Inter, sans-serif", "color": "#f87171", "fontWeight": "600" }}>not built</span></div><div style={{ "fontSize": "12px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "5px" }}>Every refund lands in the ledger</div></div>

              {/* requirements */}
              <div style={{ "position": "absolute", "left": "140px", "top": "222px", "width": "190px", "height": "66px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "8px 10px 8px 14px", "overflow": "hidden", "opacity": ".5" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5aa9e6" }}></span><div style={{ "display": "flex", "justifyContent": "space-between", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#5aa9e6" }}><span>REQ-007</span><span style={{ "color": "#4ade80" }}>2 of 2</span></div><div style={{ "fontSize": "11.5px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "5px" }}>Refund link on paid orders</div></div>
              <div style={{ "position": "absolute", "left": "390px", "top": "222px", "width": "190px", "height": "66px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid #5aa9e6", "padding": "8px 10px 8px 14px", "overflow": "hidden", "boxShadow": "0 0 24px rgba(90,169,230,.25)" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5aa9e6" }}></span><div style={{ "display": "flex", "justifyContent": "space-between", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#5aa9e6" }}><span>REQ-002</span><span style={{ "color": "#fbbf24" }}>2 of 3</span></div><div style={{ "fontSize": "11.5px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "5px" }}>Partial refund within 90 days</div></div>
              <div style={{ "position": "absolute", "left": "596px", "top": "222px", "width": "190px", "height": "66px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "8px 10px 8px 14px", "overflow": "hidden", "opacity": ".5" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5aa9e6" }}></span><div style={{ "display": "flex", "justifyContent": "space-between", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#5aa9e6" }}><span>REQ-003</span><span style={{ "color": "#4ade80" }}>3 of 3</span></div><div style={{ "fontSize": "11.5px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "5px" }}>Webhooks ingested once</div></div>
              <div style={{ "position": "absolute", "left": "846px", "top": "222px", "width": "190px", "height": "66px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "8px 10px 8px 14px", "overflow": "hidden", "opacity": ".5" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5aa9e6" }}></span><div style={{ "display": "flex", "justifyContent": "space-between", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#5aa9e6" }}><span>REQ-004</span><span style={{ "color": "#f87171" }}>0 of 2</span></div><div style={{ "fontSize": "11.5px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "5px" }}>A ledger entry per refund</div></div>

              {/* architecture */}
              <div style={{ "position": "absolute", "left": "140px", "top": "330px", "width": "190px", "height": "58px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "8px 10px 8px 14px", "overflow": "hidden", "opacity": ".5" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5fd39a" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#5fd39a" }}>FRONTEND-APP</div><div style={{ "fontSize": "12px", "fontWeight": "650", "marginTop": "4px" }}>storefront-web</div></div>
              <div style={{ "position": "absolute", "left": "390px", "top": "330px", "width": "190px", "height": "58px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid #5fd39a", "padding": "8px 10px 8px 14px", "overflow": "hidden" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5fd39a" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#5fd39a" }}>BACKEND-SERVICE</div><div style={{ "fontSize": "12px", "fontWeight": "650", "marginTop": "4px" }}>payments-api</div></div>
              <div style={{ "position": "absolute", "left": "596px", "top": "330px", "width": "190px", "height": "58px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "8px 10px 8px 14px", "overflow": "hidden", "opacity": ".5" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5fd39a" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#5fd39a" }}>EVENT-STREAM</div><div style={{ "fontSize": "12px", "fontWeight": "650", "marginTop": "4px" }}>payment-events</div></div>
              <div style={{ "position": "absolute", "left": "846px", "top": "330px", "width": "190px", "height": "58px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "8px 10px 8px 14px", "overflow": "hidden", "opacity": ".5" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5fd39a" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#5fd39a" }}>WORKER</div><div style={{ "fontSize": "12px", "fontWeight": "650", "marginTop": "4px" }}>ledger-worker</div></div>

              {/* code */}
              <div style={{ "position": "absolute", "left": "140px", "top": "430px", "width": "190px", "height": "50px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "7px 10px 7px 14px", "overflow": "hidden", "opacity": ".5" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#c07ae0" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#c07ae0" }}>FILE</div><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "marginTop": "3px", "color": "#c9cdd8" }}>orders/refund.tsx</div></div>
              <div style={{ "position": "absolute", "left": "390px", "top": "430px", "width": "190px", "height": "50px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid #c07ae0", "padding": "7px 10px 7px 14px", "overflow": "hidden" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#c07ae0" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#c07ae0" }}>FILE</div><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "marginTop": "3px", "color": "#c9cdd8" }}>src/refunds.ts</div></div>
              <div style={{ "position": "absolute", "left": "596px", "top": "430px", "width": "190px", "height": "50px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "7px 10px 7px 14px", "overflow": "hidden", "opacity": ".5" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#c07ae0" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#c07ae0" }}>FILE</div><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "marginTop": "3px", "color": "#c9cdd8" }}>src/webhooks.ts</div></div>
              <div style={{ "position": "absolute", "left": "846px", "top": "430px", "width": "190px", "height": "50px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(22,25,34,.6)", "border": "2px dashed rgba(139,147,179,.5)", "padding": "7px 10px 7px 14px", "overflow": "hidden", "opacity": ".6" }}><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9.5px", "fontWeight": "700", "color": "#8a8f9e" }}>CODE</div><div style={{ "fontSize": "11px", "marginTop": "3px", "color": "#8a8f9e" }}>no file yet</div></div>
              </div>
              </div>

              {/* the strip */}
              <div style={{ "position": "absolute", "left": "0", "right": "0", "bottom": "12px", "zIndex": "4", "display": "flex", "justifyContent": "center" }}>
              <div style={{ "display": "flex", "gap": "6px", "padding": "6px", "borderRadius": "14px", "background": "rgba(17,20,31,.82)", "border": "1px solid rgba(255,255,255,.09)" }}>
              <div style={{ "width": "190px", "boxSizing": "border-box", "display": "flex", "flexDirection": "column", "gap": "6px", "padding": "9px 10px", "borderRadius": "11px", "background": "rgba(255,255,255,.035)", "border": "1px solid rgba(255,255,255,.075)" }}><div style={{ "display": "flex", "gap": "6px", "alignItems": "center" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700", "color": "#6b7398" }}>1</span><span style={{ "fontSize": "12.5px", "fontWeight": "650", "color": "#eef0ff" }}>Customer asks</span></div><div style={{ "display": "flex", "gap": "3px" }}><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#8B8FE6" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#5aa9e6" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#5fd39a" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#c07ae0" }}></i></div><span style={{ "fontSize": "11px", "color": "#4ade80" }}>ready to close</span></div>
              <div style={{ "width": "190px", "boxSizing": "border-box", "display": "flex", "flexDirection": "column", "gap": "6px", "padding": "9px 10px", "borderRadius": "11px", "background": "rgba(139,143,230,.18)", "border": "1px solid rgba(139,143,230,.5)" }}><div style={{ "display": "flex", "gap": "6px", "alignItems": "center" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700", "color": "#6b7398" }}>2</span><span style={{ "fontSize": "12.5px", "fontWeight": "650", "color": "#eef0ff" }}>Refund issued</span></div><div style={{ "display": "flex", "gap": "3px" }}><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#8B8FE6" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#5aa9e6" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#5fd39a" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "rgba(255,255,255,.1)" }}></i></div><span style={{ "fontSize": "11px", "color": "#8b93b3" }}>being built</span></div>
              <div style={{ "width": "190px", "boxSizing": "border-box", "display": "flex", "flexDirection": "column", "gap": "6px", "padding": "9px 10px", "borderRadius": "11px", "background": "rgba(248,113,113,.09)", "border": "1px solid rgba(248,113,113,.55)" }}><div style={{ "display": "flex", "gap": "6px", "alignItems": "center" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700", "color": "#6b7398" }}>3</span><span style={{ "fontSize": "12.5px", "fontWeight": "650", "color": "#eef0ff" }}>Ledger updated</span></div><div style={{ "display": "flex", "gap": "3px" }}><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#8B8FE6" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#5aa9e6" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "rgba(255,255,255,.1)" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "rgba(255,255,255,.1)" }}></i></div><span style={{ "fontSize": "11px", "color": "#f87171" }}>not built</span></div>
              </div>
              </div>
              </div>
              </div>

            )}
            {view === 'reqs' && (

              <div style={{ "flexGrow": "1", "display": "flex", "minHeight": "0" }}>
              <aside style={{ "width": "200px", "flexShrink": "0", "boxSizing": "border-box", "borderRight": "1px solid #1e2130", "padding": "22px 12px", "display": "flex", "flexDirection": "column", "gap": "4px" }}>
              <span style={{ "padding": "0 10px 6px", "fontSize": "11px", "fontWeight": "700", "letterSpacing": "0.09em", "textTransform": "uppercase", "color": "#6d7382" }}>Workflows</span>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "9px", "padding": "9px 10px", "borderRadius": "8px", "background": "#1a1d26", "color": "#E6E9EF", "fontSize": "13px", "fontWeight": "600" }}>All requirements<span style={{ "marginLeft": "auto", "fontSize": "11.5px", "fontWeight": "500", "color": "#8a8f9e" }}>7</span></span>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "9px", "padding": "9px 10px", "color": "#c9cdd8", "fontSize": "13px" }}><span style={{ "width": "8px", "height": "8px", "borderRadius": "50%", "background": "#4fc98f" }}></span>Refund a charge<span style={{ "marginLeft": "auto", "fontSize": "11.5px", "color": "#8a8f9e" }}>4</span></span>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "9px", "padding": "9px 10px", "color": "#c9cdd8", "fontSize": "13px" }}><span style={{ "width": "8px", "height": "8px", "borderRadius": "50%", "background": "#e8a33d" }}></span>Checkout<span style={{ "marginLeft": "auto", "fontSize": "11.5px", "color": "#8a8f9e" }}>2</span></span>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "9px", "padding": "9px 10px", "color": "#c9cdd8", "fontSize": "13px" }}><span style={{ "width": "8px", "height": "8px", "borderRadius": "50%", "background": "#60a5fa" }}></span>Payouts<span style={{ "marginLeft": "auto", "fontSize": "11.5px", "color": "#8a8f9e" }}>1</span></span>
              </aside>
              <main style={{ "flexGrow": "1", "minWidth": "0", "boxSizing": "border-box", "padding": "18px 24px 0", "display": "flex", "flexDirection": "column", "overflow": "hidden" }}>
              <div style={{ "display": "flex", "gap": "4px", "alignSelf": "flex-start", "padding": "4px", "borderRadius": "10px", "background": "#1a1d26", "border": "1px solid rgba(42,46,63,.6)", "marginBottom": "14px" }}>
              <button type="button" tabIndex={-1} onClick={v.showFlows} style={{ "padding": "6px 14px", "borderRadius": "7px", "border": "none", "background": "transparent", "color": "#8a8f9e", "fontSize": "12.5px", "fontWeight": "500", "cursor": "pointer" }}>Workflows</button>
              <span style={{ "padding": "6px 14px", "borderRadius": "7px", "background": "#6466d0", "color": "#ffffff", "fontSize": "12.5px", "fontWeight": "600" }}>Requirements</span>
              <span style={{ "padding": "6px 14px", "borderRadius": "7px", "color": "#8a8f9e", "fontSize": "12.5px", "fontWeight": "500" }}>Plan</span>
              </div>
              <div style={{ "display": "flex", "alignItems": "baseline", "gap": "12px", "padding": "0 10px 12px" }}><span style={{ "fontSize": "19px", "fontWeight": "650", "letterSpacing": "-0.015em" }}>Requirements</span><span style={{ "fontSize": "12px", "color": "#8a8f9e" }}>11 of 16 criteria proven</span><span style={{ "marginLeft": "auto", "padding": "6px 12px", "borderRadius": "7px", "border": "1px solid #2a2e3f", "fontSize": "11.5px", "fontWeight": "600" }}>New requirement</span></div>
              <div style={{ "display": "flex", "flexDirection": "column", "gap": "6px", "padding": "4px 10px 14px", "borderBottom": "1px solid #1e2130" }}><span style={{ "fontSize": "11px", "fontWeight": "700", "letterSpacing": "0.09em", "textTransform": "uppercase", "color": "#6d7382" }}>Vision</span><p style={{ "margin": "0", "fontSize": "12.5px", "color": "#c9cdd8", "lineHeight": "1.55" }}>Card payments for the storefront. Customers pay at checkout and can refund part of a charge within 90 days; every transaction lands in the payout ledger exactly once.</p></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "12px", "padding": "10px", "borderBottom": "1px solid #1e2130" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700", "color": "#8a8f9e" }}>REQ-001</span><span style={{ "fontSize": "13px", "fontWeight": "600", "flexGrow": "1" }}>Customers can pay by card at checkout</span><span style={{ "width": "86px", "fontSize": "11.5px", "color": "#8B8FE6" }}>Confirmed</span><span style={{ "width": "44px", "textAlign": "right", "fontSize": "11.5px", "color": "#4fc98f" }}>4 of 4</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "12px", "padding": "10px", "borderRadius": "8px", "background": "#1a1d26", "boxShadow": "inset 3px 0 0 #a78bfa" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700", "color": "#c9cdd8" }}>REQ-002</span><span style={{ "fontSize": "13px", "fontWeight": "600", "flexGrow": "1" }}>Customers can refund part of a charge within 90 days</span><span style={{ "width": "86px", "fontSize": "11.5px", "color": "#8B8FE6" }}>Confirmed</span><span style={{ "width": "44px", "textAlign": "right", "fontSize": "11.5px", "color": "#8a8f9e" }}>2 of 3</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "12px", "padding": "10px", "borderBottom": "1px solid #1e2130" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700", "color": "#8a8f9e" }}>REQ-003</span><span style={{ "fontSize": "13px", "fontWeight": "600", "flexGrow": "1" }}>Provider webhooks are ingested exactly once</span><span style={{ "width": "86px", "fontSize": "11.5px", "color": "#8B8FE6" }}>Confirmed</span><span style={{ "width": "44px", "textAlign": "right", "fontSize": "11.5px", "color": "#4fc98f" }}>3 of 3</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "12px", "padding": "10px", "borderBottom": "1px solid #1e2130" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700", "color": "#8a8f9e" }}>REQ-004</span><span style={{ "fontSize": "13px", "fontWeight": "600", "flexGrow": "1" }}>Every refund writes one ledger entry</span><span style={{ "width": "86px", "fontSize": "11.5px", "color": "#8B8FE6" }}>Confirmed</span><span style={{ "width": "44px", "textAlign": "right", "fontSize": "11.5px", "color": "#f87171" }}>0 of 2</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "12px", "padding": "10px", "borderBottom": "1px solid #1e2130" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700", "color": "#8a8f9e" }}>REQ-005</span><span style={{ "fontSize": "13px", "fontWeight": "600", "flexGrow": "1" }}>Card data never leaves the PCI boundary</span><span style={{ "width": "86px", "fontSize": "11.5px", "color": "#8B8FE6" }}>Confirmed</span><span style={{ "width": "44px", "textAlign": "right", "fontSize": "11.5px", "color": "#8a8f9e" }}>1 of 2</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "12px", "padding": "10px", "borderBottom": "1px solid #1e2130" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700", "color": "#8a8f9e" }}>REQ-007</span><span style={{ "fontSize": "13px", "fontWeight": "600", "flexGrow": "1" }}>A refund link sits on every paid order</span><span style={{ "width": "86px", "fontSize": "11.5px", "color": "#8a8f9e" }}>Unconfirmed</span><span style={{ "width": "44px", "textAlign": "right", "fontSize": "11.5px", "color": "#4fc98f" }}>2 of 2</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "12px", "padding": "16px 10px 0" }}><span style={{ "fontSize": "12px", "fontWeight": "600", "color": "#8a8f9e" }}>Outcomes, not yet requirements</span><span style={{ "fontSize": "11.5px", "color": "#6d7382" }}>2</span><span style={{ "marginLeft": "auto", "fontSize": "11.5px", "fontWeight": "600", "color": "#fbbf24" }}>1 proposal waiting</span></div>
              </main>
              <aside style={{ "width": "460px", "flexShrink": "0", "boxSizing": "border-box", "borderLeft": "1px solid #1e2130", "padding": "22px 24px 0", "display": "flex", "flexDirection": "column", "gap": "15px", "background": "#12141c", "overflow": "hidden" }}>
              <div style={{ "display": "flex", "flexDirection": "column", "gap": "6px" }}>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "10px" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "11px", "fontWeight": "700", "color": "#8a8f9e" }}>REQ-002</span><span style={{ "fontSize": "11px", "fontWeight": "600", "color": "#8B8FE6" }}>Confirmed</span><span style={{ "fontSize": "11px", "color": "#8a8f9e" }}>2 of 3 proven</span><span style={{ "marginLeft": "auto", "padding": "5px 10px", "borderRadius": "7px", "border": "1px solid #2a2e3f", "fontSize": "11.5px", "fontWeight": "600" }}>Edit</span></div>
              <span style={{ "fontSize": "16px", "fontWeight": "650", "letterSpacing": "-0.01em", "lineHeight": "1.35" }}>Customers can refund part of a charge within 90 days</span>
              <p style={{ "margin": "0", "fontSize": "12.5px", "color": "#c9cdd8", "lineHeight": "1.55" }}>A refund never exceeds what is left of the original charge, and retrying the same request refunds once.</p>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "8px", "paddingTop": "2px" }}><button type="button" tabIndex={-1} onClick={v.showArch} style={{ "padding": "4px 9px", "borderRadius": "6px", "border": "1px solid #a78bfa", "background": "transparent", "fontSize": "11px", "fontWeight": "600", "color": "#E6E9EF", "cursor": "pointer" }}>payments-api</button><button type="button" tabIndex={-1} onClick={v.showFlows} style={{ "padding": "0", "border": "none", "background": "transparent", "fontSize": "11px", "color": "#8a8f9e", "cursor": "pointer" }}>Refund a charge, step 2</button></div>
              </div>
              <div style={{ "display": "flex", "flexDirection": "column" }}>
              <div style={{ "display": "flex", "gap": "8px", "paddingBottom": "6px" }}><span style={{ "fontSize": "11px", "fontWeight": "700", "letterSpacing": "0.09em", "textTransform": "uppercase", "color": "#6d7382" }}>Criteria</span><span style={{ "fontSize": "11px", "color": "#8a8f9e" }}>3</span></div>
              <div style={{ "display": "flex", "gap": "10px", "padding": "7px 0", "borderTop": "1px solid #1e2130" }}><span style={{ "marginTop": "4px", "width": "7px", "height": "7px", "borderRadius": "50%", "background": "#4fc98f", "flexShrink": "0" }}></span><span style={{ "fontSize": "12px", "color": "#c9cdd8", "flexGrow": "1" }}>The refund stays within what is left of the charge</span><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#4fc98f" }}>TC-004</span></div>
              <div style={{ "display": "flex", "gap": "10px", "padding": "7px 0", "borderTop": "1px solid #1e2130" }}><span style={{ "marginTop": "4px", "width": "7px", "height": "7px", "borderRadius": "50%", "background": "#4fc98f", "flexShrink": "0" }}></span><span style={{ "fontSize": "12px", "color": "#c9cdd8", "flexGrow": "1" }}>Retrying the same request refunds once</span><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#4fc98f" }}>TC-005</span></div>
              <div style={{ "display": "flex", "gap": "10px", "padding": "7px 0", "borderTop": "1px solid #1e2130", "borderBottom": "1px solid #1e2130" }}><span style={{ "marginTop": "4px", "width": "7px", "height": "7px", "borderRadius": "50%", "border": "1.5px solid #8a8f9e", "boxSizing": "border-box", "flexShrink": "0" }}></span><span style={{ "fontSize": "12px", "color": "#c9cdd8", "flexGrow": "1" }}>A request after 90 days is refused</span><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#8B8FE6" }}>TC-006</span></div>
              </div>
              <div style={{ "display": "flex", "flexDirection": "column" }}>
              <div style={{ "display": "flex", "gap": "8px", "paddingBottom": "6px" }}><span style={{ "fontSize": "11px", "fontWeight": "700", "letterSpacing": "0.09em", "textTransform": "uppercase", "color": "#6d7382" }}>Tasks</span><span style={{ "fontSize": "11px", "color": "#8a8f9e" }}>3 of payments-api's 7 serve this</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "10px", "padding": "7px 0", "borderTop": "1px solid #1e2130" }}><span aria-hidden="true" style={{ "width": "13px", "height": "13px", "borderRadius": "3px", "background": "#4fc98f", "display": "inline-grid", "placeItems": "center", "flexShrink": "0" }}><svg width="9" height="9" viewBox="0 0 12 12" fill="none" stroke="#0f1117" strokeWidth="2.2" strokeLinecap="round"><path d="M2.5 6.2l2.4 2.3 4.6-5"></path></svg></span><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#8a8f9e", "width": "22px" }}>T2</span><span style={{ "fontSize": "12px", "color": "#c9cdd8", "flexGrow": "1" }}>Add POST /refunds with an idempotency key</span><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "color": "#6d7382" }}>a41c88e</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "10px", "padding": "7px 0", "borderTop": "1px solid #1e2130" }}><span aria-hidden="true" style={{ "width": "13px", "height": "13px", "borderRadius": "3px", "background": "#4fc98f", "display": "inline-grid", "placeItems": "center", "flexShrink": "0" }}><svg width="9" height="9" viewBox="0 0 12 12" fill="none" stroke="#0f1117" strokeWidth="2.2" strokeLinecap="round"><path d="M2.5 6.2l2.4 2.3 4.6-5"></path></svg></span><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#8a8f9e", "width": "22px" }}>T3</span><span style={{ "fontSize": "12px", "color": "#c9cdd8", "flexGrow": "1" }}>Cap the refund at the remaining charge</span><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "color": "#6d7382" }}>a41c88e</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "10px", "padding": "7px 0", "borderTop": "1px solid #1e2130", "borderBottom": "1px solid #1e2130" }}><span aria-hidden="true" style={{ "width": "13px", "height": "13px", "boxSizing": "border-box", "borderRadius": "3px", "border": "1.5px solid #6d7382", "flexShrink": "0" }}></span><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#8a8f9e", "width": "22px" }}>T6</span><span style={{ "fontSize": "12px", "color": "#c9cdd8", "flexGrow": "1" }}>Refuse refunds older than 90 days</span><span style={{ "fontSize": "10.5px", "fontWeight": "600", "color": "#8B8FE6" }}>Set 3 in the plan</span></div>
              </div>
              <div style={{ "display": "flex", "flexDirection": "column" }}>
              <div style={{ "display": "flex", "gap": "8px", "paddingBottom": "6px" }}><span style={{ "fontSize": "11px", "fontWeight": "700", "letterSpacing": "0.09em", "textTransform": "uppercase", "color": "#6d7382" }}>Tests</span><span style={{ "fontSize": "11px", "color": "#8a8f9e" }}>3</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "10px", "padding": "7px 0", "borderTop": "1px solid #1e2130" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#4fc98f", "width": "46px" }}>TC-004</span><span style={{ "fontSize": "12px", "color": "#c9cdd8", "flexGrow": "1" }}>Partial refund within the original charge</span><span style={{ "fontSize": "10.5px", "fontWeight": "600", "color": "#4fc98f" }}>passed</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "10px", "padding": "7px 0", "borderTop": "1px solid #1e2130" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#4fc98f", "width": "46px" }}>TC-005</span><span style={{ "fontSize": "12px", "color": "#c9cdd8", "flexGrow": "1" }}>Same idempotency key refunds once</span><span style={{ "fontSize": "10.5px", "fontWeight": "600", "color": "#4fc98f" }}>passed</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "10px", "padding": "7px 0", "borderTop": "1px solid #1e2130", "borderBottom": "1px solid #1e2130" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#8B8FE6", "width": "46px" }}>TC-006</span><span style={{ "fontSize": "12px", "color": "#c9cdd8", "flexGrow": "1" }}>Day 91 refund is refused</span><span style={{ "display": "inline-flex", "alignItems": "center", "gap": "5px", "fontSize": "10.5px", "fontWeight": "600", "color": "#8B8FE6" }}><span style={{ "display": "inline-flex", "alignItems": "center", "justifyContent": "center", "width": "16px", "height": "16px", "borderRadius": "50%", "background": "#2e3350", "fontSize": "9px", "fontWeight": "700", "color": "#E6E9EF" }}>c</span>running</span></div>
              </div>
              </aside>
              </div>

            )}
            {view === 'arch' && (

              <div style={{ "flexGrow": "1", "display": "flex", "minHeight": "0" }}>
              <aside style={{ "width": "210px", "flexShrink": "0", "boxSizing": "border-box", "borderRight": "1px solid #1e2130", "padding": "18px 12px 16px 14px", "display": "flex", "flexDirection": "column", "gap": "12px", "overflow": "hidden" }}>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "8px", "height": "34px", "padding": "0 10px", "borderRadius": "8px", "border": "1px solid #2a2e3f", "background": "#1a1d26", "fontSize": "12.5px", "color": "#8a8f9e" }}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#8a8f9e" strokeWidth="2.2" strokeLinecap="round" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="M20 20l-3.5-3.5"></path></svg>Search nodes...</span>
              <div style={{ "display": "flex", "flexWrap": "wrap", "gap": "5px" }}><span style={{ "padding": "4px 9px", "borderRadius": "999px", "border": "1px solid #5a5f78", "background": "#24273a", "fontSize": "11px", "fontWeight": "600" }}>AWS</span><span style={{ "padding": "4px 9px", "borderRadius": "999px", "border": "1px solid #2a2e3f", "color": "#c9cdd8", "fontSize": "11px", "fontWeight": "600" }}>Azure</span><span style={{ "padding": "4px 9px", "borderRadius": "999px", "border": "1px solid #2a2e3f", "color": "#c9cdd8", "fontSize": "11px", "fontWeight": "600" }}>Google Cloud</span><span style={{ "padding": "4px 9px", "borderRadius": "999px", "border": "1px solid #2a2e3f", "color": "#c9cdd8", "fontSize": "11px", "fontWeight": "600" }}>Vercel</span></div>
              <div style={{ "display": "flex", "flexDirection": "column" }}><span style={{ "padding": "6px 8px 3px", "fontSize": "10.5px", "fontWeight": "700", "letterSpacing": "0.08em", "color": "#6d7382" }}>A</span><span style={{ "padding": "6px 8px", "fontSize": "12.5px", "color": "#c9cdd8" }}>API Gateway</span><span style={{ "padding": "6px 8px", "fontSize": "12.5px", "color": "#c9cdd8" }}>Auth Provider</span><span style={{ "padding": "10px 8px 3px", "fontSize": "10.5px", "fontWeight": "700", "letterSpacing": "0.08em", "color": "#6d7382" }}>B</span><span style={{ "padding": "6px 8px", "fontSize": "12.5px", "color": "#c9cdd8" }}>Backend Service</span><span style={{ "padding": "10px 8px 3px", "fontSize": "10.5px", "fontWeight": "700", "letterSpacing": "0.08em", "color": "#6d7382" }}>C</span><span style={{ "padding": "6px 8px", "fontSize": "12.5px", "color": "#c9cdd8" }}>Cache</span><span style={{ "padding": "6px 8px", "fontSize": "12.5px", "color": "#c9cdd8" }}>CDN</span><span style={{ "padding": "10px 8px 3px", "fontSize": "10.5px", "fontWeight": "700", "letterSpacing": "0.08em", "color": "#6d7382" }}>D</span><span style={{ "padding": "6px 8px", "fontSize": "12.5px", "color": "#c9cdd8" }}>Database</span><span style={{ "padding": "10px 8px 3px", "fontSize": "10.5px", "fontWeight": "700", "letterSpacing": "0.08em", "color": "#6d7382" }}>E</span><span style={{ "padding": "6px 8px", "fontSize": "12.5px", "color": "#c9cdd8" }}>Event Stream</span></div>
              </aside>
              <main style={{ "flexGrow": "1", "minWidth": "0", "position": "relative", "overflow": "hidden", "backgroundColor": "#0f1117", "backgroundImage": "radial-gradient(#1e2130 1px, transparent 1px)", "backgroundSize": "24px 24px" }}>
              <svg width="630" height="668" viewBox="0 0 630 668" style={{ "position": "absolute", "left": "0", "top": "0", "pointerEvents": "none" }} aria-hidden="true">
              <defs><marker id="arch-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#5a5f78"></path></marker><marker id="arch-arrow-sel" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="#a78bfa"></path></marker></defs>
              <path d="M274,103 C307,103 307,105 340,105" fill="none" stroke="#5a5f78" strokeWidth="1.5" markerEnd="url(#arch-arrow)"></path>
              <path d="M458,136 C458,200 168,190 168,256" fill="none" stroke="#a78bfa" strokeWidth="2" markerEnd="url(#arch-arrow-sel)"></path>
              <path d="M288,290 C314,290 314,289 340,289" fill="none" stroke="#a78bfa" strokeWidth="2" markerEnd="url(#arch-arrow-sel)"></path>
              <path d="M458,322 L458,372" fill="none" stroke="#5a5f78" strokeWidth="1.5" markerEnd="url(#arch-arrow)"></path>
              <path d="M168,348 L168,400" fill="none" stroke="#a78bfa" strokeWidth="2" markerEnd="url(#arch-arrow-sel)"></path>
              <path d="M48,330 C22,330 22,553 48,553" fill="none" stroke="#a78bfa" strokeWidth="2" markerEnd="url(#arch-arrow-sel)"></path>
              <path d="M340,420 C314,420 314,433 288,433" fill="none" stroke="#5a5f78" strokeWidth="1.5" markerEnd="url(#arch-arrow)"></path>
              </svg>
              <div style={{ "position": "absolute", "left": "24px", "top": "30px", "width": "270px", "height": "140px", "boxSizing": "border-box", "border": "1.5px dashed #5a5f78", "borderRadius": "12px" }}><span style={{ "position": "absolute", "left": "12px", "top": "10px", "fontSize": "12px", "fontWeight": "600", "color": "#8a8f9e" }}>Vercel</span></div>
              <div style={{ "position": "absolute", "left": "44px", "top": "70px", "width": "230px", "height": "66px", "boxSizing": "border-box", "padding": "11px 14px", "border": "1px solid #2a2e3f", "borderRadius": "10px", "background": "#1a1d26", "display": "flex", "flexDirection": "column", "gap": "3px" }}><span style={{ "fontSize": "13px", "fontWeight": "650" }}>storefront-web</span><span style={{ "fontSize": "11px", "color": "#8a8f9e" }}>frontend-app · next.js</span></div>
              <div style={{ "position": "absolute", "left": "340px", "top": "74px", "width": "236px", "height": "62px", "boxSizing": "border-box", "padding": "11px 14px", "border": "1px solid #2a2e3f", "borderRadius": "10px", "background": "#1a1d26", "display": "flex", "flexDirection": "column", "gap": "3px" }}><span style={{ "fontSize": "13px", "fontWeight": "650" }}>api-gateway</span><span style={{ "fontSize": "11px", "color": "#8a8f9e" }}>api-gateway · aws</span></div>
              <div style={{ "position": "absolute", "left": "24px", "top": "206px", "width": "584px", "height": "420px", "boxSizing": "border-box", "border": "1.5px dashed #5a5f78", "borderRadius": "12px" }}><span style={{ "position": "absolute", "left": "12px", "top": "10px", "fontSize": "12px", "fontWeight": "600", "color": "#8a8f9e" }}>AWS · us-east-1</span></div>
              <div style={{ "position": "absolute", "left": "48px", "top": "256px", "width": "240px", "height": "92px", "boxSizing": "border-box", "padding": "12px 14px", "border": "1.5px solid #a78bfa", "borderRadius": "10px", "background": "#211c33", "display": "flex", "flexDirection": "column", "gap": "4px" }}><span style={{ "fontSize": "13.5px", "fontWeight": "650" }}>payments-api</span><span style={{ "fontSize": "11px", "color": "#8a8f9e" }}>backend-service · node 22 · ecs fargate</span><span style={{ "marginTop": "auto", "fontSize": "11px", "fontWeight": "600", "color": "#fbbf24" }}>claude-code is working here</span></div>
              <div style={{ "position": "absolute", "left": "340px", "top": "256px", "width": "236px", "height": "66px", "boxSizing": "border-box", "padding": "11px 14px", "border": "1px solid #2a2e3f", "borderRadius": "10px", "background": "#1a1d26", "display": "flex", "flexDirection": "column", "gap": "3px" }}><span style={{ "fontSize": "13px", "fontWeight": "650" }}>payment-events</span><span style={{ "fontSize": "11px", "color": "#8a8f9e" }}>event-stream · msk kafka</span></div>
              <div style={{ "position": "absolute", "left": "340px", "top": "372px", "width": "236px", "height": "66px", "boxSizing": "border-box", "padding": "11px 14px", "border": "1px solid #2a2e3f", "borderRadius": "10px", "background": "#1a1d26", "display": "flex", "flexDirection": "column", "gap": "3px" }}><span style={{ "fontSize": "13px", "fontWeight": "650" }}>ledger-worker</span><span style={{ "fontSize": "11px", "color": "#8a8f9e" }}>worker · go · ecs fargate</span></div>
              <div style={{ "position": "absolute", "left": "48px", "top": "400px", "width": "240px", "height": "66px", "boxSizing": "border-box", "padding": "11px 14px", "border": "1px solid #2a2e3f", "borderRadius": "10px", "background": "#1a1d26", "display": "flex", "flexDirection": "column", "gap": "3px" }}><span style={{ "fontSize": "13px", "fontWeight": "650" }}>payments-db</span><span style={{ "fontSize": "11px", "color": "#8a8f9e" }}>database · rds postgres · 6 migrations</span></div>
              <div style={{ "position": "absolute", "left": "48px", "top": "520px", "width": "240px", "height": "66px", "boxSizing": "border-box", "padding": "11px 14px", "border": "1px solid #2a2e3f", "borderRadius": "10px", "background": "#1a1d26", "display": "flex", "flexDirection": "column", "gap": "3px" }}><span style={{ "fontSize": "13px", "fontWeight": "650" }}>session-cache</span><span style={{ "fontSize": "11px", "color": "#8a8f9e" }}>cache · elasticache</span></div>
              <div style={{ "position": "absolute", "right": "20px", "top": "16px", "display": "flex", "gap": "2px", "padding": "2px", "borderRadius": "8px", "background": "#1a1d26" }}><span style={{ "height": "28px", "padding": "0 10px", "display": "inline-flex", "alignItems": "center", "color": "#c9cdd8", "fontSize": "12px", "fontWeight": "600" }}>Fit</span></div>
              </main>
              <aside style={{ "width": "360px", "flexShrink": "0", "boxSizing": "border-box", "borderLeft": "1px solid #1e2130", "padding": "24px 22px", "display": "flex", "flexDirection": "column", "gap": "20px", "background": "#12141c" }}>
              <div style={{ "display": "flex", "flexDirection": "column", "gap": "6px" }}><span style={{ "fontSize": "16px", "fontWeight": "650" }}>payments-api</span><span style={{ "fontSize": "11.5px", "color": "#8a8f9e" }}>backend-service · node 22 · inside AWS</span></div>
              <div style={{ "display": "flex", "flexDirection": "column", "gap": "6px", "padding": "12px 14px", "borderRadius": "10px", "background": "#1e1a12" }}><span style={{ "fontSize": "12.5px", "fontWeight": "650" }}>claude-code holds this node</span><span style={{ "fontSize": "12px", "color": "#c9cdd8", "lineHeight": "1.5" }}>Working on T6, Refuse refunds older than 90 days. Other agents wait or take another node.</span></div>
              <div style={{ "display": "flex", "flexDirection": "column", "gap": "2px" }}>
              <div style={{ "display": "flex", "gap": "8px", "paddingBottom": "6px" }}><span style={{ "fontSize": "11px", "fontWeight": "700", "letterSpacing": "0.09em", "textTransform": "uppercase", "color": "#6d7382" }}>Work here</span><span style={{ "fontSize": "11.5px", "color": "#8a8f9e" }}>7 of 9 proven</span></div>
              <span style={{ "display": "flex", "flexDirection": "column", "gap": "2px", "padding": "9px 0", "borderTop": "1px solid #1e2130" }}><span style={{ "fontSize": "12.5px", "fontWeight": "600" }}>Customers can pay by card at checkout</span><span style={{ "fontSize": "11.5px", "color": "#8a8f9e" }}>REQ-001 · 4 of 4 proven</span></span>
              <button type="button" tabIndex={-1} onClick={v.showReqs} style={{ "display": "flex", "flexDirection": "column", "gap": "2px", "padding": "9px 0", "border": "none", "borderTop": "1px solid #1e2130", "background": "transparent", "textAlign": "left", "cursor": "pointer", "color": "#E6E9EF" }}><span style={{ "fontSize": "12.5px", "fontWeight": "600" }}>Customers can refund part of a charge within 90 days</span><span style={{ "fontSize": "11.5px", "color": "#8a8f9e" }}>REQ-002 · 2 of 3 proven</span></button>
              <span style={{ "display": "flex", "flexDirection": "column", "gap": "2px", "padding": "9px 0", "borderTop": "1px solid #1e2130", "borderBottom": "1px solid #1e2130" }}><span style={{ "fontSize": "12.5px", "fontWeight": "600" }}>Card data never leaves the PCI boundary</span><span style={{ "fontSize": "11.5px", "color": "#8a8f9e" }}>REQ-005 · 1 of 2 proven</span></span>
              </div>
              <div style={{ "display": "flex", "flexDirection": "column", "gap": "8px" }}><span style={{ "fontSize": "11px", "fontWeight": "700", "letterSpacing": "0.09em", "textTransform": "uppercase", "color": "#6d7382" }}>Connects to</span><div style={{ "display": "flex", "flexWrap": "wrap", "gap": "6px" }}><span style={{ "padding": "5px 10px", "borderRadius": "7px", "border": "1px solid #2a2e3f", "fontSize": "11.5px", "fontWeight": "600", "color": "#c9cdd8" }}>api-gateway</span><span style={{ "padding": "5px 10px", "borderRadius": "7px", "border": "1px solid #2a2e3f", "fontSize": "11.5px", "fontWeight": "600", "color": "#c9cdd8" }}>payment-events</span><span style={{ "padding": "5px 10px", "borderRadius": "7px", "border": "1px solid #2a2e3f", "fontSize": "11.5px", "fontWeight": "600", "color": "#c9cdd8" }}>payments-db</span><span style={{ "padding": "5px 10px", "borderRadius": "7px", "border": "1px solid #2a2e3f", "fontSize": "11.5px", "fontWeight": "600", "color": "#c9cdd8" }}>session-cache</span></div></div>
              </aside>
              </div>

            )}
          </div>
        </div>
      </div>
    </div>
  );
}

/** The phone-sized app: Workflows first, Requirements one tap away. */
export function ProductFramePhone({ view, onView }: { view: ProductView; onView: (next: ProductView) => void }) {
  const v = frameValues(view === 'arch' ? 'flows' : view, onView);
  const shown = view === 'reqs' ? 'reqs' : 'flows';
  return (
    <div className="lp-frame lp-frame-phone" role="img" aria-label={LABELS[shown]}>
      <div className="lp-frame-float">
        <div className="lp-frame-shadow lp-frame-shadow-phone">
          <div aria-hidden="true" style={{ background: '#0f1117', color: '#E6E9EF', display: 'flex', flexDirection: 'column' }}>
            <div style={{ "height": "56px", "boxSizing": "border-box", "display": "flex", "alignItems": "center", "gap": "10px", "padding": "0 14px", "borderBottom": "1px solid #1e2130", "background": "#12141c" }}>
            <div style={{ "width": "16px", "height": "16px", "borderRadius": "4px", "background": "#8B8FE6", "flexShrink": "0" }}></div>
            <div style={{ "display": "flex", "flexDirection": "column", "gap": "1px", "minWidth": "0" }}><span style={{ "fontSize": "13px", "fontWeight": "650" }}>Payments Platform</span><span style={{ "fontFamily": "'JetBrains Mono', ui-monospace, monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#8a8f9e" }}>main</span></div>
            <div style={{ "flexGrow": "1" }}></div>
            <span style={{ "display": "inline-flex", "alignItems": "center", "gap": "7px", "height": "36px", "padding": "0 12px", "borderRadius": "10px", "border": "1px solid #5c4a1f", "background": "#3d2f1a", "color": "#fbbf24", "fontSize": "12.5px", "fontWeight": "650" }}>Agents <span style={{ "display": "inline-flex", "alignItems": "center", "justifyContent": "center", "minWidth": "17px", "height": "17px", "padding": "0 5px", "borderRadius": "999px", "background": "#fbbf24", "color": "#241b08", "fontSize": "10.5px", "fontWeight": "700" }}>2</span></span>
            </div>
            <div style={{ "display": "flex", "gap": "3px", "margin": "12px 14px 0", "alignSelf": "flex-start", "padding": "3px", "borderRadius": "9px", "background": "#1a1d26", "border": "1px solid rgba(42,46,63,.6)" }}>
            <button type="button" tabIndex={-1} onClick={v.showFlows} style={{ "padding": "6px 12px", "borderRadius": "6px", "border": "none", "fontSize": "12px", "cursor": "pointer", ...v.tabFlows }}>Workflows</button>
            <button type="button" tabIndex={-1} onClick={v.showReqs} style={{ "padding": "6px 12px", "borderRadius": "6px", "border": "none", "fontSize": "12px", "cursor": "pointer", ...v.tabReqs }}>Requirements</button>
            <span style={{ "padding": "6px 12px", "borderRadius": "6px", "color": "#8a8f9e", "fontSize": "12px" }}>Plan</span>
            </div>
            {shown === 'flows' && (

              <div style={{ "padding": "12px 14px 14px" }}>
              <div style={{ "position": "relative", "height": "500px", "borderRadius": "14px", "overflow": "hidden", "background": "radial-gradient(120% 90% at 50% 4%, #141a2e 0%, #0a0c13 56%, #07080d 100%)" }}>
              <div aria-hidden="true" style={{ "position": "absolute", "inset": "0", "boxShadow": "inset 0 0 90px 24px rgba(0,0,0,.7)", "zIndex": "3", "pointerEvents": "none" }}></div>

              <div style={{ "position": "absolute", "top": "10px", "left": "0", "right": "0", "zIndex": "4", "display": "flex", "flexDirection": "column", "alignItems": "center", "gap": "6px" }}>
              <div style={{ "display": "flex", "gap": "3px", "padding": "3px", "borderRadius": "11px", "background": "rgba(17,20,31,.82)", "border": "1px solid rgba(255,255,255,.09)" }}>
              <span style={{ "borderRadius": "8px", "padding": "6px 13px", "fontSize": "11px", "fontWeight": "650", "background": "rgba(139,143,230,.9)", "color": "#ffffff" }}>User Journey</span>
              <span style={{ "borderRadius": "8px", "padding": "6px 13px", "fontSize": "11px", "fontWeight": "650", "color": "#9aa2c0" }}>Constraints</span>
              </div>
              <div style={{ "display": "flex", "gap": "3px", "padding": "3px", "borderRadius": "11px", "background": "rgba(17,20,31,.82)", "border": "1px solid rgba(255,255,255,.09)" }}>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "5px", "borderRadius": "8px", "padding": "5px 9px", "fontSize": "10.5px", "fontWeight": "650", "background": "rgba(139,143,230,.9)", "color": "#ffffff", "whiteSpace": "nowrap" }}><span style={{ "width": "6px", "height": "6px", "borderRadius": "50%", "background": "#4fc98f" }}></span>Refund a charge</span>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "5px", "borderRadius": "8px", "padding": "5px 9px", "fontSize": "10.5px", "fontWeight": "650", "color": "#9aa2c0" }}><span style={{ "width": "6px", "height": "6px", "borderRadius": "50%", "background": "#e8a33d" }}></span>Checkout</span>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "5px", "borderRadius": "8px", "padding": "5px 9px", "fontSize": "10.5px", "fontWeight": "650", "color": "#9aa2c0" }}><span style={{ "width": "6px", "height": "6px", "borderRadius": "50%", "background": "#60a5fa" }}></span>Payouts</span>
              </div>
              </div>

              {/* the scene: the focused stage in front, its neighbours at the edges */}
              <div style={{ "position": "absolute", "inset": "0", "perspective": "900px", "perspectiveOrigin": "50% 30%", "zIndex": "1" }}>
              <div aria-hidden="true" style={{ "position": "absolute", "left": "50%", "top": "96px", "width": "520px", "height": "352px", "marginLeft": "-260px", "transform": "translateZ(-380px) translateY(-60px) rotateY(-12deg)", "opacity": ".2" }}>
              <div style={{ "position": "absolute", "left": "185px", "top": "0", "width": "150px", "height": "38px", "borderRadius": "11px", "background": "rgba(22,25,34,.78)", "border": "1.5px solid rgba(255,255,255,.18)" }}></div>
              <div style={{ "position": "absolute", "left": "185px", "top": "60px", "width": "150px", "height": "76px", "borderRadius": "10px", "background": "rgba(22,25,34,.78)", "border": "1.5px solid rgba(139,143,230,.4)" }}></div>
              <div style={{ "position": "absolute", "left": "185px", "top": "158px", "width": "150px", "height": "62px", "borderRadius": "10px", "background": "rgba(22,25,34,.78)", "border": "1.5px solid rgba(90,169,230,.4)" }}></div>
              </div>

              <div style={{ "position": "absolute", "left": "50%", "top": "96px", "width": "520px", "height": "352px", "marginLeft": "-260px", "transformStyle": "preserve-3d", "transformOrigin": "50% 40%", "animation": "lp-sway-phone 16s ease-in-out infinite" }}>
              <svg width="520" height="352" viewBox="0 0 520 352" style={{ "position": "absolute", "left": "0", "top": "0" }} aria-hidden="true">
              <defs>
              <linearGradient id="mg-ho" gradientUnits="userSpaceOnUse" x1="0" y1="38" x2="0" y2="60"><stop offset="0" stopColor="#9aa2c0"></stop><stop offset="1" stopColor="#8B8FE6"></stop></linearGradient>
              <linearGradient id="mg-or" gradientUnits="userSpaceOnUse" x1="0" y1="136" x2="0" y2="158"><stop offset="0" stopColor="#8B8FE6"></stop><stop offset="1" stopColor="#5aa9e6"></stop></linearGradient>
              <linearGradient id="mg-rn" gradientUnits="userSpaceOnUse" x1="0" y1="220" x2="0" y2="242"><stop offset="0" stopColor="#5aa9e6"></stop><stop offset="1" stopColor="#5fd39a"></stop></linearGradient>
              <linearGradient id="mg-nc" gradientUnits="userSpaceOnUse" x1="0" y1="290" x2="0" y2="312"><stop offset="0" stopColor="#5fd39a"></stop><stop offset="1" stopColor="#c07ae0"></stop></linearGradient>
              </defs>
              <g fill="none" strokeWidth="2.6" strokeLinecap="round" opacity=".38">
              <path d="M85,38 L85,60" stroke="url(#mg-ho)"></path><path d="M435,38 L435,60" stroke="url(#mg-ho)"></path>
              <path d="M85,136 L85,158" stroke="url(#mg-or)"></path><path d="M435,136 L435,158" stroke="url(#mg-or)"></path>
              <path d="M85,220 L85,242" stroke="url(#mg-rn)"></path><path d="M435,220 L435,242" stroke="url(#mg-rn)"></path>
              <path d="M85,290 L85,312" stroke="url(#mg-nc)"></path><path d="M435,290 L435,312" stroke="rgba(139,147,179,.6)" strokeDasharray="6 5"></path>
              </g>
              <g fill="none" strokeWidth="3.2" strokeLinecap="round">
              <path d="M260,38 L260,60" stroke="url(#mg-ho)"></path>
              <path d="M260,136 L260,158" stroke="url(#mg-or)"></path>
              <path d="M260,220 L260,242" stroke="url(#mg-rn)"></path>
              <path d="M260,290 L260,312" stroke="url(#mg-nc)"></path>
              </g>
              <g fill="none" stroke="#ffffff" strokeWidth="2" strokeLinecap="round" strokeDasharray="3 117" opacity=".85">
              <path d="M260,38 L260,60" style={{ "animation": "lp-flow 2.2s linear infinite" }}></path>
              <path d="M260,136 L260,158" style={{ "animation": "lp-flow 2.2s linear .35s infinite" }}></path>
              <path d="M260,220 L260,242" style={{ "animation": "lp-flow 2.2s linear .7s infinite" }}></path>
              <path d="M260,290 L260,312" style={{ "animation": "lp-flow 2.2s linear 1.05s infinite" }}></path>
              </g>
              </svg>

              {/* stage heads */}
              <div style={{ "position": "absolute", "left": "10px", "top": "0", "width": "150px", "height": "38px", "boxSizing": "border-box", "borderRadius": "11px", "background": "rgba(32,36,50,.97)", "border": "1.5px solid rgba(255,255,255,.18)", "display": "flex", "alignItems": "center", "gap": "8px", "padding": "0 10px", "opacity": ".5" }}><span style={{ "width": "20px", "height": "20px", "flexShrink": "0", "boxSizing": "border-box", "borderRadius": "50%", "border": "2.2px solid #4ade80", "display": "grid", "placeItems": "center", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "fontWeight": "700" }}>1</span><span style={{ "fontSize": "11.5px", "fontWeight": "650", "color": "#EEF0FF", "whiteSpace": "nowrap" }}>Customer asks</span></div>
              <div style={{ "position": "absolute", "left": "185px", "top": "0", "width": "150px", "height": "38px", "boxSizing": "border-box", "borderRadius": "11px", "background": "rgba(32,36,50,.97)", "border": "1.5px solid rgba(255,255,255,.28)", "display": "flex", "alignItems": "center", "gap": "8px", "padding": "0 10px", "boxShadow": "0 0 0 3px rgba(139,143,230,.16)" }}><span style={{ "width": "20px", "height": "20px", "flexShrink": "0", "boxSizing": "border-box", "borderRadius": "50%", "border": "2.2px solid #fbbf24", "display": "grid", "placeItems": "center", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "fontWeight": "700" }}>2</span><span style={{ "fontSize": "11.5px", "fontWeight": "650", "color": "#EEF0FF", "whiteSpace": "nowrap" }}>Refund issued</span></div>
              <div style={{ "position": "absolute", "left": "360px", "top": "0", "width": "150px", "height": "38px", "boxSizing": "border-box", "borderRadius": "11px", "background": "rgba(32,36,50,.97)", "border": "1.5px solid rgba(255,255,255,.18)", "display": "flex", "alignItems": "center", "gap": "8px", "padding": "0 10px", "opacity": ".5" }}><span style={{ "width": "20px", "height": "20px", "flexShrink": "0", "boxSizing": "border-box", "borderRadius": "50%", "border": "2.2px solid #f87171", "display": "grid", "placeItems": "center", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "fontWeight": "700" }}>3</span><span style={{ "fontSize": "11.5px", "fontWeight": "650", "color": "#EEF0FF", "whiteSpace": "nowrap" }}>Ledger updated</span></div>

              {/* outcomes */}
              <div style={{ "position": "absolute", "left": "10px", "top": "60px", "width": "150px", "height": "76px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "7px 9px 7px 13px", "overflow": "hidden", "opacity": ".45" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#8B8FE6" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9px", "fontWeight": "700", "color": "#8B8FE6" }}>OUTCOME</div><div style={{ "fontSize": "11px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "4px" }}>A refund link sits on every paid order</div></div>
              <div style={{ "position": "absolute", "left": "185px", "top": "60px", "width": "150px", "height": "76px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid #8B8FE6", "padding": "7px 9px 7px 13px", "overflow": "hidden" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#8B8FE6" }}></span><div style={{ "display": "flex", "justifyContent": "space-between", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9px", "fontWeight": "700", "color": "#8B8FE6" }}><span>OUTCOME</span><span style={{ "fontFamily": "Inter, sans-serif", "color": "#fbbf24", "fontWeight": "600" }}>being built</span></div><div style={{ "fontSize": "11px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "4px" }}>Part of a charge comes back within 90 days</div></div>
              <div style={{ "position": "absolute", "left": "360px", "top": "60px", "width": "150px", "height": "76px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "7px 9px 7px 13px", "overflow": "hidden", "opacity": ".45" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#8B8FE6" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9px", "fontWeight": "700", "color": "#8B8FE6" }}>OUTCOME</div><div style={{ "fontSize": "11px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "4px" }}>Every refund lands in the ledger</div></div>

              {/* requirements */}
              <div style={{ "position": "absolute", "left": "10px", "top": "158px", "width": "150px", "height": "62px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "7px 9px 7px 13px", "overflow": "hidden", "opacity": ".45" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5aa9e6" }}></span><div style={{ "display": "flex", "justifyContent": "space-between", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9px", "fontWeight": "700", "color": "#5aa9e6" }}><span>REQ-007</span><span style={{ "color": "#4ade80" }}>2 of 2</span></div><div style={{ "fontSize": "11px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "4px" }}>Refund link on paid orders</div></div>
              <div style={{ "position": "absolute", "left": "185px", "top": "158px", "width": "150px", "height": "62px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid #5aa9e6", "padding": "7px 9px 7px 13px", "overflow": "hidden", "boxShadow": "0 0 20px rgba(90,169,230,.25)" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5aa9e6" }}></span><div style={{ "display": "flex", "justifyContent": "space-between", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9px", "fontWeight": "700", "color": "#5aa9e6" }}><span>REQ-002</span><span style={{ "color": "#fbbf24" }}>2 of 3</span></div><div style={{ "fontSize": "11px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "4px" }}>Partial refund within 90 days</div></div>
              <div style={{ "position": "absolute", "left": "360px", "top": "158px", "width": "150px", "height": "62px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "7px 9px 7px 13px", "overflow": "hidden", "opacity": ".45" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5aa9e6" }}></span><div style={{ "display": "flex", "justifyContent": "space-between", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9px", "fontWeight": "700", "color": "#5aa9e6" }}><span>REQ-004</span><span style={{ "color": "#f87171" }}>0 of 2</span></div><div style={{ "fontSize": "11px", "fontWeight": "650", "lineHeight": "1.3", "marginTop": "4px" }}>A ledger entry per refund</div></div>

              {/* architecture */}
              <div style={{ "position": "absolute", "left": "10px", "top": "242px", "width": "150px", "height": "48px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "7px 9px 7px 13px", "overflow": "hidden", "opacity": ".45" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5fd39a" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9px", "fontWeight": "700", "color": "#5fd39a" }}>FRONTEND-APP</div><div style={{ "fontSize": "11px", "fontWeight": "650", "marginTop": "3px" }}>storefront-web</div></div>
              <div style={{ "position": "absolute", "left": "185px", "top": "242px", "width": "150px", "height": "48px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid #5fd39a", "padding": "7px 9px 7px 13px", "overflow": "hidden" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5fd39a" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9px", "fontWeight": "700", "color": "#5fd39a" }}>BACKEND-SERVICE</div><div style={{ "fontSize": "11px", "fontWeight": "650", "marginTop": "3px" }}>payments-api</div></div>
              <div style={{ "position": "absolute", "left": "360px", "top": "242px", "width": "150px", "height": "48px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "7px 9px 7px 13px", "overflow": "hidden", "opacity": ".45" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#5fd39a" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9px", "fontWeight": "700", "color": "#5fd39a" }}>WORKER</div><div style={{ "fontSize": "11px", "fontWeight": "650", "marginTop": "3px" }}>ledger-worker</div></div>

              {/* code */}
              <div style={{ "position": "absolute", "left": "10px", "top": "312px", "width": "150px", "height": "40px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid rgba(255,255,255,.16)", "padding": "6px 9px 6px 13px", "overflow": "hidden", "opacity": ".45" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#c07ae0" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9px", "fontWeight": "700", "color": "#c07ae0" }}>FILE</div><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "color": "#c9cdd8" }}>orders/refund.tsx</div></div>
              <div style={{ "position": "absolute", "left": "185px", "top": "312px", "width": "150px", "height": "40px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(26,29,38,.97)", "border": "1.5px solid #c07ae0", "padding": "6px 9px 6px 13px", "overflow": "hidden" }}><span style={{ "position": "absolute", "left": "0", "top": "0", "bottom": "0", "width": "4px", "background": "#c07ae0" }}></span><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9px", "fontWeight": "700", "color": "#c07ae0" }}>FILE</div><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "color": "#c9cdd8" }}>src/refunds.ts</div></div>
              <div style={{ "position": "absolute", "left": "360px", "top": "312px", "width": "150px", "height": "40px", "boxSizing": "border-box", "borderRadius": "10px", "background": "rgba(22,25,34,.6)", "border": "2px dashed rgba(139,147,179,.5)", "padding": "6px 9px 6px 13px", "overflow": "hidden", "opacity": ".55" }}><div style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "9px", "fontWeight": "700", "color": "#8a8f9e" }}>CODE</div><div style={{ "fontSize": "10px", "color": "#8a8f9e" }}>no file yet</div></div>
              </div>
              </div>

              {/* the strip */}
              <div style={{ "position": "absolute", "left": "0", "right": "0", "bottom": "10px", "zIndex": "4", "display": "flex", "justifyContent": "center" }}>
              <div style={{ "display": "flex", "gap": "4px", "padding": "4px", "borderRadius": "12px", "background": "rgba(17,20,31,.85)", "border": "1px solid rgba(255,255,255,.09)" }}>
              <div style={{ "width": "98px", "boxSizing": "border-box", "display": "flex", "flexDirection": "column", "gap": "5px", "padding": "7px 8px", "borderRadius": "9px", "background": "rgba(255,255,255,.035)", "border": "1px solid rgba(255,255,255,.075)" }}><div style={{ "display": "flex", "gap": "5px", "alignItems": "center" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "fontWeight": "700", "color": "#6b7398" }}>1</span><span style={{ "fontSize": "10.5px", "fontWeight": "650", "color": "#eef0ff", "whiteSpace": "nowrap", "overflow": "hidden", "textOverflow": "ellipsis" }}>Customer asks</span></div><div style={{ "display": "flex", "gap": "2px" }}><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#8B8FE6" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#5aa9e6" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#5fd39a" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#c07ae0" }}></i></div><span style={{ "fontSize": "10px", "color": "#4ade80" }}>ready to close</span></div>
              <div style={{ "width": "98px", "boxSizing": "border-box", "display": "flex", "flexDirection": "column", "gap": "5px", "padding": "7px 8px", "borderRadius": "9px", "background": "rgba(139,143,230,.18)", "border": "1px solid rgba(139,143,230,.5)" }}><div style={{ "display": "flex", "gap": "5px", "alignItems": "center" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "fontWeight": "700", "color": "#6b7398" }}>2</span><span style={{ "fontSize": "10.5px", "fontWeight": "650", "color": "#eef0ff", "whiteSpace": "nowrap", "overflow": "hidden", "textOverflow": "ellipsis" }}>Refund issued</span></div><div style={{ "display": "flex", "gap": "2px" }}><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#8B8FE6" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#5aa9e6" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#5fd39a" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "rgba(255,255,255,.1)" }}></i></div><span style={{ "fontSize": "10px", "color": "#8b93b3" }}>being built</span></div>
              <div style={{ "width": "98px", "boxSizing": "border-box", "display": "flex", "flexDirection": "column", "gap": "5px", "padding": "7px 8px", "borderRadius": "9px", "background": "rgba(248,113,113,.09)", "border": "1px solid rgba(248,113,113,.55)" }}><div style={{ "display": "flex", "gap": "5px", "alignItems": "center" }}><span style={{ "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "fontWeight": "700", "color": "#6b7398" }}>3</span><span style={{ "fontSize": "10.5px", "fontWeight": "650", "color": "#eef0ff", "whiteSpace": "nowrap", "overflow": "hidden", "textOverflow": "ellipsis" }}>Ledger updated</span></div><div style={{ "display": "flex", "gap": "2px" }}><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#8B8FE6" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "#5aa9e6" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "rgba(255,255,255,.1)" }}></i><i style={{ "flex": "1", "height": "3px", "borderRadius": "2px", "background": "rgba(255,255,255,.1)" }}></i></div><span style={{ "fontSize": "10px", "color": "#f87171" }}>not built</span></div>
              </div>
              </div>
              </div>
              </div>

            )}
            {shown === 'reqs' && (

              <div style={{ "padding": "14px", "display": "flex", "flexDirection": "column", "minHeight": "500px", "boxSizing": "border-box" }}>
              <span style={{ "fontSize": "17px", "fontWeight": "650", "letterSpacing": "-0.015em" }}>Requirements</span>
              <span style={{ "fontSize": "11.5px", "color": "#8a8f9e" }}>11 of 16 criteria proven</span>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "9px", "marginTop": "12px", "padding": "10px 12px", "borderRadius": "8px", "background": "#1e1a12" }}><span style={{ "width": "7px", "height": "7px", "borderRadius": "50%", "background": "#fbbf24" }}></span><span style={{ "fontSize": "12.5px", "color": "#fbbf24", "flexGrow": "1" }}>1 proposal waiting</span><span style={{ "fontSize": "12px", "fontWeight": "600", "color": "#c9cdd8" }}>Review</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "10px", "padding": "12px 4px", "borderBottom": "1px solid #1e2130", "marginTop": "8px" }}><span style={{ "fontFamily": "'JetBrains Mono', ui-monospace, monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#8a8f9e" }}>REQ-001</span><span style={{ "fontSize": "12.5px", "fontWeight": "600", "flexGrow": "1" }}>Pay by card at checkout</span><span style={{ "fontSize": "11px", "color": "#4fc98f" }}>4 of 4</span></div>
              <div style={{ "display": "flex", "flexDirection": "column", "gap": "8px", "padding": "12px", "borderRadius": "8px", "background": "#1a1d26", "boxShadow": "inset 3px 0 0 #a78bfa" }}>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "10px" }}><span style={{ "fontFamily": "'JetBrains Mono', ui-monospace, monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#c9cdd8" }}>REQ-002</span><span style={{ "fontSize": "12.5px", "fontWeight": "600", "flexGrow": "1" }}>Refund part of a charge within 90 days</span></div>
              <div style={{ "display": "flex", "flexDirection": "column", "gap": "5px", "fontSize": "11.5px", "color": "#c9cdd8" }}>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "8px" }}><span style={{ "width": "7px", "height": "7px", "borderRadius": "50%", "background": "#4fc98f" }}></span>Stays within the charge<span style={{ "marginLeft": "auto", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "color": "#4fc98f" }}>TC-004</span></span>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "8px" }}><span style={{ "width": "7px", "height": "7px", "borderRadius": "50%", "background": "#4fc98f" }}></span>Retrying refunds once<span style={{ "marginLeft": "auto", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "color": "#4fc98f" }}>TC-005</span></span>
              <span style={{ "display": "flex", "alignItems": "center", "gap": "8px" }}><span style={{ "width": "7px", "height": "7px", "borderRadius": "50%", "border": "1.5px solid #8a8f9e", "boxSizing": "border-box" }}></span>Day 91 is refused<span style={{ "marginLeft": "auto", "fontFamily": "'JetBrains Mono', monospace", "fontSize": "10px", "color": "#8B8FE6" }}>TC-006</span></span>
              </div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "8px" }}><span style={{ "padding": "4px 9px", "borderRadius": "6px", "border": "1px solid #a78bfa", "fontSize": "11px", "fontWeight": "600" }}>payments-api</span><span style={{ "fontSize": "11px", "color": "#8a8f9e" }}>ecs fargate &middot; aws</span></div>
              </div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "10px", "padding": "12px 4px", "borderBottom": "1px solid #1e2130" }}><span style={{ "fontFamily": "'JetBrains Mono', ui-monospace, monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#8a8f9e" }}>REQ-003</span><span style={{ "fontSize": "12.5px", "fontWeight": "600", "flexGrow": "1" }}>Webhooks ingested exactly once</span><span style={{ "fontSize": "11px", "color": "#4fc98f" }}>3 of 3</span></div>
              <div style={{ "display": "flex", "alignItems": "center", "gap": "10px", "padding": "12px 4px", "borderBottom": "1px solid #1e2130" }}><span style={{ "fontFamily": "'JetBrains Mono', ui-monospace, monospace", "fontSize": "10.5px", "fontWeight": "700", "color": "#8a8f9e" }}>REQ-004</span><span style={{ "fontSize": "12.5px", "fontWeight": "600", "flexGrow": "1" }}>A ledger entry per refund</span><span style={{ "fontSize": "11px", "color": "#f87171" }}>0 of 2</span></div>
              </div>

            )}
            <div style={{ "height": "60px", "display": "flex", "borderTop": "1px solid #1e2130", "background": "#12141c" }}>
            <span style={{ "flex": "1", "display": "flex", "flexDirection": "column", "alignItems": "center", "justifyContent": "center", "gap": "4px", "fontSize": "11px", "fontWeight": "650" }}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#8B8FE6" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><path d="M4 6h16"></path><path d="M4 12h16"></path><path d="M4 18h10"></path></svg>Work</span>
            <span style={{ "flex": "1", "display": "flex", "flexDirection": "column", "alignItems": "center", "justifyContent": "center", "gap": "4px", "fontSize": "11px", "color": "#8a8f9e" }}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#8a8f9e" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><rect x="3" y="3" width="7" height="7" rx="1.5"></rect><rect x="14" y="14" width="7" height="7" rx="1.5"></rect><path d="M10 6.5h4a3 3 0 0 1 3 3V14"></path></svg>Architecture</span>
            <span style={{ "flex": "1", "display": "flex", "flexDirection": "column", "alignItems": "center", "justifyContent": "center", "gap": "4px", "fontSize": "11px", "color": "#8a8f9e" }}><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#8a8f9e" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><path d="M12 3v12"></path><path d="M8 11l4 4 4-4"></path><path d="M4 19h16"></path></svg>Export</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
