import type { ProjectExportSpecification } from './export-context.js';

export type ParsedSpecification = Pick<ProjectExportSpecification, 'vision' | 'requirements'>;

const AUTO_GENERATED_HEADINGS = new Set([
  'System Architecture Summary',
  'Implementation Progress',
  'Technology & Constraints',
]);

interface HeadingBlock {
  level: number;
  title: string;
  lines: string[];
}

function splitIntoHeadingBlocks(markdown: string): HeadingBlock[] {
  const rawLines = markdown.split('\n');
  const blocks: HeadingBlock[] = [];
  let current: HeadingBlock | null = null;

  for (const line of rawLines) {
    const match = line.match(/^(#{1,6})\s+(.+)$/);
    if (match) {
      if (current) blocks.push(current);
      current = { level: match[1].length, title: match[2].trim(), lines: [] };
    } else if (current) {
      current.lines.push(line);
    }
  }
  if (current) blocks.push(current);
  return blocks;
}

function isAutoGenerated(block: HeadingBlock): boolean {
  if (AUTO_GENERATED_HEADINGS.has(block.title)) return true;
  if (block.lines.some(l => l.includes('<!-- auto-generated: skip -->'))) return true;
  return false;
}

function parseVision(blocks: HeadingBlock[]): string {
  const visionBlock = blocks.find(b => b.level === 2 && b.title === 'Vision');
  if (!visionBlock) return '';
  return visionBlock.lines
    .join('\n')
    .trim();
}

function stripCoverageTag(title: string): string {
  return title.replace(/\s+--\s+\d+\/\d+\s+criteria\s+met$/, '').trim();
}

function parseRequirements(blocks: HeadingBlock[]): ParsedSpecification['requirements'] {
  const requirements: ParsedSpecification['requirements'] = [];

  for (let i = 0; i < blocks.length; i++) {
    const catBlock = blocks[i];
    if (catBlock.level !== 3) continue;
    const catMatch = catBlock.title.match(/^(.+?)\s+Requirements$/);
    if (!catMatch) continue;

    const rawCategory = catMatch[1].trim().toLowerCase().replace(/-/g, '-');
    const category = rawCategory as 'functional' | 'non-functional' | 'technical' | 'business';

    for (let j = i + 1; j < blocks.length; j++) {
      const reqBlock = blocks[j];
      if (reqBlock.level <= 3) break;
      if (reqBlock.level !== 4) continue;

      const name = stripCoverageTag(reqBlock.title);
      let requirementId = '';
      const descLines: string[] = [];
      const acceptanceCriteria: Array<{ text: string; met?: boolean }> = [];
      let inCriteria = false;

      for (const line of reqBlock.lines) {
        const metaMatch = line.match(/^\*?\*?ID:\*?\*?\s*([^\s|]+)/);
        if (metaMatch) {
          requirementId = metaMatch[1];
          continue;
        }

        if (/^\*?\*?Acceptance Criteria\*?\*?:?/i.test(line)) {
          inCriteria = true;
          continue;
        }

        const checkboxMatch = line.match(/^\s*-\s*\[([ xX])\]\s+(.+)/);
        if (checkboxMatch) {
          inCriteria = true;
          acceptanceCriteria.push({
            text: checkboxMatch[2].trim(),
            met: checkboxMatch[1].toLowerCase() === 'x',
          });
          continue;
        }

        if (!inCriteria) {
          descLines.push(line);
        }
      }

      requirements.push({
        requirementId,
        name,
        description: descLines.join('\n').trim(),
        category,
        status: 'active',
        acceptanceCriteria,
      });
    }
  }

  return requirements;
}

export function parseSpecificationMarkdown(markdown: string): ParsedSpecification {
  const blocks = splitIntoHeadingBlocks(markdown);
  const editableBlocks = blocks.filter(b => !isAutoGenerated(b));

  return {
    vision: parseVision(editableBlocks),
    requirements: parseRequirements(editableBlocks),
  };
}
