// D2 (docs/WORK_LOOP_PLAN.md): `.nodespec/BOARD.md` — the git projection of
// the work board. ONE checkbox line per criterion and per task, grouped by
// requirement, with the derived status line and the node/test columns. ZERO
// prose: every line matches the grammar below (the no-prose test enforces
// it); rationale lives in the per-node task docs, never here.
//
// THE FILE IS A PROJECTION, NEVER A SECOND TRUTH. It is regenerated on every
// push from the same inputs the canvas board reads (deriveWorkStatus — the
// literal same function, cross-runtime). Ticks made IN the file ingest
// through the SAME delta lanes task docs use: parseBoardMd feeds
// computeCriterionDeltas and computeTaskDeltas unchanged, the deltas ride
// the change card next to the task-doc deltas, and apply happens through the
// existing apply lanes (tick-only, approval-gated). Any line this parser
// cannot attribute is FLAGGED, never guessed.
//
// LAYOUT (owner refinement 2026-08-21 — "a table in git, quick triage"):
// a GFM SUMMARY TABLE heads the file — one row per requirement with status
// emoji + aligned criteria/tasks/tests counts, each row anchor-linked to its
// detail section — because pulled or viewed on GitHub, the file must READ as
// a board. GFM renders checkboxes only as list items (never in table cells),
// so ticking stays in the sections below, and the sections align the three
// evidence lanes per requirement: Criteria (tickable) · Tasks (tickable) ·
// Tests (read-only status glyphs + the plan file's path — tests flip via
// report_test_results, never a checkbox).
//
// Grammar (every non-blank line is one of):
//   # Work Board <!-- nodespec-board v1 -->
//   <!-- ... -->                                  (instruction comment)
//   | ... |                                       (summary table rows)
//   ## <REQ-id> — <name> <!-- r:<REQ-id> -->
//   status: <derived> · criteria n/m · tasks n/m · tests p/f/s of t
//   ### Criteria
//   ### Tasks — <node label> <!-- n:<node uuid> -->
//   ### Tests — <plan path>   (path present when the plan artifact exists)
//   - [ ] / - [x] checkbox lines (criterion text, or task with <!-- t:key -->)
//     ↳ tasks: …/tests: … read-only LATERAL annotation under a criterion
//   - ✅/❌/▫️ <test id> — <name> read-only test lines ( (stale) suffixed)

import { computeArchivedRowIds, deriveWorkStatus, type WorkStatus } from "./derive-status.ts";
import { alignCriterionLanes, formatCriterionAnnotation, taskEvidenceDone } from "./board-alignment.ts";
import { findExistingTestArtifact } from "./test-document-generator.ts";
import {
  computeTaskDeltas,
  parseTaskDocTasks,
  type ParsedTask,
  type TaskDeltaResult,
} from "./task-deltas.ts";
import {
  computeCriterionDeltas,
  type CriterionDeltaResult,
  type CurrentCriterion,
} from "./criterion-deltas.ts";

export const BOARD_PATH = ".nodespec/BOARD.md";
export const BOARD_HEADER = "# Work Board <!-- nodespec-board v1 -->";
const BOARD_NOTE =
  "<!-- Generated by NodeSpec on every push - a PROJECTION of the design state, never a second truth. The table is the triage summary; tick boxes in the sections BELOW to record completion (ingested on push, applied after approval). Do not edit text - lines are matched exactly. Test lines are read-only: tests flip via report_test_results. -->";

/** Triage-scannable status glyphs for the summary table. */
export const STATUS_EMOJI: Record<WorkStatus, string> = {
  "verified": "✅",
  "evidence-due": "🟠",
  "in-progress": "🔵",
  "pending": "⬜",
  "blocked": "⛔",
  "archived": "🗄️",
};

const TEST_GLYPH: Record<string, string> = { passed: "✅", failed: "❌" };

/** GitHub's heading-anchor slug, mirrored best-effort — a slightly-off slug
 *  degrades to a non-jumping link, never to broken content. */
export function gfmSlug(text: string): string {
  return text.toLowerCase().replace(/[^\w\s-]/g, "").replace(/\s/g, "-");
}

const escapeCell = (text: string): string => text.replace(/\|/g, "\\|");

export interface BoardTaskLine {
  displayId: string;
  title: string;
  key: string;
  done: boolean;
  /** D3 alignment: criteria this work order serves (from the doc's ↳ lines). */
  serves?: Array<{ reqId: string; text: string }>;
}

export interface BoardRequirement {
  /** Human id (REQ-###) — the identity criteria are keyed by. */
  requirementId: string;
  name: string;
  status: string;
  archived: boolean;
  criteria: Array<{ text: string; met?: boolean; evidenceStale?: unknown; testId?: string }>;
  nodes: Array<{ id: string; label: string; tasks: BoardTaskLine[] }>;
  tests: { total: number; passed: number; failed: number; stale: number };
  /** Read-only per-case detail (sorted at render). rowId is the test_cases
   *  uuid — what criterion.testId points at (the alignment key). */
  testCases: Array<{ rowId?: string; testId: string; name: string; status: string; stale: boolean }>;
  /** The requirement's test-plan artifact path, when one exists. */
  planPath: string | null;
}

export interface BoardModel {
  requirements: BoardRequirement[];
}

// ── render ────────────────────────────────────────────────────────────────────

export function renderBoardMd(model: BoardModel): string {
  const lines: string[] = [BOARD_HEADER, BOARD_NOTE, ""];
  // Stable order: by human requirement id — regeneration is byte-idempotent.
  const reqs = [...model.requirements].sort((a, b) => a.requirementId.localeCompare(b.requirementId));

  // Triage first: pulled or viewed on GitHub, the file opens as a TABLE —
  // every row one requirement, anchor-linked to its tickable section below.
  const derived = reqs.map((req) => {
    // Owner refinement 2026-09-01: evidence-derived task completion. Counts
    // and annotations reflect it; the tickable checkbox lines below NEVER do
    // (they are the tick-ingestion surface and keep the recorded state).
    const effectiveNodes = req.nodes.map((node) => ({
      ...node,
      tasks: node.tasks.map((t) => ({
        ...t,
        evidenceDone: taskEvidenceDone({ requirementId: req.requirementId, criteria: req.criteria, task: t }),
      })),
    }));
    const taskTotal = req.nodes.reduce((n, node) => n + node.tasks.length, 0);
    const taskDone = effectiveNodes.reduce((n, node) => n + node.tasks.filter((t) => t.done || t.evidenceDone).length, 0);
    const status = deriveWorkStatus({
      archived: req.archived,
      requirementStatus: req.status,
      criteria: req.criteria,
      tests: req.tests,
      tasks: { total: taskTotal, done: taskDone },
    });
    return { req, effectiveNodes, status, taskTotal, taskDone };
  });
  lines.push("| Requirement | Status | Criteria | Tasks | Tests P/F/S | Nodes |");
  lines.push("|---|---|---|---|---|---|");
  for (const { req, status, taskTotal, taskDone } of derived) {
    const slug = gfmSlug(`${req.requirementId} — ${req.name}`);
    const statusCell = `${STATUS_EMOJI[status.status]} ${status.status}${status.tier ? ` (${status.tier})` : ""}`;
    const nodesCell = req.nodes.map((n) => escapeCell(n.label)).sort().join(", ") || "—";
    lines.push(
      `| [${req.requirementId}](#${slug}) — ${escapeCell(req.name)} | ${statusCell} | ${status.counts.criteriaMet}/${status.counts.criteriaTotal} | ${taskDone}/${taskTotal} | ${req.tests.passed}/${req.tests.failed}/${req.tests.stale} of ${req.tests.total} | ${nodesCell} |`,
    );
  }
  lines.push("");

  for (const { req, effectiveNodes, status, taskTotal, taskDone } of derived) {
    lines.push(`## ${req.requirementId} — ${req.name} <!-- r:${req.requirementId} -->`);
    lines.push(
      `status: ${status.status}${status.tier ? ` (${status.tier})` : ""} · criteria ${status.counts.criteriaMet}/${status.counts.criteriaTotal} · tasks ${taskDone}/${taskTotal} · tests ${req.tests.passed}/${req.tests.failed}/${req.tests.stale} of ${req.tests.total}`,
    );
    // D3 refinement 2: LATERAL alignment — each criterion carries a read-only
    // `↳ tasks/tests` annotation naming exactly the work orders that serve it
    // (the doc's serves-lines) and the test bound to it (criterion.testId).
    // Annotations are pointers, not tick surfaces: tasks still tick in their
    // sections below, tests never tick anywhere.
    const lanes = alignCriterionLanes({
      requirementId: req.requirementId,
      criteria: req.criteria,
      tasks: [...effectiveNodes].sort((a, b) => a.label.localeCompare(b.label)).flatMap((node) =>
        node.tasks.map((t) => ({
          displayId: t.displayId, title: t.title,
          done: t.done || t.evidenceDone, evidenceDone: t.evidenceDone,
          nodeLabel: node.label, serves: t.serves,
        })),
      ),
      tests: [...req.testCases].sort((a, b) => a.testId.localeCompare(b.testId)),
    });
    if (req.criteria.length > 0) {
      lines.push("### Criteria");
      for (const c of req.criteria) {
        lines.push(`- [${c.met === true ? "x" : " "}] ${c.text}`);
        const annotation = formatCriterionAnnotation(lanes.byCriterion.get(c.text)!);
        if (annotation) lines.push(`  ${annotation}`);
      }
    }
    for (const node of [...req.nodes].sort((a, b) => a.label.localeCompare(b.label))) {
      if (node.tasks.length === 0) continue;
      lines.push(`### Tasks — ${node.label} <!-- n:${node.id} -->`);
      for (const t of node.tasks) {
        lines.push(`- [${t.done ? "x" : " "}] **${t.displayId} — ${t.title}** <!-- t:${t.key} -->`);
      }
    }
    // Tests aligned to a criterion already read on its annotation line —
    // this section keeps only the LEFTOVERS (cases no criterion points at,
    // shown so evidence never hides) and the plan path. Read-only always:
    // tests flip via report_test_results, never a checkbox.
    if (lanes.otherTests.length > 0 || req.planPath) {
      lines.push(`### Tests${req.planPath ? ` — ${req.planPath}` : ""}`);
      for (const tc of lanes.otherTests) {
        const glyph = TEST_GLYPH[tc.status] ?? "▫️";
        lines.push(`- ${glyph} ${tc.testId} — ${tc.name}${tc.stale ? " (stale)" : ""}`);
      }
    }
    lines.push("");
  }
  return lines.join("\n");
}

// ── parse (ingestion) ─────────────────────────────────────────────────────────

const REQ_HEADING = /^##\s+.*<!--\s*r:([^\s]+)\s*-->\s*$/;
const NODE_HEADING = /^###\s+Tasks\s+—\s+.*<!--\s*n:([0-9a-fA-F-]{36})\s*-->\s*$/;
const CRITERIA_HEADING = /^###\s+Criteria\s*$/;
const TASK_LINE = /^-\s+\[([ xX])\]\s+\*\*([^—*]+)—\s*(.+?)\*\*\s*<!--\s*t:([a-f0-9]{8}(?:-\d+)?)\s*-->\s*$/;
const CRITERION_LINE = /^-\s+\[([ xX])\]\s+(.+)$/;

export interface ParsedBoard {
  /** REQ-id → criterion checkbox lines (the computeCriterionDeltas shape). */
  criteria: Record<string, Array<{ text: string; checked: boolean }>>;
  /** node uuid → task lines (the computeTaskDeltas shape). */
  tasksByNode: Record<string, ParsedTask[]>;
  flagged: Array<{ reason: string; detail: string }>;
}

export function parseBoardMd(markdown: string): ParsedBoard {
  const out: ParsedBoard = { criteria: {}, tasksByNode: {}, flagged: [] };
  if (!markdown) return out;
  let currentReq: string | null = null;
  let mode: "none" | "criteria" | "tasks" = "none";
  let currentNode: string | null = null;

  for (const raw of markdown.split(/\r?\n/)) {
    const line = raw.trimEnd();
    const req = REQ_HEADING.exec(line);
    if (req) {
      currentReq = req[1];
      mode = "none";
      currentNode = null;
      continue;
    }
    if (CRITERIA_HEADING.test(line)) { mode = "criteria"; currentNode = null; continue; }
    const node = NODE_HEADING.exec(line);
    if (node) { mode = "tasks"; currentNode = node[1]; continue; }
    if (line.startsWith("#")) { mode = "none"; currentNode = null; continue; }

    if (mode === "tasks" && currentNode) {
      const task = TASK_LINE.exec(line);
      if (task) {
        const [, box, displayId, title, key] = task;
        (out.tasksByNode[currentNode] ??= []).push({
          displayId: displayId.trim(),
          title: title.trim(),
          key,
          checked: box.toLowerCase() === "x",
        });
        continue;
      }
      if (CRITERION_LINE.test(line)) {
        out.flagged.push({ reason: "task-line-no-anchor", detail: line.slice(0, 120) });
      }
      continue;
    }
    if (mode === "criteria" && currentReq) {
      const crit = CRITERION_LINE.exec(line);
      if (crit) {
        (out.criteria[currentReq] ??= []).push({ text: crit[2].trim(), checked: crit[1].toLowerCase() === "x" });
      }
      continue;
    }
    if (CRITERION_LINE.test(line)) {
      out.flagged.push({ reason: "checkbox-outside-section", detail: line.slice(0, 120) });
    }
  }
  return out;
}

// ── deltas: THE SAME LANES task docs use ─────────────────────────────────────

export function computeBoardTickDeltas(
  parsed: ParsedBoard,
  currentCriteria: Record<string, CurrentCriterion[]>,
  doneByNodeKey: ReadonlyMap<string, boolean>,
): { criterionDeltas: CriterionDeltaResult; taskDeltas: TaskDeltaResult } {
  const criterionDeltas = computeCriterionDeltas(
    { requirements: parsed.criteria },
    currentCriteria,
  );
  const taskDeltas: TaskDeltaResult = { deltas: [], flagged: [] };
  for (const [nodeId, tasks] of Object.entries(parsed.tasksByNode)) {
    const perNode = new Map<string, boolean>();
    for (const t of tasks) {
      if (t.key) perNode.set(t.key, doneByNodeKey.get(`${nodeId}::${t.key}`) === true);
    }
    const result = computeTaskDeltas(nodeId, { tasks, flagged: [] }, perNode);
    taskDeltas.deltas.push(...result.deltas);
    taskDeltas.flagged.push(...result.flagged);
  }
  return { criterionDeltas, taskDeltas };
}

/** Merge board deltas with task-doc deltas on one card — same tick from both
 *  sources reports once (apply is idempotent anyway; the CARD must be clean). */
export function mergeCriterionDeltaResults(a: CriterionDeltaResult, b: CriterionDeltaResult): CriterionDeltaResult {
  const deltas = [...a.deltas];
  const seen = new Set(a.deltas.map((d) => `${d.requirementId}::${d.direction}::${d.text}`));
  for (const d of b.deltas) {
    const key = `${d.requirementId}::${d.direction}::${d.text}`;
    if (!seen.has(key)) { seen.add(key); deltas.push(d); }
  }
  const flagged = [...a.flagged];
  const seenFlags = new Set(a.flagged.map((f) => `${f.requirementId}::${f.text}`));
  for (const f of b.flagged) {
    const key = `${f.requirementId}::${f.text}`;
    if (!seenFlags.has(key)) { seenFlags.add(key); flagged.push(f); }
  }
  return { deltas, flagged };
}

export function mergeTaskDeltaResults(a: TaskDeltaResult, b: TaskDeltaResult): TaskDeltaResult {
  const deltas = [...a.deltas];
  const seen = new Set(a.deltas.map((d) => `${d.nodeId}::${d.key}::${d.direction}`));
  for (const d of b.deltas) {
    const key = `${d.nodeId}::${d.key}::${d.direction}`;
    if (!seen.has(key)) { seen.add(key); deltas.push(d); }
  }
  return { deltas, flagged: [...a.flagged, ...b.flagged] };
}

// ── model assembly (server, at push time) ────────────────────────────────────

/**
 * Assemble the board model from what git-push already holds (graph + the
 * loaded spec plane) plus ONE test_cases and ONE task_items batch. Relations
 * feed the SAME archived-set rule the canvas uses.
 */
// deno-lint-ignore no-explicit-any
export async function buildBoardModel(supabase: any, projectId: string, args: {
  graph: {
    nodes?: Record<string, { id: string; label?: string }>;
    artifacts?: Record<string, { nodeId?: string; kind?: string; path?: string; content?: string }>;
  };
  requirements: Array<{
    id: string;
    requirement_id: string;
    name?: string | null;
    status?: string | null;
    acceptance_criteria?: unknown;
  }>;
  mappings: Array<{ requirementId: string; nodeId: string }>;
}): Promise<BoardModel> {
  const reqRowIds = args.requirements.map((r) => r.id);
  const [testsRes, tasksRes, relsRes] = await Promise.all([
    reqRowIds.length > 0
      ? supabase.from("test_cases").select("id, requirement_id, test_id, name, status, stale").in("requirement_id", reqRowIds).is("retired_at", null)
      : Promise.resolve({ data: [] }),
    supabase.from("task_items").select("node_id, task_key, done").eq("project_id", projectId),
    reqRowIds.length > 0
      ? supabase.from("requirement_relations").select("from_requirement_id, to_requirement_id, relation_type").in("from_requirement_id", reqRowIds)
      : Promise.resolve({ data: [] }),
  ]);

  const testsByRowId = new Map<string, { total: number; passed: number; failed: number; stale: number }>();
  const casesByRowId = new Map<string, Array<{ testId: string; name: string; status: string; stale: boolean }>>();
  // deno-lint-ignore no-explicit-any
  for (const t of ((testsRes.data ?? []) as any[])) {
    const bucket = testsByRowId.get(t.requirement_id) ?? { total: 0, passed: 0, failed: 0, stale: 0 };
    bucket.total += 1;
    if (t.status === "passed") bucket.passed += 1;
    if (t.status === "failed") bucket.failed += 1;
    if (t.stale === true) bucket.stale += 1;
    testsByRowId.set(t.requirement_id, bucket);
    const cases = casesByRowId.get(t.requirement_id) ?? [];
    cases.push({ rowId: String(t.id ?? ""), testId: String(t.test_id ?? ""), name: String(t.name ?? ""), status: String(t.status ?? ""), stale: t.stale === true });
    casesByRowId.set(t.requirement_id, cases);
  }
  const doneByNodeKey = new Map<string, boolean>();
  // deno-lint-ignore no-explicit-any
  for (const row of ((tasksRes.data ?? []) as any[])) {
    doneByNodeKey.set(`${row.node_id}::${row.task_key}`, row.done === true);
  }

  const criteriaOf = (raw: unknown): Array<{ text: string; met?: boolean; evidenceStale?: unknown; testId?: string }> => {
    if (!Array.isArray(raw)) return [];
    return raw
      .map((c) =>
        typeof c === "string"
          ? { text: c }
          // deno-lint-ignore no-explicit-any
          : { text: String((c as any)?.text ?? ""), met: (c as any)?.met === true, evidenceStale: (c as any)?.evidenceStale, ...(typeof (c as any)?.testId === "string" ? { testId: (c as any).testId } : {}) },
      )
      .filter((c) => c.text);
  };

  const archived = computeArchivedRowIdsFromRows(args.requirements, criteriaOf, (relsRes.data ?? []) as Array<{ from_requirement_id: string; to_requirement_id: string; relation_type: string }>);

  const nodesByReq = new Map<string, string[]>();
  for (const m of args.mappings) {
    const list = nodesByReq.get(m.requirementId) ?? [];
    if (!list.includes(m.nodeId)) list.push(m.nodeId);
    nodesByReq.set(m.requirementId, list);
  }
  const taskDocByNode = new Map<string, string>();
  for (const artifact of Object.values(args.graph.artifacts ?? {})) {
    if (artifact.kind === "task" && artifact.nodeId && artifact.content) {
      taskDocByNode.set(artifact.nodeId, artifact.content);
    }
  }

  const requirements: BoardRequirement[] = args.requirements.map((r) => {
    const nodeIds = nodesByReq.get(r.requirement_id) ?? [];
    const nodes = nodeIds.map((nodeId) => {
      const doc = taskDocByNode.get(nodeId);
      const tasks: BoardTaskLine[] = doc
        ? parseTaskDocTasks(doc).tasks
          .filter((t): t is ParsedTask & { key: string } => !!t.key)
          .map((t) => ({
            displayId: t.displayId,
            title: t.title,
            key: t.key,
            done: doneByNodeKey.get(`${nodeId}::${t.key}`) ?? t.checked,
            ...(t.serves ? { serves: t.serves } : {}),
          }))
        : [];
      return { id: nodeId, label: args.graph.nodes?.[nodeId]?.label ?? nodeId.slice(0, 8), tasks };
    });
    // The plan artifact match mirrors findExistingTestArtifact exactly — it
    // IS that function, so the board and the freshness lane cannot disagree
    // about whether a requirement's plan exists.
    const plan = findExistingTestArtifact(
      (args.graph.artifacts ?? {}) as Record<string, { kind: string; path?: string; metadata?: Record<string, unknown> | null }>,
      r.requirement_id,
      r.name ?? r.requirement_id,
    );
    return {
      requirementId: r.requirement_id,
      name: r.name ?? r.requirement_id,
      status: r.status ?? "pending",
      archived: archived.has(r.id),
      criteria: criteriaOf(r.acceptance_criteria),
      nodes,
      tests: testsByRowId.get(r.id) ?? { total: 0, passed: 0, failed: 0, stale: 0 },
      testCases: casesByRowId.get(r.id) ?? [],
      planPath: plan?.path ?? null,
    };
  });

  return { requirements };
}

function computeArchivedRowIdsFromRows(
  rows: Array<{ id: string; status?: string | null; acceptance_criteria?: unknown }>,
  criteriaOf: (raw: unknown) => Array<{ met?: boolean }>,
  relations: Array<{ from_requirement_id: string; to_requirement_id: string; relation_type: string }>,
): Set<string> {
  return computeArchivedRowIds(
    rows.map((r) => ({ id: r.id, status: r.status ?? "pending", acceptanceCriteria: criteriaOf(r.acceptance_criteria) })),
    relations.map((rel) => ({
      fromRequirementId: rel.from_requirement_id,
      toRequirementId: rel.to_requirement_id,
      relationType: rel.relation_type,
    })),
  );
}
