import type { ContainerTypeDefinition } from './container-types.js';

export const STATIC_CONTAINER_TYPE_DATA: ContainerTypeDefinition[] = [
  {
    id: 'vpc',
    label: 'VPC / Virtual Network',
    description: 'Isolated cloud network environment. Contains subnets, security groups, route tables, and hosts applications, databases, and orchestration clusters.',
    icon: 'cloud',
    layer: 'infrastructure',
    containerStyle: 'hosting',
    canContain: [
      'subnet', 'realtime-service', 'scheduled-trigger', 'k8s-cluster', 'k8s-namespace', 'docker-compose', 'docker-swarm',
      'ecs-cluster', 'docker-container', 'serverless-function', 'microservice-boundary',
      'backend-service',
      'worker', 'database', 'graph-db', 'time-series-db', 'search-engine',
      'cache', 'auth-provider', 'load-balancer', 'api-gateway', 'message-broker',
      'event-stream', 'monitoring', 'logging', 'inference-service', 'ml-pipeline',
      'object-storage', 'vector-database'],
    defaultMetadata: {
      cidrBlock: '10.0.0.0/16',
      region: 'us-east-1',
      enableDnsHostnames: true,
      enableDnsSupport: true,
      tenancy: 'default',
      internetGateway: true,
      natGateway: true,
      flowLogsEnabled: true,
      tags: { Name: 'production-vpc', Environment: 'production', ManagedBy: 'nodal' },
    },
    metadataSchema: {
      cidrBlock: { type: 'string', label: 'CIDR Block', description: 'IP address range (e.g., 10.0.0.0/16)', required: true, default: '10.0.0.0/16' },
      region: { type: 'string', label: 'Region', description: 'Geographic region (e.g., us-east-1, eastus, us-central1)', required: true },
      tags: { type: 'object', label: 'Resource Tags', description: 'Key-value pairs for organization and billing' },
      flowLogsEnabled: { type: 'boolean', label: 'Flow Logs', description: 'Enable traffic flow logging', default: false },
      internetGateway: { type: 'boolean', label: 'Internet Gateway', description: 'Allow internet access', default: true },
      natGateway: { type: 'boolean', label: 'NAT Gateway', description: 'Allow private subnets to access internet', default: false },
      enableDnsHostnames: { type: 'boolean', label: 'DNS Hostnames', description: 'Allow instances to receive DNS hostnames', default: true },
      enableDnsSupport: { type: 'boolean', label: 'DNS Support', description: 'Enable DNS server', default: true },
    },
  },
  {
    id: 'subnet',
    label: 'Subnet',
    description: 'Logical subdivision of a VPC. Can be public (internet-facing) or private (internal only).',
    icon: 'layers',
    layer: 'infrastructure',
    containerStyle: 'hosting',
    canContain: [
      'k8s-cluster', 'docker-container', 'serverless-function',
      'backend-service', 'worker', 'database', 'cache', 'load-balancer',
    ],
    defaultMetadata: {
      cidrBlock: '10.0.1.0/24',
      availabilityZone: '',
      type: 'public',
      routeTable: '',
    },
    metadataSchema: {
      cidrBlock: { type: 'string', label: 'CIDR Block', description: 'IP address range for the subnet', required: true },
      availabilityZone: { type: 'string', label: 'Availability Zone', description: 'Physical location', required: true },
      type: { type: 'string', label: 'Subnet Type', description: 'public or private', default: 'public' },
      routeTableId: { type: 'string', label: 'Route Table ID', description: 'Associated route table for traffic routing' },
      autoAssignPublicIp: { type: 'boolean', label: 'Auto-assign Public IP', description: 'Automatically assign public IPs', default: false },
    },
  },
  {
    id: 'hypervisor',
    label: 'Hypervisor Cluster',
    description: 'Virtualization platform (vSphere, Hyper-V, Proxmox). Hosts virtual machines with HA and live migration.',
    icon: 'server',
    layer: 'infrastructure',
    containerStyle: 'hosting',
    canContain: [
      'virtual-machine', 'vpc', 'k8s-cluster', 'docker-compose',
      'docker-container', 'backend-service', 'worker', 'database', 'cache',
    ],
    defaultMetadata: {
      platform: 'vmware-vsphere',
      clusterName: '',
      haEnabled: true,
      hostCount: 3,
    },
    metadataSchema: {
      platform: { type: 'string', label: 'Platform', description: 'vmware-vsphere, hyper-v, proxmox, kvm', default: 'vmware-vsphere' },
      clusterName: { type: 'string', label: 'Cluster Name', description: 'Virtualization cluster identifier', required: true },
      haEnabled: { type: 'boolean', label: 'High Availability', description: 'Enable automatic VM failover', default: true },
      hostCount: { type: 'number', label: 'Host Count', description: 'Number of hosts in cluster', default: 3 },
    },
  },
  {
    id: 'virtual-machine',
    label: 'Virtual Machine',
    description: 'Generic VM instance on any hypervisor (vSphere, Hyper-V, KVM, etc.).',
    icon: 'monitor',
    layer: 'infrastructure',
    containerStyle: 'hosting',
    canContain: [
      'k8s-cluster', 'docker-compose', 'docker-container',
      'backend-service', 'worker', 'database', 'cache'],
    defaultMetadata: {
      osType: 'linux',
      osVersion: 'Ubuntu 22.04 LTS',
      cpuCores: 4,
      memoryGB: 16,
      diskGB: 100,
      diskType: 'ssd',
      hypervisor: 'vmware',
      snapshotsEnabled: true,
    },
    metadataSchema: {
      osType: { type: 'string', label: 'OS Type', description: 'linux, windows, or other', default: 'linux' },
      osVersion: { type: 'string', label: 'OS Version', description: 'Operating system version', default: 'Ubuntu 22.04 LTS' },
      cpuCores: { type: 'number', label: 'CPU Cores', description: 'Number of virtual CPUs', default: 4 },
      memoryGB: { type: 'number', label: 'Memory (GB)', description: 'RAM in gigabytes', default: 16 },
      diskGB: { type: 'number', label: 'Disk Size (GB)', description: 'Primary disk size', default: 100 },
      diskType: { type: 'string', label: 'Disk Type', description: 'ssd, nvme, or hdd', default: 'ssd' },
      hypervisor: { type: 'string', label: 'Hypervisor', description: 'vmware, hyper-v, kvm, xen, virtualbox', default: 'vmware' },
      snapshotsEnabled: { type: 'boolean', label: 'Snapshots', description: 'Allow VM snapshots', default: true },
    },
  },
  {
    id: 'embedded-system',
    label: 'Embedded System',
    description: 'Hardware-software integrated system for aerospace, automotive, industrial control, and IoT.',
    icon: 'cpu',
    layer: 'infrastructure',
    containerStyle: 'hosting',
    canContain: ['backend-service', 'worker', 'frontend-app', 'database'],
    defaultMetadata: {
      systemType: 'real-time',
      powerBudget: '10W',
      operatingTemperature: '-40C to 85C',
      debugInterface: 'JTAG',
      firmwareUpdateMethod: 'OTA',
    },
    metadataSchema: {
      systemType: { type: 'string', label: 'System Type', description: 'real-time, soft-real-time, general-purpose', default: 'real-time' },
      powerBudget: { type: 'string', label: 'Power Budget', description: 'Maximum power consumption', required: true },
      operatingTemperature: { type: 'string', label: 'Operating Temperature', description: 'Temperature range', default: '-40C to 85C' },
      certifications: { type: 'array', label: 'Certifications', description: 'DO-178C, IEC 61508, ISO 26262, etc.' },
      debugInterface: { type: 'string', label: 'Debug Interface', description: 'JTAG, SWD, UART, none', default: 'JTAG' },
    },
  },
  {
    id: 'k8s-cluster',
    label: 'Kubernetes Cluster',
    description: 'Container orchestration platform. Manages deployments, scaling, and networking of containerized applications.',
    icon: 'box',
    layer: 'orchestration',
    containerStyle: 'hosting',
    canContain: [
      'k8s-namespace', 'scheduled-trigger', 'docker-container', 'serverless-function',
      'backend-service', 'worker', 'database', 'cache',
      'message-broker', 'monitoring', 'logging', 'inference-service', 'vector-database'],
    defaultMetadata: {
      version: '1.28',
      nodeCount: 3,
      nodeType: 't3.medium',
      networking: 'calico',
      ingressController: 'nginx',
      certManager: true,
      clusterAutoscaler: true,
      logging: 'CloudWatch',
      monitoring: 'Prometheus',
      rbacEnabled: true,
    },
    metadataSchema: {
      version: { type: 'string', label: 'Kubernetes Version', description: 'Cluster version (e.g., 1.28)', required: true, default: '1.28' },
      nodeCount: { type: 'number', label: 'Node Count', description: 'Number of worker nodes', required: true, default: 3 },
      nodeType: { type: 'string', label: 'Node Instance Type', description: 'Instance type for nodes', default: 't3.medium' },
      networking: { type: 'string', label: 'CNI Plugin', description: 'Network plugin (calico, flannel, weave)', default: 'calico' },
      ingressController: { type: 'string', label: 'Ingress Controller', description: 'nginx, traefik, or istio', default: 'nginx' },
      certManager: { type: 'boolean', label: 'Cert Manager', description: 'Automatic TLS certificate management', default: true },
      monitoring: { type: 'string', label: 'Monitoring Stack', description: 'Prometheus, Datadog, etc.', default: 'Prometheus' },
      rbacEnabled: { type: 'boolean', label: 'RBAC Enabled', description: 'Role-based access control', default: true },
    },
  },
  {
    id: 'k8s-namespace',
    label: 'Kubernetes Namespace',
    description: 'Logical isolation boundary within a K8s cluster. Provides resource quotas, network policies, and RBAC separation.',
    icon: 'folder',
    layer: 'orchestration',
    containerStyle: 'hosting',
    canContain: [
      'docker-container', 'scheduled-trigger', 'serverless-function',
      'backend-service', 'worker', 'database', 'cache', 'message-broker',
      'monitoring', 'logging', 'inference-service', 'vector-database'],
    defaultMetadata: {
      resourceQuota: true,
      cpuLimit: '10',
      cpuRequest: '2',
      memoryLimit: '20Gi',
      memoryRequest: '4Gi',
      storageLimit: '50Gi',
      podLimit: 100,
      networkPolicies: ['deny-all-ingress'],
      limitRanges: true,
      rbacEnabled: true,
    },
    metadataSchema: {
      resourceQuota: { type: 'boolean', label: 'Resource Quota', description: 'Enforce resource limits', default: true },
      cpuLimit: { type: 'string', label: 'CPU Limit', description: 'Max CPU cores', default: '10' },
      memoryLimit: { type: 'string', label: 'Memory Limit', description: 'Max memory', default: '20Gi' },
      podLimit: { type: 'number', label: 'Pod Limit', description: 'Maximum number of pods', default: 100 },
      networkPolicies: { type: 'array', label: 'Network Policies', description: 'Network security policies', default: ['deny-all-ingress'] },
      limitRanges: { type: 'boolean', label: 'Limit Ranges', description: 'Default per-pod resource limits', default: true },
      rbacEnabled: { type: 'boolean', label: 'RBAC', description: 'Role-based access control', default: true },
    },
  },
  {
    id: 'docker-compose',
    label: 'Docker Compose Stack',
    description: 'Multi-container Docker application. Defines and runs multiple containers with shared networking and volumes.',
    icon: 'layers',
    layer: 'orchestration',
    containerStyle: 'hosting',
    canContain: [
      'docker-container', 'backend-service', 'worker', 'database', 'cache',
      'message-broker', 'frontend-app', 'monitoring', 'logging', 'inference-service', 'vector-database'],
    defaultMetadata: {
      version: '3.8',
      networks: ['default'],
      volumes: [],
    },
    metadataSchema: {
      version: { type: 'string', label: 'Compose Version', description: 'Docker Compose file version', default: '3.8' },
      networks: { type: 'array', label: 'Networks', description: 'Docker networks' },
      volumes: { type: 'array', label: 'Named Volumes', description: 'Persistent volume definitions' },
      secrets: { type: 'array', label: 'Secrets', description: 'Secret management configuration' },
    },
  },
  {
    id: 'docker-swarm',
    label: 'Docker Swarm',
    description: 'Docker Swarm cluster. Native Docker clustering for container orchestration with built-in load balancing.',
    icon: 'layers',
    layer: 'orchestration',
    containerStyle: 'hosting',
    canContain: [
      'docker-container', 'backend-service',
      'worker', 'database', 'cache', 'inference-service', 'vector-database'],
    defaultMetadata: {
      managerCount: 3,
      workerCount: 5,
      ingressNetwork: 'ingress',
      overlayNetworks: ['app-network'],
      autolock: true,
    },
    metadataSchema: {
      managerCount: { type: 'number', label: 'Manager Nodes', description: 'Number of manager nodes (odd for quorum)', default: 3 },
      workerCount: { type: 'number', label: 'Worker Nodes', description: 'Number of worker nodes', default: 5 },
      overlayNetworks: { type: 'array', label: 'Overlay Networks', description: 'Custom overlay networks', default: ['app-network'] },
      autolock: { type: 'boolean', label: 'Auto-lock', description: 'Require unlock key on manager restart', default: true },
    },
  },
  {
    id: 'ecs-cluster',
    label: 'ECS Cluster',
    description: 'AWS Elastic Container Service cluster for running containerized applications.',
    icon: 'box',
    layer: 'orchestration',
    containerStyle: 'hosting',
    canContain: [
      'backend-service', 'worker', 'database', 'cache',
      'monitoring', 'logging',
      'inference-service', 'vector-database'],
    defaultMetadata: {
      launchType: 'FARGATE',
      taskCount: 2,
    },
    metadataSchema: {
      launchType: { type: 'string', label: 'Launch Type', description: 'FARGATE or EC2', default: 'FARGATE' },
      taskCount: { type: 'number', label: 'Task Count', description: 'Number of running tasks', default: 2 },
    },
  },
  {
    id: 'docker-container',
    label: 'Docker Container',
    description: 'Isolated runtime environment for a single application. Runs inside Docker Compose or Docker Engine.',
    icon: 'box',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: ['backend-service', 'frontend-app', 'worker', 'database', 'cache', 'inference-service', 'vector-database'],
    defaultMetadata: {
      baseImage: 'node:20-alpine',
      ports: [3000],
      environmentVariables: {},
      volumes: [],
      command: 'npm start',
      restartPolicy: 'unless-stopped',
      cpuLimit: '1.0',
      memoryLimit: '512m',
    },
    metadataSchema: {
      baseImage: { type: 'string', label: 'Base Image', description: 'Docker image (e.g., node:20-alpine)', required: true },
      ports: { type: 'array', label: 'Exposed Ports', description: 'Container ports to expose' },
      environmentVariables: { type: 'object', label: 'Environment Variables', description: 'Key-value configuration pairs' },
      volumes: { type: 'array', label: 'Volume Mounts', description: 'Persistent storage paths' },
      restartPolicy: { type: 'string', label: 'Restart Policy', description: 'always, unless-stopped, on-failure', default: 'unless-stopped' },
      cpuLimit: { type: 'string', label: 'CPU Limit', description: 'Max CPU (e.g., 1.5 cores)' },
      memoryLimit: { type: 'string', label: 'Memory Limit', description: 'Max memory (e.g., 512m, 2g)' },
    },
  },
  // N11(c) 2026-08-09: the `serverless-function` and `desktop-app` entries are GONE —
  // the DB reclassified both as LEAF roles (20260512025200; M3 guards desktop-app with an
  // exception), so the static shadow claiming container-ness was an active pre-hydration
  // lie: those nodes rendered as containers and admitted children until the catalog
  // arrived. Both ids remain valid LEAF roles and still appear in other containers'
  // canContain lists — only their container DEFINITIONS were the drift.
  {
    id: 'mobile-device',
    label: 'Mobile Device',
    description: 'Physical mobile device (iOS or Android) that hosts native apps, local databases, background workers, and on-device services.',
    icon: 'smartphone',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: ['mobile-app', 'frontend-app', 'database', 'cache', 'backend-service', 'worker', 'inference-service'],
    defaultMetadata: {
      platform: 'ios',
      osMinVersion: '16.0',
      deviceCategory: 'phone',
      offlineCapable: true,
      pushNotifications: true,
      biometricAuth: false,
    },
    metadataSchema: {
      platform: { type: 'string', label: 'Platform', description: 'ios, android, or cross-platform', default: 'ios' },
      osMinVersion: { type: 'string', label: 'Minimum OS Version', description: 'Minimum supported OS version (e.g., 16.0 for iOS, 13 for Android)', default: '16.0' },
      deviceCategory: { type: 'string', label: 'Device Category', description: 'phone, tablet, watch, or tv', default: 'phone' },
      offlineCapable: { type: 'boolean', label: 'Offline Capable', description: 'App works without network connectivity', default: true },
      pushNotifications: { type: 'boolean', label: 'Push Notifications', description: 'Enable push notification support (APNs/FCM)', default: true },
      biometricAuth: { type: 'boolean', label: 'Biometric Auth', description: 'Use Face ID / Touch ID / Fingerprint', default: false },
    },
  },
  {
    id: 'microservice-boundary',
    label: 'Microservice Boundary',
    description: 'Service-oriented architecture boundary. Groups related services with shared data models and business logic.',
    icon: 'box',
    layer: 'logical',
    containerStyle: 'logical-boundary',
    canContain: [
      'backend-service', 'realtime-service', 'scheduled-trigger',
      'worker', 'database', 'graph-db', 'time-series-db', 'search-engine',
      'cache', 'auth-provider', 'message-broker', 'event-stream', 'monitoring', 'logging'],
    defaultMetadata: {
      domain: '',
      apiContract: '',
      communicationProtocol: 'rest',
      authenticationMethod: 'jwt',
      sharedLibraries: [],
      eventBus: '',
    },
    metadataSchema: {
      domain: { type: 'string', label: 'Business Domain', description: 'Domain this service belongs to', required: true },
      communicationProtocol: { type: 'string', label: 'Communication Protocol', description: 'rest, graphql, grpc, message-queue', default: 'rest' },
      authenticationMethod: { type: 'string', label: 'Authentication Method', description: 'jwt, oauth2, api-key, mtls', default: 'jwt' },
      apiGateway: { type: 'string', label: 'API Gateway', description: 'Kong, Ambassador, AWS API Gateway, etc.' },
      serviceRegistry: { type: 'string', label: 'Service Registry', description: 'Consul, Eureka, etcd, etc.' },
    },
  },
  {
    id: 'bounded-context',
    label: 'Bounded Context (DDD)',
    description: 'Domain-Driven Design boundary. Encapsulates a specific domain model with explicit interfaces.',
    icon: 'hexagon',
    layer: 'logical',
    containerStyle: 'logical-boundary',
    canContain: [
      'microservice-boundary', 'backend-service',
      'worker', 'database', 'graph-db', 'cache', 'message-broker', 'event-stream'],
    defaultMetadata: {
      domain: '',
      ubiquitousLanguage: {},
      aggregates: [],
      domainEvents: [],
    },
    metadataSchema: {
      domain: { type: 'string', label: 'Domain Name', description: 'Business domain (e.g., Order Management)', required: true },
      aggregates: { type: 'array', label: 'Aggregate Roots', description: 'Key domain entities' },
      domainEvents: { type: 'array', label: 'Domain Events', description: 'Events published by this context' },
      anticorruptionLayer: { type: 'boolean', label: 'Anti-Corruption Layer', description: 'Protect domain model from external changes', default: false },
    },
  },
  // N10(c) 2026-08-09: the `service-mesh` entry is GONE — re-filed as a Networking
  // LEAF (migration 20260810100000): a mesh is installed INTO a cluster, it does not
  // host services and it is not one of the five ruled Structure roles. Its curated
  // metadata_schema moved to the catalog row, where curated content belongs.
  {
    id: 'application-module',
    label: 'Application Module',
    description: 'Self-contained business module within an application. Encapsulates related functionality.',
    icon: 'package',
    layer: 'logical',
    containerStyle: 'logical-boundary',
    canContain: [
      'software-layer', 'realtime-service', 'scheduled-trigger', 'backend-service', 'worker', 'database', 'graph-db',
      'time-series-db', 'cache', 'auth-provider', 'frontend-app', 'message-broker', 'event-stream', 'monitoring', 'logging'],
    defaultMetadata: {
      moduleName: '',
      moduleType: 'feature',
      visibility: 'internal',
      dependencies: [],
      exports: [],
      entryPoints: [],
      testCoverage: 0,
    },
    metadataSchema: {
      moduleName: { type: 'string', label: 'Module Name', description: 'Unique module identifier', required: true },
      moduleType: { type: 'string', label: 'Module Type', description: 'feature, core, or plugin', default: 'feature' },
      visibility: { type: 'string', label: 'Visibility', description: 'internal or public', default: 'internal' },
      dependencies: { type: 'array', label: 'Module Dependencies', description: 'Other modules this depends on' },
      testCoverage: { type: 'number', label: 'Test Coverage (%)', description: 'Code coverage percentage', default: 0 },
    },
  },
  {
    id: 'software-layer',
    label: 'Software Layer',
    description: 'Architectural layer following clean architecture or n-tier patterns.',
    icon: 'layers',
    layer: 'logical',
    containerStyle: 'logical-boundary',
    canContain: [
      'backend-service',
      'worker', 'database', 'cache', 'frontend-app'],
    defaultMetadata: {
      layerType: 'business',
      allowedDependencies: [],
      prohibitedDependencies: [],
      responsibilities: [],
    },
    metadataSchema: {
      layerType: { type: 'string', label: 'Layer Type', description: 'presentation, business, data, infrastructure, or domain', default: 'business' },
      allowedDependencies: { type: 'array', label: 'Allowed Dependencies', description: 'Layers this layer can depend on' },
      prohibitedDependencies: { type: 'array', label: 'Prohibited Dependencies', description: 'Layers this layer must NOT depend on' },
      responsibilities: { type: 'array', label: 'Responsibilities', description: 'What this layer is responsible for' },
    },
  },
];
