import type { InterfaceEnrichment } from './interface-enrichment.js';

/**
 * Extended Interface Enrichments
 * - API Gateways (AWS, Azure, GCP, Kong)
 * - WebSocket Server
 * - Service Meshes (Istio, Linkerd, Consul)
 */

// AWS API Gateway Enrichment
const AWS_API_GATEWAY_ENRICHMENT: InterfaceEnrichment = {
  interfaceId: 'gateway.aws-api-gateway',
  displayName: 'AWS API Gateway',
  category: 'gateway',
  fileTypes: [
    {
      extension: '.yaml',
      description: 'OpenAPI/Swagger specification',
      purpose: 'schema',
      example: 'api-definition.yaml',
    },
    {
      extension: '.json',
      description: 'API Gateway model schemas',
      purpose: 'schema',
      example: 'models/user.json',
    },
    {
      extension: '.yaml',
      description: 'CloudFormation/SAM template',
      purpose: 'config',
      example: 'template.yaml, cloudformation.yaml',
    },
    {
      extension: '.tf',
      description: 'Terraform configuration',
      purpose: 'config',
      example: 'api-gateway.tf',
    },
    {
      extension: '.vtl',
      description: 'Velocity Template Language for mapping',
      purpose: 'middleware',
      example: 'request-mapping.vtl, response-mapping.vtl',
    },
  ],
  clientLibraries: [
    {
      language: 'typescript',
      name: 'AWS SDK',
      package: '@aws-sdk/client-api-gateway',
      description: 'AWS SDK for API Gateway management',
      popularity: 'primary',
      features: ['Full API access', 'TypeScript support', 'v3 modular'],
    },
    {
      language: 'typescript',
      name: 'AWS Amplify',
      package: '@aws-amplify/api',
      description: 'Simplified API client with auth',
      popularity: 'popular',
      features: ['Auth integration', 'Caching', 'Simple API'],
    },
    {
      language: 'python',
      name: 'boto3',
      package: 'boto3',
      description: 'AWS SDK for Python',
      popularity: 'primary',
      features: ['Full AWS support', 'High-level and low-level APIs'],
    },
    {
      language: 'java',
      name: 'AWS SDK for Java',
      package: 'software.amazon.awssdk:apigateway',
      description: 'Official Java SDK',
      popularity: 'primary',
      features: ['Type-safe', 'Async support', 'DynamoDB enhanced client'],
    },
    {
      language: 'go',
      name: 'AWS SDK for Go',
      package: 'github.com/aws/aws-sdk-go-v2',
      description: 'Official Go SDK v2',
      popularity: 'primary',
      features: ['Modular', 'Context support', 'Retries'],
    },
  ],
  authStrategies: [
    {
      name: 'AWS IAM',
      description: 'IAM-based authentication',
      complexity: 'moderate',
      useCases: ['Service-to-service', 'AWS services', 'Internal APIs'],
      implementation: 'SigV4 signing with AWS credentials',
    },
    {
      name: 'Cognito User Pools',
      description: 'User authentication with Cognito',
      complexity: 'moderate',
      useCases: ['User applications', 'Mobile apps', 'Web apps'],
      implementation: 'JWT tokens from Cognito',
    },
    {
      name: 'Lambda Authorizers',
      description: 'Custom authorization logic',
      complexity: 'complex',
      useCases: ['Third-party auth', 'Custom logic', 'External IdPs'],
      implementation: 'Lambda function validates tokens',
    },
    {
      name: 'API Keys',
      description: 'Simple API key authentication',
      complexity: 'simple',
      useCases: ['Usage plans', 'Rate limiting', 'Public APIs'],
      implementation: 'x-api-key header',
    },
  ],
  configPatterns: [
    {
      name: 'Usage Plans',
      description: 'Throttling and quota configuration',
      example: '{ "throttle": { "rateLimit": 1000, "burstLimit": 2000 }, "quota": { "limit": 100000, "period": "MONTH" } }',
      purpose: 'Control API usage per customer',
    },
    {
      name: 'Request Validation',
      description: 'Validate requests against models',
      example: '{ "validateRequestBody": true, "validateRequestParameters": true }',
      purpose: 'Ensure request format compliance',
    },
    {
      name: 'Response Caching',
      description: 'Cache GET responses',
      example: '{ "cachingEnabled": true, "ttlInSeconds": 300 }',
      purpose: 'Reduce backend load',
    },
    {
      name: 'CORS Configuration',
      description: 'Cross-origin settings',
      example: '{ "allowOrigins": ["https://example.com"], "allowMethods": ["GET", "POST"], "allowHeaders": ["Content-Type", "Authorization"] }',
      purpose: 'Enable browser access',
    },
  ],
  deploymentOptions: [
    {
      provider: 'AWS',
      service: 'API Gateway REST API',
      description: 'Traditional REST API with rich features',
      advantages: ['Full feature set', 'Request/response transformation', 'Caching', 'Usage plans'],
      considerations: ['Higher cost', 'More complex'],
    },
    {
      provider: 'AWS',
      service: 'API Gateway HTTP API',
      description: 'Cost-effective, fast HTTP APIs',
      advantages: ['70% cheaper', 'Lower latency', 'OIDC/JWT support'],
      considerations: ['Fewer features', 'No caching', 'No usage plans'],
    },
    {
      provider: 'AWS',
      service: 'API Gateway WebSocket',
      description: 'WebSocket API support',
      advantages: ['Managed WebSocket', 'Bidirectional', 'Connection management'],
      considerations: ['Connection limits', 'Custom routing required'],
    },
  ],
  securityFeatures: [
    {
      name: 'AWS WAF Integration',
      description: 'Web application firewall',
      importance: 'critical',
      implementation: 'Attach WAF WebACL to API Gateway',
    },
    {
      name: 'Resource Policies',
      description: 'IP whitelisting and VPC access',
      importance: 'critical',
      implementation: 'Resource policy on API Gateway',
    },
    {
      name: 'Throttling',
      description: 'Rate limiting per account/API key',
      importance: 'critical',
      implementation: 'Usage plans with throttle settings',
    },
    {
      name: 'Request Validation',
      description: 'Schema-based validation',
      importance: 'recommended',
      implementation: 'Enable request validators',
    },
    {
      name: 'CloudWatch Logging',
      description: 'Full request/response logging',
      importance: 'recommended',
      implementation: 'Enable execution and access logs',
    },
  ],
  monitoringTools: [
    'AWS CloudWatch',
    'AWS X-Ray',
    'CloudWatch Logs Insights',
    'CloudWatch Metrics',
    'AWS CloudTrail',
    'Third-party APM (Datadog, New Relic)',
  ],
  testingTools: [
    'AWS Console Test feature',
    'Postman',
    'Insomnia',
    'AWS CLI',
    'curl',
    'Serverless Framework',
  ],
  performanceTips: [
    'Enable response caching for GET requests',
    'Use HTTP APIs for lower latency (vs REST)',
    'Minimize mapping template complexity',
    'Use VPC Link for private integrations',
    'Enable payload compression',
    'Optimize Lambda functions behind gateway',
    'Use regional endpoints for lower latency',
    'Monitor CloudWatch metrics for bottlenecks',
  ],
};

// WebSocket Server Enrichment
const WEBSOCKET_SERVER_ENRICHMENT: InterfaceEnrichment = {
  interfaceId: 'web.websocket-server',
  displayName: 'WebSocket Server',
  category: 'realtime',
  fileTypes: [
    {
      extension: '.ts/.js',
      description: 'WebSocket server initialization',
      purpose: 'config',
      example: 'server.ts, websocket.ts',
    },
    {
      extension: '.ts/.js',
      description: 'Event handlers and message processors',
      purpose: 'handler',
      example: 'handlers/chat.ts, handlers/game.ts',
    },
    {
      extension: '.ts/.js',
      description: 'Room/channel management',
      purpose: 'middleware',
      example: 'rooms.ts, channels.ts',
    },
    {
      extension: '.ts/.js',
      description: 'Authentication middleware',
      purpose: 'middleware',
      example: 'auth-middleware.ts',
    },
    {
      extension: '.proto',
      description: 'Message schema definitions',
      purpose: 'schema',
      example: 'messages.proto',
    },
  ],
  clientLibraries: [
    {
      language: 'typescript',
      name: 'Socket.IO Client',
      package: 'socket.io-client',
      description: 'Feature-rich WebSocket client with fallbacks',
      popularity: 'primary',
      features: ['Auto-reconnection', 'Binary support', 'Rooms', 'Namespaces'],
    },
    {
      language: 'typescript',
      name: 'WebSocket API',
      package: 'native',
      description: 'Native browser WebSocket',
      popularity: 'popular',
      features: ['Standard', 'Lightweight', 'No dependencies'],
    },
    {
      language: 'typescript',
      name: 'ws',
      package: 'ws',
      description: 'Simple WebSocket library for Node.js',
      popularity: 'popular',
      features: ['Fast', 'Spec-compliant', 'Binary support'],
    },
    {
      language: 'python',
      name: 'websockets',
      package: 'websockets',
      description: 'Async WebSocket library',
      popularity: 'primary',
      features: ['Async/await', 'Clean API', 'Client and server'],
    },
    {
      language: 'python',
      name: 'python-socketio',
      package: 'python-socketio',
      description: 'Socket.IO for Python',
      popularity: 'popular',
      features: ['Socket.IO protocol', 'Client and server', 'Async support'],
    },
    {
      language: 'java',
      name: 'Java-WebSocket',
      package: 'org.java-websocket:Java-WebSocket',
      description: 'Java WebSocket implementation',
      popularity: 'primary',
      features: ['RFC 6455 compliant', 'Client and server', 'TLS support'],
    },
    {
      language: 'go',
      name: 'gorilla/websocket',
      package: 'github.com/gorilla/websocket',
      description: 'Fast WebSocket implementation for Go',
      popularity: 'primary',
      features: ['Fast', 'RFC 6455', 'Compression'],
    },
    {
      language: 'csharp',
      name: 'SignalR',
      package: 'Microsoft.AspNetCore.SignalR',
      description: 'Real-time communication library',
      popularity: 'primary',
      features: ['Multiple transports', 'Hubs', 'Scaling'],
    },
    {
      language: 'rust',
      name: 'tokio-tungstenite',
      package: 'tokio-tungstenite',
      description: 'Async WebSocket library',
      popularity: 'primary',
      features: ['Async', 'Fast', 'TLS support'],
    },
  ],
  authStrategies: [
    {
      name: 'Handshake Authentication',
      description: 'Validate on initial connection',
      complexity: 'simple',
      useCases: ['Token-based auth', 'Session validation', 'API keys'],
      implementation: 'Validate query params or headers during handshake',
    },
    {
      name: 'Message-Based Auth',
      description: 'Send auth message after connection',
      complexity: 'moderate',
      useCases: ['Delayed auth', 'Multi-step auth', 'Re-authentication'],
      implementation: 'First message must be auth, disconnect if invalid',
    },
    {
      name: 'JWT Tokens',
      description: 'JSON Web Tokens in handshake',
      complexity: 'simple',
      useCases: ['Stateless auth', 'Microservices', 'SPAs'],
      implementation: 'Pass JWT in query string or headers, validate on connect',
    },
  ],
  configPatterns: [
    {
      name: 'Heartbeat/Ping-Pong',
      description: 'Keep connection alive',
      example: '{ "pingInterval": 25000, "pingTimeout": 20000 }',
      purpose: 'Detect dead connections',
    },
    {
      name: 'Max Connections',
      description: 'Limit concurrent connections',
      example: '{ "maxConnections": 10000 }',
      purpose: 'Prevent resource exhaustion',
    },
    {
      name: 'Message Size Limits',
      description: 'Maximum message payload',
      example: '{ "maxPayload": 1048576 }',
      purpose: 'Prevent memory issues',
    },
    {
      name: 'Compression',
      description: 'Per-message compression',
      example: '{ "perMessageDeflate": true }',
      purpose: 'Reduce bandwidth',
    },
  ],
  deploymentOptions: [
    {
      provider: 'AWS',
      service: 'API Gateway WebSocket',
      description: 'Managed WebSocket API',
      advantages: ['Serverless', 'Auto-scaling', 'Connection management'],
      considerations: ['Connection table required', 'Lambda integration complexity'],
    },
    {
      provider: 'Pusher',
      service: 'Pusher Channels',
      description: 'Hosted WebSocket service',
      advantages: ['Fully managed', 'Presence channels', 'Easy integration'],
      considerations: ['Cost', 'Vendor lock-in'],
    },
    {
      provider: 'Ably',
      service: 'Ably Realtime',
      description: 'Real-time messaging platform',
      advantages: ['Global edge network', 'Guaranteed delivery', 'History'],
      considerations: ['Pricing', 'Learning curve'],
    },
    {
      provider: 'Self-hosted',
      service: 'Socket.IO + Redis',
      description: 'Horizontal scaling with Redis adapter',
      advantages: ['Full control', 'Cost-effective at scale', 'Custom logic'],
      considerations: ['Operations overhead', 'Redis cluster management'],
    },
  ],
  securityFeatures: [
    {
      name: 'Connection Authentication',
      description: 'Validate on handshake',
      importance: 'critical',
      implementation: 'Middleware during connection upgrade',
    },
    {
      name: 'Rate Limiting',
      description: 'Message rate limits per connection',
      importance: 'critical',
      implementation: 'Token bucket or sliding window',
    },
    {
      name: 'TLS/WSS',
      description: 'Encrypted WebSocket connections',
      importance: 'critical',
      implementation: 'Use wss:// protocol with SSL certificates',
    },
    {
      name: 'Message Validation',
      description: 'Validate message format and content',
      importance: 'critical',
      implementation: 'JSON schema or protobuf validation',
    },
    {
      name: 'Connection Limits',
      description: 'Per-user connection limits',
      importance: 'recommended',
      implementation: 'Track connections by user ID',
    },
  ],
  monitoringTools: [
    'Socket.IO Admin UI',
    'Prometheus + Grafana',
    'Datadog',
    'New Relic',
    'CloudWatch (for AWS)',
    'Custom connection metrics',
    'Redis monitoring (for scaling)',
  ],
  testingTools: [
    'wscat',
    'Postman WebSocket',
    'websocat',
    'Socket.IO client',
    'Artillery (load testing)',
    'k6 (WebSocket support)',
  ],
  performanceTips: [
    'Implement heartbeat to detect dead connections',
    'Use binary frames for large payloads',
    'Implement connection pooling for backends',
    'Use Redis adapter for horizontal scaling',
    'Batch messages when possible',
    'Implement backpressure handling',
    'Monitor memory usage per connection',
    'Clean up resources on disconnection',
  ],
};

// Istio Service Mesh Enrichment
const ISTIO_MESH_ENRICHMENT: InterfaceEnrichment = {
  interfaceId: 'mesh.istio',
  displayName: 'Istio Service Mesh',
  category: 'mesh',
  fileTypes: [
    {
      extension: '.yaml',
      description: 'Istio VirtualService configuration',
      purpose: 'config',
      example: 'virtualservice.yaml',
    },
    {
      extension: '.yaml',
      description: 'Istio DestinationRule configuration',
      purpose: 'config',
      example: 'destinationrule.yaml',
    },
    {
      extension: '.yaml',
      description: 'Istio Gateway configuration',
      purpose: 'config',
      example: 'gateway.yaml',
    },
    {
      extension: '.yaml',
      description: 'Istio ServiceEntry for external services',
      purpose: 'config',
      example: 'serviceentry.yaml',
    },
    {
      extension: '.yaml',
      description: 'Istio AuthorizationPolicy',
      purpose: 'config',
      example: 'authz-policy.yaml',
    },
  ],
  clientLibraries: [],
  authStrategies: [
    {
      name: 'mTLS (Mutual TLS)',
      description: 'Automatic service-to-service encryption',
      complexity: 'simple',
      useCases: ['All service mesh deployments', 'Zero-trust security'],
      implementation: 'PeerAuthentication resource with STRICT mode',
    },
    {
      name: 'JWT Authentication',
      description: 'Validate JWT tokens at ingress',
      complexity: 'moderate',
      useCases: ['User authentication', 'External clients', 'API access'],
      implementation: 'RequestAuthentication and AuthorizationPolicy',
    },
    {
      name: 'Authorization Policies',
      description: 'Fine-grained access control',
      complexity: 'moderate',
      useCases: ['Service-to-service authz', 'RBAC', 'Namespace isolation'],
      implementation: 'AuthorizationPolicy resources',
    },
  ],
  configPatterns: [
    {
      name: 'Traffic Splitting',
      description: 'Canary deployments and A/B testing',
      example: 'VirtualService with weighted routing: v1: 90%, v2: 10%',
      purpose: 'Gradual rollouts and testing',
    },
    {
      name: 'Circuit Breaking',
      description: 'Prevent cascade failures',
      example: 'DestinationRule with outlierDetection',
      purpose: 'Improve resilience',
    },
    {
      name: 'Retry Policy',
      description: 'Automatic retry on failures',
      example: 'VirtualService with retries: attempts: 3, perTryTimeout: 2s',
      purpose: 'Handle transient failures',
    },
    {
      name: 'Timeout Configuration',
      description: 'Request timeout settings',
      example: 'VirtualService with timeout: 30s',
      purpose: 'Prevent hanging requests',
    },
  ],
  deploymentOptions: [
    {
      provider: 'Self-managed',
      service: 'Istio on Kubernetes',
      description: 'Full-featured self-managed',
      advantages: ['Complete control', 'All features', 'Open source'],
      considerations: ['Operations overhead', 'Version management', 'Resource usage'],
    },
    {
      provider: 'Google Cloud',
      service: 'GKE with Istio',
      description: 'Managed Istio on GKE',
      advantages: ['Managed control plane', 'Google support', 'Integration with GCP'],
      considerations: ['GCP specific', 'Cost'],
    },
    {
      provider: 'AWS',
      service: 'EKS with Istio',
      description: 'Self-managed Istio on EKS',
      advantages: ['AWS integration', 'Full control'],
      considerations: ['Self-managed', 'Complexity'],
    },
  ],
  securityFeatures: [
    {
      name: 'Automatic mTLS',
      description: 'Zero-config service encryption',
      importance: 'critical',
      implementation: 'PeerAuthentication with STRICT mode',
    },
    {
      name: 'Authorization Policies',
      description: 'Service-level access control',
      importance: 'critical',
      implementation: 'AuthorizationPolicy resources',
    },
    {
      name: 'JWT Validation',
      description: 'Validate external tokens',
      importance: 'recommended',
      implementation: 'RequestAuthentication resources',
    },
    {
      name: 'Certificate Management',
      description: 'Automatic cert rotation',
      importance: 'critical',
      implementation: 'Istio CA or external CA integration',
    },
  ],
  monitoringTools: [
    'Kiali (service mesh observability)',
    'Prometheus + Grafana',
    'Jaeger (distributed tracing)',
    'Zipkin',
    'Istio Dashboard',
    'Envoy Access Logs',
  ],
  testingTools: [
    'Istioctl analyze',
    'Istioctl proxy-config',
    'Fortio (load testing)',
    'Kiali Graph',
  ],
  performanceTips: [
    'Set resource limits on sidecar proxies',
    'Use concurrency limits in DestinationRules',
    'Monitor proxy CPU and memory usage',
    'Optimize mTLS cipher suites',
    'Use locality load balancing',
    'Enable telemetry sampling',
    'Monitor control plane health',
    'Use protocol detection hints',
  ],
};

// Kong Gateway Enrichment
const KONG_GATEWAY_ENRICHMENT: InterfaceEnrichment = {
  interfaceId: 'gateway.kong',
  displayName: 'Kong Gateway',
  category: 'gateway',
  fileTypes: [
    {
      extension: '.yaml',
      description: 'Kong declarative configuration',
      purpose: 'config',
      example: 'kong.yaml, deck.yaml',
    },
    {
      extension: '.lua',
      description: 'Custom Kong plugins',
      purpose: 'middleware',
      example: 'plugins/custom-auth.lua',
    },
    {
      extension: '.yaml',
      description: 'Kubernetes Ingress with Kong annotations',
      purpose: 'config',
      example: 'ingress.yaml',
    },
  ],
  clientLibraries: [
    {
      language: 'typescript',
      name: 'Kong Admin API Client',
      package: 'kong-admin-api',
      description: 'Node.js client for Kong Admin API',
      popularity: 'popular',
    },
    {
      language: 'python',
      name: 'kong-admin-client',
      package: 'kong-admin-client',
      description: 'Python client for Kong Admin API',
      popularity: 'popular',
    },
    {
      language: 'go',
      name: 'deck',
      package: 'github.com/kong/deck',
      description: 'Declarative configuration tool',
      popularity: 'primary',
      features: ['Declarative config', 'State sync', 'Backup/restore'],
    },
  ],
  authStrategies: [
    {
      name: 'Key Authentication',
      description: 'API key-based authentication',
      complexity: 'simple',
      useCases: ['API access', 'Simple auth', 'Internal services'],
      implementation: 'key-auth plugin',
    },
    {
      name: 'JWT',
      description: 'JWT token validation',
      complexity: 'moderate',
      useCases: ['SPAs', 'Mobile apps', 'Stateless auth'],
      implementation: 'jwt plugin',
    },
    {
      name: 'OAuth 2.0',
      description: 'Full OAuth flow support',
      complexity: 'complex',
      useCases: ['Third-party integrations', 'Delegated access'],
      implementation: 'oauth2 plugin',
    },
    {
      name: 'LDAP',
      description: 'LDAP authentication',
      complexity: 'moderate',
      useCases: ['Enterprise', 'Active Directory integration'],
      implementation: 'ldap-auth plugin',
    },
  ],
  configPatterns: [
    {
      name: 'Rate Limiting',
      description: 'Token bucket rate limiting',
      example: 'rate-limiting plugin: minute: 100, hour: 1000',
      purpose: 'Prevent API abuse',
    },
    {
      name: 'Request Transformation',
      description: 'Modify request/response',
      example: 'request-transformer plugin',
      purpose: 'Normalize API formats',
    },
    {
      name: 'Caching',
      description: 'Response caching',
      example: 'proxy-cache plugin: strategy: memory, ttl: 300',
      purpose: 'Reduce backend load',
    },
    {
      name: 'CORS',
      description: 'Cross-origin configuration',
      example: 'cors plugin with allowed origins and methods',
      purpose: 'Enable browser clients',
    },
  ],
  deploymentOptions: [
    {
      provider: 'Kong',
      service: 'Kong Cloud (Konnect)',
      description: 'Fully managed Kong',
      advantages: ['Managed', 'Multi-cloud', 'Analytics'],
      considerations: ['Cost', 'Vendor lock-in'],
    },
    {
      provider: 'Self-hosted',
      service: 'Kong on Kubernetes',
      description: 'Kong Ingress Controller',
      advantages: ['Native K8s integration', 'Free tier', 'Control'],
      considerations: ['Operations', 'Database management'],
    },
    {
      provider: 'Docker',
      service: 'Kong in Docker',
      description: 'Containerized deployment',
      advantages: ['Portable', 'Easy dev setup'],
      considerations: ['Scaling', 'High availability'],
    },
  ],
  securityFeatures: [
    {
      name: 'Authentication Plugins',
      description: 'Multiple auth strategies',
      importance: 'critical',
      implementation: 'key-auth, jwt, oauth2, ldap-auth plugins',
    },
    {
      name: 'Rate Limiting',
      description: 'Prevent DDoS and abuse',
      importance: 'critical',
      implementation: 'rate-limiting or rate-limiting-advanced plugins',
    },
    {
      name: 'IP Restriction',
      description: 'Whitelist/blacklist IPs',
      importance: 'recommended',
      implementation: 'ip-restriction plugin',
    },
    {
      name: 'Bot Detection',
      description: 'Detect and block bots',
      importance: 'recommended',
      implementation: 'bot-detection plugin (Enterprise)',
    },
    {
      name: 'Request Validation',
      description: 'Validate requests against schemas',
      importance: 'recommended',
      implementation: 'request-validator plugin',
    },
  ],
  monitoringTools: [
    'Kong Manager',
    'Prometheus + Grafana',
    'StatsD',
    'Datadog',
    'New Relic',
    'Kong Vitals (Enterprise)',
    'Zipkin/Jaeger (tracing)',
  ],
  testingTools: [
    'HTTPie',
    'curl',
    'Postman',
    'Kong Admin API',
    'deck validate',
    'Insomnia',
  ],
  performanceTips: [
    'Use database caching (db-less mode for read-heavy)',
    'Enable DNS caching',
    'Use upstream healthchecks',
    'Implement connection pooling',
    'Monitor Nginx worker processes',
    'Use load balancing algorithms effectively',
    'Minimize plugin chain length',
    'Cache responses with proxy-cache plugin',
  ],
};

export const EXTENDED_INTERFACE_ENRICHMENTS: Record<string, InterfaceEnrichment> = {
  'gateway.aws-api-gateway': AWS_API_GATEWAY_ENRICHMENT,
  'web.websocket-server': WEBSOCKET_SERVER_ENRICHMENT,
  'mesh.istio': ISTIO_MESH_ENRICHMENT,
  'gateway.kong': KONG_GATEWAY_ENRICHMENT,
};
