#!/usr/bin/env bash
# NodeSpec self-host bootstrap (SHIP-1(e)) — idempotent; run from anywhere.
#
# What it does, in order:
#   1. sanity-checks the tools (docker, supabase CLI, node),
#   2. composes supabase/functions/.env from deploy/selfhost/selfhost.env
#      (NODESPEC_DEPLOYMENT, license, encryption secret — the functions read
#      env from that file on this stack),
#   3. starts the Supabase stack; on FIRST run applies the schema,
#   4. fills VITE_SUPABASE_ANON_KEY from the running stack when left empty,
#   5. builds + starts the frontend container (port ${FRONTEND_PORT:-8080}).
#
# Re-running is safe: an already-running stack is left alone (config changes
# need `supabase stop && supabase start`), and the frontend is rebuilt only
# when compose detects changes. It NEVER runs `supabase db reset` on an
# existing database — that would drop customer data.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
ENV_FILE="$HERE/selfhost.env"

say()  { printf '\n[nodespec] %s\n' "$*"; }
fail() { printf '\n[nodespec] ERROR: %s\n' "$*" >&2; exit 1; }

# 1 · tools
command -v docker >/dev/null   || fail "docker not found — install Docker Engine and re-run"
docker info >/dev/null 2>&1    || fail "docker daemon not reachable — is Docker running?"
command -v supabase >/dev/null || fail "supabase CLI not found — see deploy/selfhost/README.md prerequisites"
[ -f "$ENV_FILE" ] || fail "missing $ENV_FILE — cp selfhost.env.example selfhost.env and edit it (see README.md)"

# shellcheck disable=SC1090
set -a; . "$ENV_FILE"; set +a
[ -n "${ENCRYPTION_SECRET:-}" ] || fail "ENCRYPTION_SECRET is empty in selfhost.env — set it once and back it up"
[ "${NODESPEC_DEPLOYMENT:-}" = "self-hosted" ] || fail "NODESPEC_DEPLOYMENT must be 'self-hosted' in selfhost.env"
if [ -z "${NODESPEC_LICENSE:-}" ]; then
  say "NOTE: NODESPEC_LICENSE is empty — the deployment runs at community tier (fail-closed, never fatal)."
fi

# 2 · functions env (composed, not hand-edited — selfhost.env is the source)
FUNC_ENV="$ROOT/supabase/functions/.env"
say "writing $FUNC_ENV from selfhost.env"
{
  echo "# Generated by deploy/selfhost/bootstrap.sh from selfhost.env — edit THAT file."
  echo "NODESPEC_DEPLOYMENT=${NODESPEC_DEPLOYMENT}"
  echo "ENCRYPTION_SECRET=${ENCRYPTION_SECRET}"
  echo "NODESPEC_LICENSE=${NODESPEC_LICENSE:-}"
  [ -n "${NODESPEC_LICENSE_PUBLIC_KEY:-}" ] && echo "NODESPEC_LICENSE_PUBLIC_KEY=${NODESPEC_LICENSE_PUBLIC_KEY}"
  # The MCP server advertises its own URL (OAuth discovery, WWW-Authenticate);
  # without this it falls back to the stack-internal http://kong:8000 and no
  # external MCP client can complete the handshake (live-caught 2026-08-25).
  [ -n "${VITE_MCP_PUBLIC_URL:-}" ] && echo "MCP_PUBLIC_URL=${VITE_MCP_PUBLIC_URL}"
  # Single-user local trust for the MCP authorize step (see selfhost.env.example).
  [ -n "${MCP_LOCAL_TRUST:-}" ] && echo "MCP_LOCAL_TRUST=${MCP_LOCAL_TRUST}"
  # The OAuth consent page runs in the user's browser: it needs the public
  # auth origin (single-origin gateway) and a Turnstile key valid for THIS
  # domain — the runtime-internal SUPABASE_URL and the hosted default key
  # both fail off nodespec.io (live-caught 2026-08-25).
  [ -n "${VITE_SUPABASE_URL:-}" ] && echo "PUBLIC_SUPABASE_URL=${VITE_SUPABASE_URL}"
  [ -n "${VITE_TURNSTILE_SITE_KEY:-}" ] && echo "TURNSTILE_SITE_KEY=${VITE_TURNSTILE_SITE_KEY}"
  echo "STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_dummy_never_called_selfhost}"
  [ -n "${OPENAI_API_KEY:-}" ] && echo "OPENAI_API_KEY=${OPENAI_API_KEY}"
} > "$FUNC_ENV"

# 3 · the Supabase stack
cd "$ROOT"
if supabase status >/dev/null 2>&1; then
  say "supabase stack already running — leaving it (config changes: supabase stop && supabase start)"
else
  say "starting the Supabase stack (first run downloads images — several GB)"
  supabase start
  # First-install schema apply: only when the database has no NodeSpec tables
  # yet. NEVER reset an initialized database (it drops all data).
  # psql rides INSIDE the db container — CLI 2.x removed `supabase db psql`,
  # and the container's psql is always version-matched to the server.
  DB_CONTAINER="$(docker ps --format '{{.Names}}' | grep '^supabase_db_' | head -1)"
  [ -n "$DB_CONTAINER" ] || fail "could not find the supabase_db_* container after supabase start"
  HAS_SCHEMA="$(docker exec "$DB_CONTAINER" psql -U postgres -d postgres -tAc "select to_regclass('public.projects') is not null;" 2>/dev/null | tr -d '[:space:]' || echo '')"
  if [ "$HAS_SCHEMA" != "t" ]; then
    # --no-seed: the repo's seed.sql is BENCH tooling (a pre-confirmed admin
    # account with a known password) — it must never reach a deployment.
    # Customer accounts start with a fresh signup + first-admin.sql.
    say "empty database — applying the NodeSpec schema (no bench seed)"
    supabase db reset --no-seed
  fi
fi

# 4 · anon key for the frontend build, from the running stack when unset
if [ -z "${VITE_SUPABASE_ANON_KEY:-}" ]; then
  say "filling VITE_SUPABASE_ANON_KEY from the running stack"
  # env-format output parses with sed alone — the VM needs no Node runtime
  # (security audit 2026-08-24: fewer third-party installers on the box).
  # Newer CLIs name the value PUBLISHABLE_KEY — same key, same role.
  VITE_SUPABASE_ANON_KEY="$(supabase status -o env 2>/dev/null \
    | grep -E '^(ANON_KEY|PUBLISHABLE_KEY)=' | head -1 \
    | sed -E 's/^[A-Z_]+=//; s/^"//; s/"$//')"
  [ -n "$VITE_SUPABASE_ANON_KEY" ] || fail "could not read the anon key from 'supabase status' — paste it into selfhost.env (VITE_SUPABASE_ANON_KEY)"
  export VITE_SUPABASE_ANON_KEY
  # Persist it: selfhost.env must be self-sufficient so a MANUAL
  # `docker compose --env-file … up --build` also bakes a working frontend
  # (live find 2026-08-24: a manual rebuild with the key still blank shipped
  # an app that boots to "configuration is incomplete").
  sed -i "s|^VITE_SUPABASE_ANON_KEY=.*|VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY|" "$ENV_FILE"
fi

# 5 · frontend
say "building + starting the frontend container"
docker compose --env-file "$ENV_FILE" -f "$HERE/docker-compose.frontend.yml" up -d --build

say "done. App: ${PUBLIC_APP_URL:-http://localhost:${FRONTEND_PORT:-8080}} · API: ${VITE_SUPABASE_URL:-http://127.0.0.1:54321} · Studio (keep firewalled): http://127.0.0.1:54323"
say "next: sign up in the app, then promote your admin — see README.md 'First admin'."
