// N10(b) — the enrichment COVERAGE SWEEP. Runs the GTM bar (the ONE definition, in
// catalog-schemas) across every live technology row and writes the scored matrix +
// prioritized fill list to docs/N10_ENRICHMENT_COVERAGE.md.
//
// Run against the local Supabase OSS bench (reads scripts/bench/.env.bench like the
// bench harness; env vars win when set):
//
//   deno run --allow-net --allow-env --allow-read --allow-write scripts/n10-enrichment-coverage.ts
//
// Prioritization: the board asks for "most-dropped first, not alphabetical". There is
// no usage telemetry yet, so the proxy is catalog IN-DEGREE — how many OTHER rows name
// this technology in common_connections — plus affinity breadth. Both are printed so
// the ranking is auditable; replace with real drop counts when telemetry exists.

import { assessTechnologyGtmReadiness } from "../supabase/functions/_shared/catalog-schemas.ts";
import { resolveSweepEnv } from "./n10-lib.ts";

const { SUPABASE_URL, KEY } = resolveSweepEnv(import.meta.url);

async function rest(table: string, select: string): Promise<Record<string, unknown>[]> {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/${table}?select=${select}&limit=1000`, {
    headers: { apikey: KEY!, Authorization: `Bearer ${KEY}` },
  });
  if (!res.ok) throw new Error(`${table}: ${res.status} ${await res.text()}`);
  return await res.json();
}

let technologies: Record<string, unknown>[];
try {
  // NOTE: technology_catalog has NO category column (categories live on node_roles);
  // a technology's grouping is its role_affinities. Selecting one taught that live.
  technologies = await rest("technology_catalog", "id,name,role_affinities,ai_context,metadata_schema,suggested_files,common_connections");
} catch (e) {
  // A fetch-level failure means unreachable; an HTTP error means the stack answered
  // and the QUERY is wrong — say which, they need opposite fixes.
  if (e instanceof TypeError) {
    console.error(`Could not reach ${SUPABASE_URL} — is the local Supabase stack running?`);
  } else {
    console.error(`The stack at ${SUPABASE_URL} answered but the query failed (a script bug, not your setup):`);
  }
  console.error(String(e));
  Deno.exit(1);
}
const now = new Date().toISOString();

// In-degree: who names me in their common_connections.
const inDegree = new Map<string, number>();
for (const t of technologies) {
  const conns = (t.common_connections as unknown[]) ?? [];
  for (const c of conns) {
    const target = typeof c === "string" ? c : (c as Record<string, unknown>)?.technologyId ?? (c as Record<string, unknown>)?.id;
    if (typeof target === "string") inDegree.set(target, (inDegree.get(target) ?? 0) + 1);
  }
}

interface Scored {
  id: string;
  name: string;
  /** The technology's grouping IS its role affinities — technology rows carry no
   *  category column of their own. */
  roles: string;
  inDeg: number;
  affinities: number;
  ready: boolean;
  missing: string[];
  provenanceStatus: string;
  /** B10: 'migrated' | 'retired' | 'platform-umbrella' — outside the enrichment
   *  program, listed apart and excluded from the ready/total counts. */
  exempt?: string;
}

const allScored: Scored[] = technologies.map((t) => {
  const r = assessTechnologyGtmReadiness(t as never, { now });
  const affinities = ((t.role_affinities as string[]) ?? []);
  return {
    id: String(t.id),
    name: String(t.name ?? t.id),
    roles: affinities.slice(0, 3).join(", ") + (affinities.length > 3 ? ", …" : ""),
    inDeg: inDegree.get(String(t.id)) ?? 0,
    affinities: affinities.length,
    ready: r.ready,
    missing: r.missing,
    provenanceStatus: r.provenanceStatus,
    exempt: r.exempt,
  };
});

const exempt = allScored.filter((s) => s.exempt);
const scored = allScored.filter((s) => !s.exempt);
const readyCount = scored.filter((s) => s.ready).length;
const byProv = new Map<string, number>();
for (const s of scored) byProv.set(s.provenanceStatus, (byProv.get(s.provenanceStatus) ?? 0) + 1);

const fillList = scored
  .filter((s) => !s.ready)
  .sort((a, b) => b.inDeg - a.inDeg || b.affinities - a.affinities || a.missing.length - b.missing.length || a.id.localeCompare(b.id));

const lines: string[] = [];
lines.push("# N10(b) — Enrichment Coverage Matrix");
lines.push("");
lines.push(`> Generated by \`scripts/n10-enrichment-coverage.ts\` against ${SUPABASE_URL} on ${now}.`);
lines.push("> The bar is defined ONCE in `core/src/catalog-schemas.ts` (`assessTechnologyGtmReadiness`);");
lines.push("> re-run the script after every enrichment chunk — do not hand-edit the tables.");
lines.push("");
lines.push("## Summary");
lines.push("");
lines.push(`- **${readyCount} / ${scored.length}** technologies meet the GTM bar`);
for (const [status, n] of [...byProv.entries()].sort((a, b) => b[1] - a[1])) {
  lines.push(`- provenance \`${status}\`: ${n}`);
}
if (exempt.length > 0) {
  lines.push(`- exempt (outside the enrichment program): ${exempt.length} — ${exempt.map((s) => `\`${s.id}\` (${s.exempt})`).join(" · ")}`);
}
lines.push("");
lines.push("## Prioritized fill list (in-degree proxy — replace with drop telemetry when it exists)");
lines.push("");
lines.push("| # | technology | roles | in-deg | affinities | provenance | gaps |");
lines.push("|---|---|---|---|---|---|---|");
fillList.forEach((s, i) => {
  const gaps = s.missing.map((m) => m.split(":")[0]).join(", ");
  lines.push(`| ${i + 1} | ${s.id} | ${s.roles} | ${s.inDeg} | ${s.affinities} | ${s.provenanceStatus} | ${gaps} |`);
});
lines.push("");
lines.push("## Rows meeting the bar");
lines.push("");
lines.push(scored.filter((s) => s.ready).map((s) => `\`${s.id}\``).join(" · ") || "_none yet_");
lines.push("");

await Deno.writeTextFile(new URL("../docs/N10_ENRICHMENT_COVERAGE.md", import.meta.url), lines.join("\n"));
console.log(`GTM bar: ${readyCount}/${scored.length} ready — matrix written to docs/N10_ENRICHMENT_COVERAGE.md`);
console.log(`Top 10 fill priorities: ${fillList.slice(0, 10).map((s) => s.id).join(", ")}`);
