// P1-7 C2: cross-runtime serialization contract. This golden was generated by
// serializeModel itself; the test pins the anchor byte-for-byte so any change to the
// serialization rules is deliberate. The vitest side (src/tests/anchor-slice.test.ts)
// asserts core's buildNodeAnchorSlice produces byte-identical elements from the SAME
// fixture — together they keep the Deno anchor and the browser/node slice in lockstep.
// If you intentionally change the format: regenerate the fixture, and expect BOTH suites
// to need updating.
import { serializeModel } from '../_shared/model-anchor.ts';
import { assertEquals } from './helpers.ts';

Deno.test('model anchor matches the cross-runtime golden byte-for-byte', async () => {
  const fixture = JSON.parse(
    await Deno.readTextFile(new URL('./fixtures/anchor-slice-golden.json', import.meta.url)),
  );
  const produced = await serializeModel(fixture.graph);
  assertEquals(produced, fixture.anchorJson, 'anchor serialization drifted from the golden — if intentional, regenerate the fixture AND update the vitest slice suite');
});
