// GENERATED from core/src/container-type-data.ts by scripts/sync-core-engine.mjs. Do not edit:
// change core and run the script; src/tests/core-engine-copy.test.ts fails on drift.
import type { ContainerTypeDefinition } from './container-types.ts';

// AG.11f (2026-09-28): the containers the app draws before the catalog loads, or when it
// fails to. One entry per container role in the catalog, retired ones included so an
// existing node still draws as a box, with the catalog's label, layer, style, what it may
// hold and its fields, as of migration 20260928170000. The live bench compares this list
// with node_roles (n8-catalog, ag10-catalog-round-two).
export const STATIC_CONTAINER_TYPE_DATA: ContainerTypeDefinition[] = [
  {
    id: 'vpc',
    label: 'VPC / Virtual Network',
    description: 'Cloud virtual private network boundary',
    icon: 'cloud',
    layer: 'infrastructure',
    containerStyle: 'hosting',
    canContain: [
      'api-gateway', 'application-module', 'auth-provider', 'backend-service', 'bounded-context',
      'cache', 'cdn', 'database', 'docker-compose', 'docker-container', 'docker-swarm', 'ecs-cluster',
      'event-stream', 'graph-db', 'inference-service', 'k8s-cluster', 'k8s-namespace',
      'load-balancer', 'logging', 'message-broker', 'microservice-boundary', 'ml-pipeline',
      'monitoring', 'network-connection', 'object-storage', 'queue', 'realtime-service',
      'scheduled-trigger', 'search-engine', 'serverless-function', 'service-mesh', 'software-layer',
      'subnet', 'time-series-db', 'vector-database', 'worker',
    ],
    defaultMetadata: {
      cidrBlock: '10.0.0.0/16',
      region: 'us-east-1',
      enableDnsHostnames: true,
      enableDnsSupport: true,
      tenancy: 'default',
      internetGateway: true,
      natGateway: true,
      flowLogsEnabled: true,
      tags: { Name: 'production-vpc', Environment: 'production', ManagedBy: 'nodal' },
    },
    metadataSchema: {
      tags: { type: 'object', label: 'Resource Tags', description: 'Key-value pairs for organization and billing' },
      region: { type: 'string', label: 'Region', description: 'Geographic region (e.g., us-east-1)', required: true },
      cidrBlock: {
        type: 'string',
        label: 'CIDR Block',
        description: 'IP address range (e.g., 10.0.0.0/16)',
        required: true,
        default: '10.0.0.0/16',
      },
      natGateway: {
        type: 'boolean',
        label: 'NAT Gateway',
        description: 'Allow private subnets to access internet',
        default: false,
      },
      flowLogsEnabled: { type: 'boolean', label: 'Flow Logs', description: 'Enable traffic flow logging', default: false },
      internetGateway: { type: 'boolean', label: 'Internet Gateway', description: 'Allow internet access', default: true },
      enableDnsSupport: { type: 'boolean', label: 'DNS Support', description: 'Enable DNS server', default: true },
      enableDnsHostnames: {
        type: 'boolean',
        label: 'DNS Hostnames',
        description: 'Allow instances to receive DNS hostnames',
        default: true,
      },
    },
  },
  {
    id: 'subnet',
    label: 'Subnet',
    description: 'Network subnet within a VPC',
    icon: 'layers',
    layer: 'infrastructure',
    containerStyle: 'hosting',
    canContain: [
      'api-gateway', 'application-module', 'auth-provider', 'backend-service', 'bounded-context',
      'cache', 'database', 'docker-container', 'event-stream', 'graph-db', 'k8s-cluster',
      'load-balancer', 'message-broker', 'microservice-boundary', 'network-connection',
      'object-storage', 'queue', 'realtime-service', 'scheduled-trigger', 'search-engine',
      'serverless-function', 'service-mesh', 'software-layer', 'time-series-db', 'vector-database',
      'worker',
    ],
    defaultMetadata: { cidrBlock: '10.0.1.0/24', availabilityZone: '', subnetType: 'public', routeTable: '' },
    metadataSchema: {
      cidrBlock: { type: 'string', label: 'CIDR Block', description: 'IP address range for the subnet', required: true },
      subnetType: { type: 'string', label: 'Subnet Type', description: 'public or private', default: 'public' },
      routeTableId: { type: 'string', label: 'Route Table ID', description: 'Associated route table' },
      availabilityZone: {
        type: 'string',
        label: 'Availability Zone',
        description: 'Physical location (e.g., us-east-1a)',
        required: true,
      },
      autoAssignPublicIp: {
        type: 'boolean',
        label: 'Auto-assign Public IP',
        description: 'Automatically assign public IPs',
        default: false,
      },
    },
  },
  {
    id: 'hypervisor',
    label: 'Hypervisor Cluster',
    description: 'Virtualization platform (vSphere, Hyper-V, Proxmox)',
    icon: 'server',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: [
      'backend-service', 'cache', 'database', 'docker-compose', 'docker-container', 'k8s-cluster',
      'vector-database', 'virtual-machine', 'vpc', 'worker',
    ],
    defaultMetadata: { platform: 'vmware-vsphere', clusterName: '', haEnabled: true, hostCount: 3 },
    metadataSchema: {
      platform: {
        type: 'string',
        label: 'Platform',
        description: 'vmware-vsphere, hyper-v, proxmox, kvm',
        default: 'vmware-vsphere',
      },
      haEnabled: { type: 'boolean', label: 'High Availability', description: 'Enable automatic VM failover', default: true },
      hostCount: { type: 'number', label: 'Host Count', description: 'Number of hosts in cluster', default: 3 },
      clusterName: { type: 'string', label: 'Cluster Name', description: 'Virtualization cluster identifier', required: true },
    },
  },
  {
    id: 'virtual-machine',
    label: 'Virtual Machine',
    description: 'Generic VM instance on any hypervisor',
    icon: 'monitor',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: [
      'api-gateway', 'application-module', 'backend-service', 'bounded-context', 'cache', 'database',
      'docker-compose', 'docker-container', 'event-stream', 'graph-db', 'k8s-cluster',
      'message-broker', 'microservice-boundary', 'ml-pipeline', 'queue', 'realtime-service',
      'scheduled-trigger', 'search-engine', 'service-mesh', 'software-layer', 'time-series-db',
      'vector-database', 'worker',
    ],
    defaultMetadata: {
      osType: 'linux',
      osVersion: 'Ubuntu 22.04 LTS',
      cpuCores: 4,
      memoryGB: 16,
      diskGB: 100,
      diskType: 'ssd',
      hypervisor: 'vmware',
      snapshotsEnabled: true,
    },
    metadataSchema: {
      diskGB: { type: 'number', label: 'Disk Size (GB)', description: 'Primary disk size', default: 100 },
      osType: { type: 'string', label: 'OS Type', description: 'linux, windows, or other', default: 'linux' },
      cpuCores: { type: 'number', label: 'CPU Cores', description: 'Number of virtual CPUs', default: 4 },
      diskType: { type: 'string', label: 'Disk Type', description: 'ssd, nvme, or hdd', default: 'ssd' },
      memoryGB: { type: 'number', label: 'Memory (GB)', description: 'RAM in gigabytes', default: 16 },
      osVersion: { type: 'string', label: 'OS Version', description: 'Operating system version', default: 'Ubuntu 22.04 LTS' },
      hypervisor: { type: 'string', label: 'Hypervisor', description: 'vmware, hyper-v, kvm, xen, virtualbox', default: 'vmware' },
    },
  },
  {
    id: 'embedded-system',
    label: 'Embedded System',
    description: 'Deprecated: draw the device as an Edge Device, and group its code with an Application Module. Embedded system boundary containing device, firmware, and sensor subsystems',
    icon: 'cpu',
    layer: 'logical',
    containerStyle: 'logical-boundary',
    canContain: [
      'backend-service', 'database', 'embedded-device', 'firmware-service', 'frontend-app',
      'vector-database', 'worker',
    ],
    defaultMetadata: {
      systemType: 'real-time',
      powerBudget: '10W',
      operatingTemperature: '-40C to 85C',
      debugInterface: 'JTAG',
      firmwareUpdateMethod: 'OTA',
    },
    metadataSchema: {
      systemType: {
        type: 'string',
        label: 'System Type',
        description: 'real-time, soft-real-time, general-purpose',
        default: 'real-time',
      },
      powerBudget: { type: 'string', label: 'Power Budget', description: 'Maximum power consumption (e.g., 10W)' },
      certifications: { type: 'array', label: 'Certifications', description: 'DO-178C, IEC 61508, ISO 26262, etc.' },
      debugInterface: { type: 'string', label: 'Debug Interface', description: 'JTAG, SWD, UART, none', default: 'JTAG' },
      operatingTemperature: {
        type: 'string',
        label: 'Operating Temperature',
        description: 'Temperature range (e.g., -40C to 85C)',
        default: '-40C to 85C',
      },
    },
  },
  {
    id: 'k8s-cluster',
    label: 'Kubernetes Cluster',
    description: 'Kubernetes cluster boundary',
    icon: 'box',
    layer: 'orchestration',
    containerStyle: 'hosting',
    canContain: [
      'api-gateway', 'application-module', 'auth-provider', 'backend-service', 'bounded-context',
      'cache', 'database', 'event-stream', 'graph-db', 'inference-service', 'k8s-namespace',
      'load-balancer', 'logging', 'message-broker', 'microservice-boundary', 'ml-pipeline',
      'monitoring', 'queue', 'realtime-service', 'scheduled-trigger', 'search-engine', 'service-mesh',
      'software-layer', 'time-series-db', 'vector-database', 'worker',
    ],
    defaultMetadata: {
      version: '1.28',
      nodeCount: 3,
      nodeType: 't3.medium',
      networking: 'calico',
      ingressController: 'nginx',
      certManager: true,
      clusterAutoscaler: true,
      logging: 'CloudWatch',
      monitoring: 'Prometheus',
      rbacEnabled: true,
    },
    metadataSchema: {
      version: {
        type: 'string',
        label: 'Kubernetes Version',
        description: 'Cluster version (e.g., 1.28)',
        required: true,
        default: '1.28',
      },
      nodeType: { type: 'string', label: 'Node Instance Type', description: 'Instance type for nodes', default: 't3.medium' },
      nodeCount: { type: 'number', label: 'Node Count', description: 'Number of worker nodes', required: true, default: 3 },
      monitoring: { type: 'string', label: 'Monitoring Stack', description: 'Prometheus, Datadog, etc.', default: 'Prometheus' },
      networking: {
        type: 'string',
        label: 'CNI Plugin',
        description: 'Network plugin (calico, flannel, weave)',
        default: 'calico',
      },
      certManager: { type: 'boolean', label: 'Cert Manager', description: 'Automatic TLS certificate management', default: true },
      rbacEnabled: { type: 'boolean', label: 'RBAC Enabled', description: 'Role-based access control', default: true },
      ingressController: { type: 'string', label: 'Ingress Controller', description: 'nginx, traefik, or istio', default: 'nginx' },
    },
  },
  {
    id: 'k8s-namespace',
    label: 'Kubernetes Namespace',
    description: 'Kubernetes namespace isolation boundary',
    icon: 'folder',
    layer: 'orchestration',
    containerStyle: 'hosting',
    canContain: [
      'api-gateway', 'application-module', 'auth-provider', 'backend-service', 'bounded-context',
      'cache', 'database', 'event-stream', 'graph-db', 'inference-service', 'load-balancer',
      'logging', 'message-broker', 'microservice-boundary', 'ml-pipeline', 'monitoring',
      'object-storage', 'queue', 'realtime-service', 'scheduled-trigger', 'search-engine',
      'service-mesh', 'software-layer', 'time-series-db', 'vector-database', 'worker',
    ],
    defaultMetadata: {
      resourceQuota: true,
      cpuLimit: '10',
      cpuRequest: '2',
      memoryLimit: '20Gi',
      memoryRequest: '4Gi',
      storageLimit: '50Gi',
      podLimit: 100,
      networkPolicies: ['deny-all-ingress'],
      limitRanges: true,
      rbacEnabled: true,
    },
    metadataSchema: {
      cpuLimit: { type: 'string', label: 'CPU Limit', description: 'Max CPU cores (e.g., 10)', default: '10' },
      podLimit: { type: 'number', label: 'Pod Limit', description: 'Maximum number of pods', default: 100 },
      cpuRequest: { type: 'string', label: 'CPU Request', description: 'Total CPU requests (e.g., 2)', default: '2' },
      limitRanges: { type: 'boolean', label: 'Limit Ranges', description: 'Set default per-pod resource limits', default: true },
      memoryLimit: { type: 'string', label: 'Memory Limit', description: 'Max memory (e.g., 20Gi)', default: '20Gi' },
      rbacEnabled: { type: 'boolean', label: 'RBAC', description: 'Role-based access control', default: true },
      memoryRequest: { type: 'string', label: 'Memory Request', description: 'Total memory requests (e.g., 4Gi)', default: '4Gi' },
      resourceQuota: { type: 'boolean', label: 'Resource Quota', description: 'Enforce resource limits', default: true },
      networkPolicies: {
        type: 'array',
        label: 'Network Policies',
        description: 'Network security policies',
        default: ['deny-all-ingress'],
      },
    },
  },
  {
    id: 'docker-compose',
    label: 'Docker Compose',
    description: 'Multi-container Docker application',
    icon: 'layers',
    layer: 'orchestration',
    containerStyle: 'hosting',
    canContain: [
      'api-gateway', 'application-module', 'auth-provider', 'backend-service', 'bounded-context',
      'cache', 'database', 'docker-container', 'event-stream', 'frontend-app', 'graph-db',
      'inference-service', 'load-balancer', 'logging', 'message-broker', 'microservice-boundary',
      'ml-pipeline', 'monitoring', 'object-storage', 'queue', 'realtime-service', 'scheduled-trigger',
      'search-engine', 'serverless-function', 'service-mesh', 'software-layer', 'time-series-db',
      'vector-database', 'worker',
    ],
    defaultMetadata: { version: '3.8', networks: ['default'], volumes: [] },
    metadataSchema: {
      secrets: { type: 'array', label: 'Secrets', description: 'Secret management configuration' },
      version: { type: 'string', label: 'Compose Version', description: 'Docker Compose file version', default: '3.8' },
      volumes: { type: 'array', label: 'Named Volumes', description: 'Persistent volume definitions' },
      networks: { type: 'array', label: 'Networks', description: 'Docker networks' },
    },
  },
  {
    id: 'docker-swarm',
    label: 'Docker Swarm',
    description: 'Docker Swarm container orchestration cluster',
    icon: 'layers',
    layer: 'orchestration',
    containerStyle: 'hosting',
    canContain: [
      'application-module', 'backend-service', 'bounded-context', 'cache', 'database',
      'docker-container', 'event-stream', 'inference-service', 'load-balancer', 'message-broker',
      'microservice-boundary', 'queue', 'realtime-service', 'scheduled-trigger', 'search-engine',
      'service-mesh', 'software-layer', 'vector-database', 'worker',
    ],
    defaultMetadata: { managerCount: 3, workerCount: 5, ingressNetwork: 'ingress', overlayNetworks: ['app-network'], autolock: true },
    metadataSchema: {
      autolock: { type: 'boolean', label: 'Auto-lock', description: 'Require unlock key on manager restart', default: true },
      workerCount: { type: 'number', label: 'Worker Nodes', description: 'Number of worker nodes', default: 5 },
      managerCount: { type: 'number', label: 'Manager Nodes', description: 'Number of manager nodes', default: 3 },
      overlayNetworks: { type: 'array', label: 'Overlay Networks', description: 'Custom overlay networks', default: ['app-network'] },
    },
  },
  {
    id: 'ecs-cluster',
    label: 'ECS Cluster',
    description: 'AWS ECS container cluster',
    icon: 'box',
    layer: 'orchestration',
    containerStyle: 'hosting',
    canContain: [
      'application-module', 'backend-service', 'bounded-context', 'cache', 'database', 'event-stream',
      'inference-service', 'load-balancer', 'logging', 'message-broker', 'microservice-boundary',
      'monitoring', 'queue', 'realtime-service', 'scheduled-trigger', 'search-engine', 'service-mesh',
      'software-layer', 'vector-database', 'worker',
    ],
    defaultMetadata: { launchType: 'FARGATE', taskCount: 2 },
    metadataSchema: {
      taskCount: { type: 'number', label: 'Task Count', description: 'Number of running tasks', default: 2 },
      clusterArn: { type: 'string', label: 'Cluster ARN', description: 'ECS cluster Amazon Resource Name' },
      launchType: { type: 'string', label: 'Launch Type', description: 'FARGATE or EC2', default: 'FARGATE' },
    },
  },
  {
    id: 'docker-container',
    label: 'Container or App Runtime',
    description: 'What runs your portable code: a container, or a managed runtime that only runs it.',
    icon: 'box',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: [
      'api-gateway', 'auth-provider', 'backend-service', 'cache', 'database', 'event-stream',
      'frontend-app', 'game-server', 'graph-db', 'inference-service', 'message-broker', 'queue',
      'realtime-service', 'scheduled-trigger', 'search-engine', 'time-series-db', 'vector-database',
      'worker',
    ],
    defaultMetadata: {
      baseImage: 'node:24-alpine',
      ports: [3000],
      environmentVariables: {},
      volumes: [],
      command: 'npm start',
      restartPolicy: 'unless-stopped',
      cpuLimit: '1.0',
      memoryLimit: '512m',
    },
    metadataSchema: {
      ports: { type: 'array', label: 'Exposed Ports', description: 'Container ports to expose' },
      volumes: { type: 'array', label: 'Volume Mounts', description: 'Persistent storage paths' },
      cpuLimit: { type: 'string', label: 'CPU Limit', description: 'Max CPU (e.g., 1.5 cores)' },
      baseImage: { type: 'string', label: 'Base Image', description: 'Docker image (e.g., node:20-alpine)', required: true },
      memoryLimit: { type: 'string', label: 'Memory Limit', description: 'Max memory (e.g., 512m, 2g)' },
      restartPolicy: {
        type: 'string',
        label: 'Restart Policy',
        description: 'always, unless-stopped, on-failure',
        default: 'unless-stopped',
      },
      environmentVariables: { type: 'object', label: 'Environment Variables', description: 'Key-value configuration pairs' },
    },
  },
  {
    id: 'mobile-device',
    label: 'Mobile Device',
    description: 'Physical mobile device (iOS or Android) that hosts native apps, local databases, background workers, and on-device services.',
    icon: 'smartphone',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: [
      'backend-service', 'cache', 'database', 'frontend-app', 'game-client',
      'inference-service', 'mobile-app', 'vector-database', 'worker',
    ],
    defaultMetadata: {
      platform: 'ios',
      osMinVersion: '16.0',
      deviceCategory: 'phone',
      offlineCapable: true,
      pushNotifications: true,
      biometricAuth: false,
    },
    metadataSchema: {
      platform: {
        type: 'enum',
        label: 'Platform',
        description: 'The mobile operating system the device runs',
        default: 'ios',
        options: ['ios', 'android', 'cross-platform'],
      },
      biometricAuth: { type: 'boolean', label: 'Biometric Auth', description: 'Use Face ID / Touch ID / Fingerprint', default: false },
      deviceCategory: {
        type: 'enum',
        label: 'Device category',
        description: 'The kind of device',
        default: 'phone',
        options: ['phone', 'tablet', 'watch', 'tv'],
      },
      offlineCapable: {
        type: 'boolean',
        label: 'Offline Capable',
        description: 'App works without network connectivity',
        default: true,
      },
      pushNotifications: {
        type: 'boolean',
        label: 'Push Notifications',
        description: 'Enable push notification support (APNs/FCM)',
        default: true,
      },
    },
  },
  {
    id: 'microservice-boundary',
    label: 'Microservice Boundary',
    description: 'Logical grouping of related services',
    icon: 'box',
    layer: 'logical',
    containerStyle: 'logical-boundary',
    canContain: [
      'auth-provider', 'backend-service', 'cache', 'database', 'event-stream', 'graph-db', 'logging',
      'message-broker', 'monitoring', 'queue', 'realtime-service', 'scheduled-trigger',
      'search-engine', 'time-series-db', 'vector-database', 'worker',
    ],
    defaultMetadata: {
      domain: '',
      apiContract: '',
      communicationProtocol: 'rest',
      authenticationMethod: 'jwt',
      sharedLibraries: [],
      eventBus: '',
    },
    metadataSchema: {
      domain: { type: 'string', label: 'Business Domain', description: 'Domain this service belongs to', required: true },
      apiGateway: { type: 'string', label: 'API Gateway', description: 'Kong, Ambassador, AWS API Gateway, etc.' },
      serviceRegistry: { type: 'string', label: 'Service Registry', description: 'Consul, Eureka, etcd, etc.' },
      authenticationMethod: { type: 'string', label: 'Authentication Method', description: 'jwt, oauth2, api-key, mtls', default: 'jwt' },
      communicationProtocol: {
        type: 'string',
        label: 'Communication Protocol',
        description: 'rest, graphql, grpc, message-queue',
        default: 'rest',
      },
    },
  },
  {
    id: 'bounded-context',
    label: 'Bounded Context',
    description: 'DDD bounded context boundary',
    icon: 'hexagon',
    layer: 'logical',
    containerStyle: 'logical-boundary',
    canContain: [
      'backend-service', 'cache', 'database', 'event-stream', 'graph-db', 'message-broker',
      'microservice-boundary', 'queue', 'scheduled-trigger', 'vector-database', 'worker',
    ],
    defaultMetadata: { domain: '', ubiquitousLanguage: {}, aggregates: [], domainEvents: [] },
    metadataSchema: {
      domain: { type: 'string', label: 'Domain Name', description: 'Business domain (e.g., Order Management)', required: true },
      aggregates: { type: 'array', label: 'Aggregate Roots', description: 'Key domain entities' },
      domainEvents: { type: 'array', label: 'Domain Events', description: 'Events published by this context' },
      anticorruptionLayer: {
        type: 'boolean',
        label: 'Anti-Corruption Layer',
        description: 'Protect domain model from external changes',
        default: false,
      },
    },
  },
  {
    id: 'application-module',
    label: 'Application Module',
    description: 'Logical module within an application',
    icon: 'package',
    layer: 'logical',
    containerStyle: 'logical-boundary',
    canContain: [
      'auth-provider', 'backend-service', 'cache', 'database', 'event-stream', 'frontend-app',
      'graph-db', 'logging', 'message-broker', 'monitoring', 'queue', 'realtime-service',
      'scheduled-trigger', 'time-series-db', 'vector-database', 'worker',
    ],
    defaultMetadata: {
      moduleName: '',
      moduleType: 'feature',
      visibility: 'internal',
      dependencies: [],
      exports: [],
      entryPoints: [],
      testCoverage: 0,
    },
    metadataSchema: {
      moduleName: { type: 'string', label: 'Module Name', description: 'Unique module identifier', required: true },
      moduleType: { type: 'string', label: 'Module Type', description: 'feature, core, or plugin', default: 'feature' },
      visibility: { type: 'string', label: 'Visibility', description: 'internal or public', default: 'internal' },
      dependencies: { type: 'array', label: 'Dependencies', description: 'Other modules this depends on' },
      testCoverage: { type: 'number', label: 'Test Coverage (%)', description: 'Code coverage percentage', default: 0 },
    },
  },
  {
    id: 'software-layer',
    label: 'Software Layer',
    description: 'Architectural layer grouping (presentation, business, data)',
    icon: 'layers',
    layer: 'logical',
    containerStyle: 'logical-boundary',
    canContain: [
      'backend-service', 'cache', 'database', 'frontend-app', 'scheduled-trigger', 'vector-database',
      'worker',
    ],
    defaultMetadata: { layerType: 'business', allowedDependencies: [], prohibitedDependencies: [], responsibilities: [] },
    metadataSchema: {
      layerType: {
        type: 'string',
        label: 'Layer Type',
        description: 'presentation, business, data, infrastructure, or domain',
        default: 'business',
      },
      allowedDependencies: { type: 'array', label: 'Allowed Dependencies', description: 'Layers this layer can depend on' },
      prohibitedDependencies: { type: 'array', label: 'Prohibited Dependencies', description: 'Layers this layer must NOT depend on' },
    },
  },
  {
    id: 'aws',
    label: 'AWS',
    description: 'Amazon Web Services cloud platform providing compute, storage, messaging, and database services',
    icon: 'Cloud',
    layer: 'infrastructure',
    containerStyle: 'hosting',
    canContain: {
      natures: ['build', 'call', 'engine', 'integrate'],
      interfaceKinds: ['auth', 'data', 'event_bus', 'object_store', 'queue', 'service', 'telemetry'],
      providers: ['aws'],
    },
    defaultMetadata: {
      costTags: true,
      environment: 'production',
      iamBaseline: 'identity-center-sso',
      budgetAlerts: true,
      primaryRegion: 'us-east-1',
    },
    metadataSchema: {
      iacTool: {
        type: 'enum',
        label: 'IaC tool',
        description: 'The infrastructure-as-code tool EVERY declarative node in this platform is provisioned with; inherited by contained nodes and named verbatim in their task packets. Terraform is the ecosystem default (BSL-licensed since 2023; OpenTofu is the Linux Foundation fork under MPL); provider-native = CloudFormation/Bicep/Config-Connector. Leave unset only if undecided; packets will then instruct the AI to confirm rather than assume',
        options: ['terraform', 'opentofu', 'pulumi', 'provider-native', 'cdk'],
      },
      costTags: {
        type: 'boolean',
        label: 'Enforce cost-allocation tags',
        description: 'project/env/owner tags on every child resource; IaC-enforced, reads in Cost Explorer',
        default: true,
      },
      environment: {
        type: 'enum',
        label: 'Environment',
        description: 'Drives sizing/HA defaults children inherit',
        default: 'production',
        options: ['dev', 'staging', 'production'],
      },
      iamBaseline: {
        type: 'enum',
        label: 'IAM baseline',
        description: 'Account access model; Identity Center setup is a CONSOLE step; role/policy wiring is IaC',
        default: 'identity-center-sso',
        options: ['identity-center-sso', 'iam-users-mfa', 'oidc-federation-only'],
      },
      accountAlias: {
        type: 'string',
        label: 'Account alias',
        description: 'Which AWS account/environment this container represents (e.g. myapp-prod)',
      },
      budgetAlerts: {
        type: 'boolean',
        label: 'Budget alerts',
        description: 'AWS Budgets alarm wiring (IaC); the notification email confirm is a console step',
        default: true,
      },
      primaryRegion: {
        type: 'string',
        label: 'Primary region',
        description: 'Default region children deploy into unless they say otherwise; IaC reads this',
        default: 'us-east-1',
      },
    },
  },
  {
    id: 'azure',
    label: 'Azure',
    description: 'Microsoft Azure cloud platform providing compute, storage, messaging, and database services',
    icon: 'cloud',
    layer: 'infrastructure',
    containerStyle: 'hosting',
    canContain: {
      natures: ['build', 'call', 'engine', 'integrate'],
      interfaceKinds: ['auth', 'data', 'event_bus', 'object_store', 'queue', 'service', 'telemetry'],
      providers: ['azure'],
    },
    defaultMetadata: {
      tagPolicy: true,
      environment: 'production',
      budgetAlerts: true,
      primaryRegion: 'eastus',
      identityBaseline: 'managed-identity-preferred',
    },
    metadataSchema: {
      iacTool: {
        type: 'enum',
        label: 'IaC tool',
        description: 'The infrastructure-as-code tool EVERY declarative node in this platform is provisioned with; inherited by contained nodes and named verbatim in their task packets. Terraform is the ecosystem default (BSL-licensed since 2023; OpenTofu is the Linux Foundation fork under MPL); provider-native = CloudFormation/Bicep/Config-Connector. Leave unset only if undecided; packets will then instruct the AI to confirm rather than assume',
        options: ['terraform', 'opentofu', 'pulumi', 'provider-native', 'cdk'],
      },
      tagPolicy: {
        type: 'boolean',
        label: 'Enforce resource tags',
        description: 'project/env/owner tags on every child resource; IaC-enforced, reads in Cost Management',
        default: true,
      },
      environment: {
        type: 'enum',
        label: 'Environment',
        description: 'Drives sizing/HA defaults children inherit',
        default: 'production',
        options: ['dev', 'staging', 'production'],
      },
      budgetAlerts: {
        type: 'boolean',
        label: 'Budget alerts',
        description: 'Cost Management budget wiring (IaC); the notification confirm is a console step',
        default: true,
      },
      primaryRegion: {
        type: 'string',
        label: 'Primary region',
        description: 'Default region children deploy into unless they say otherwise; Bicep/Terraform reads this',
        default: 'eastus',
      },
      resourceGroup: {
        type: 'string',
        label: 'Default resource group',
        description: 'Resource group children are created in unless they override; the unit of lifecycle and RBAC in Azure',
      },
      identityBaseline: {
        type: 'enum',
        label: 'Identity baseline',
        description: 'How children authenticate to each other. Managed identity removes stored secrets entirely; the Entra ID setup is a CONSOLE step, the role assignments are IaC',
        default: 'managed-identity-preferred',
        options: ['managed-identity-preferred', 'service-principals', 'workload-identity-federation'],
      },
      policyAssignment: {
        type: 'string',
        label: 'Azure Policy initiative',
        description: 'Policy initiative assigned at this scope (e.g. CIS, custom deny-public-IP). Children must be provisioned to satisfy it or deployment fails',
      },
      subscriptionName: {
        type: 'string',
        label: 'Subscription',
        description: 'Which Azure subscription/environment this container represents (e.g. myapp-prod). Children deploy into it',
      },
    },
  },
  {
    id: 'gcp',
    label: 'Google Cloud',
    description: 'Google Cloud Platform providing compute, storage, messaging, and database services',
    icon: 'cloud',
    layer: 'infrastructure',
    containerStyle: 'hosting',
    canContain: {
      natures: ['build', 'call', 'engine', 'integrate'],
      interfaceKinds: ['auth', 'data', 'event_bus', 'object_store', 'queue', 'service', 'telemetry'],
      providers: ['gcp', 'firebase'],
    },
    defaultMetadata: {
      environment: 'production',
      labelPolicy: true,
      orgPolicies: true,
      budgetAlerts: true,
      primaryRegion: 'us-central1',
      identityBaseline: 'workload-identity-federation',
    },
    metadataSchema: {
      folder: {
        type: 'string',
        label: 'Folder / org path',
        description: 'Where the project sits in the resource hierarchy; org policies inherit down from it',
      },
      iacTool: {
        type: 'enum',
        label: 'IaC tool',
        description: 'The infrastructure-as-code tool EVERY declarative node in this platform is provisioned with; inherited by contained nodes and named verbatim in their task packets. Terraform is the ecosystem default (BSL-licensed since 2023; OpenTofu is the Linux Foundation fork under MPL); provider-native = CloudFormation/Bicep/Config-Connector. Leave unset only if undecided; packets will then instruct the AI to confirm rather than assume',
        options: ['terraform', 'opentofu', 'pulumi', 'provider-native', 'cdk'],
      },
      projectId: {
        type: 'string',
        label: 'Project ID',
        description: 'The GCP project children are created in (e.g. myapp-prod-1234). In GCP the PROJECT is the primary isolation and billing boundary, not the account',
      },
      environment: {
        type: 'enum',
        label: 'Environment',
        description: 'Drives sizing/HA defaults children inherit',
        default: 'production',
        options: ['dev', 'staging', 'production'],
      },
      labelPolicy: {
        type: 'boolean',
        label: 'Enforce resource labels',
        description: 'project/env/owner LABELS (GCP calls them labels, not tags) on every child; reads in billing export',
        default: true,
      },
      orgPolicies: {
        type: 'boolean',
        label: 'Org policy constraints',
        description: 'Constraints like domain-restricted sharing and no-external-IP inherit to every child; IaC must satisfy them or provisioning fails',
        default: true,
      },
      budgetAlerts: {
        type: 'boolean',
        label: 'Budget alerts',
        description: 'Billing budget + Pub/Sub notification wiring (IaC); enabling the billing export is a console step',
        default: true,
      },
      primaryRegion: {
        type: 'string',
        label: 'Primary region',
        description: 'Default region children deploy into unless they say otherwise; Terraform reads this',
        default: 'us-central1',
      },
      identityBaseline: {
        type: 'enum',
        label: 'Identity baseline',
        description: 'Workload Identity Federation avoids downloaded service-account keys entirely. The default compute SA is over-privileged and should never be the answer for production',
        default: 'workload-identity-federation',
        options: ['workload-identity-federation', 'per-service-service-accounts', 'default-compute-sa'],
      },
    },
  },
  {
    id: 'cloudflare',
    label: 'Cloudflare',
    description: 'Cloudflare platform providing edge workers, R2 storage, and CDN services',
    icon: 'Globe',
    layer: 'infrastructure',
    containerStyle: 'hosting',
    canContain: {
      natures: ['build', 'call', 'engine', 'integrate'],
      interfaceKinds: ['auth', 'data', 'event_bus', 'object_store', 'queue', 'service', 'telemetry'],
      providers: ['cloudflare'],
    },
    defaultMetadata: {},
    metadataSchema: {},
  },
  {
    id: 'supabase',
    label: 'Supabase (Managed)',
    description: 'The fully managed Supabase product (Postgres database, Auth, Storage, Edge Functions, Realtime, Vector) operated by Supabase. ONE node represents the whole product; declare which services the architecture uses in its configuration. For self-hosting, use the individual OSS component technologies inside your own container instead.',
    icon: 'Database',
    layer: 'infrastructure',
    containerStyle: 'hosting',
    canContain: { roleIds: ['auth-provider', 'database', 'object-storage', 'realtime-service', 'serverless-function'] },
    defaultMetadata: {},
    metadataSchema: {},
  },
  {
    id: 'vercel',
    label: 'Vercel',
    description: 'Managed hosting platform for frontend-first apps: git-push deploys, preview environments per PR, Vercel Functions (Fluid Compute), edge network and first-party Next.js support.',
    icon: 'Cloud',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: { natures: ['build', 'call'], interfaceKinds: ['data', 'service', 'telemetry'], providers: ['vercel'] },
    defaultMetadata: { environment: 'production' },
    metadataSchema: {
      team: {
        type: 'string',
        label: 'Team / scope',
        description: 'Vercel team the project lives under (billing + access boundary)',
      },
      environment: {
        type: 'enum',
        label: 'Environment',
        description: 'Scopes contained nodes; preview deployments are per-PR by default',
        default: 'production',
        options: ['production', 'preview', 'development'],
      },
    },
  },
  {
    id: 'netlify',
    label: 'Netlify',
    description: 'Managed hosting platform for static-first sites and Jamstack apps: git deploys, deploy previews, Netlify Functions, forms and edge handlers.',
    icon: 'Cloud',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: { natures: ['build', 'call'], interfaceKinds: ['service', 'telemetry'], providers: ['netlify'] },
    defaultMetadata: { environment: 'production' },
    metadataSchema: {
      team: { type: 'string', label: 'Team', description: 'Netlify team (billing + access boundary)' },
      environment: {
        type: 'enum',
        label: 'Environment',
        default: 'production',
        options: ['production', 'deploy-preview', 'branch-deploy'],
      },
    },
  },
  {
    id: 'railway',
    label: 'Railway',
    description: 'Managed app platform that runs full stacks from git or Docker images: services, managed Postgres/Redis/MySQL, cron, private networking and per-environment config.',
    icon: 'Cloud',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: {
      natures: ['build', 'call', 'engine'],
      interfaceKinds: ['data', 'queue', 'service', 'telemetry'],
      providers: ['railway'],
    },
    defaultMetadata: { environment: 'production' },
    metadataSchema: {
      region: { type: 'string', label: 'Region', description: 'Deployment region for contained services' },
      environment: {
        type: 'enum',
        label: 'Environment',
        description: 'Railway environments scope every contained service\'s config',
        default: 'production',
        options: ['production', 'staging', 'pr-environments'],
      },
    },
  },
  {
    id: 'render',
    label: 'Render',
    description: 'Managed app platform: web services, background workers, cron jobs, managed Postgres/Redis (Key Value), static sites and preview environments.',
    icon: 'Cloud',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: {
      natures: ['build', 'call', 'engine'],
      interfaceKinds: ['data', 'queue', 'service', 'telemetry'],
      providers: ['render'],
    },
    defaultMetadata: { environment: 'production' },
    metadataSchema: {
      region: { type: 'string', label: 'Region', description: 'Region for contained services and databases' },
      environment: { type: 'enum', label: 'Environment', default: 'production', options: ['production', 'preview'] },
    },
  },
  {
    id: 'fly-io',
    label: 'Fly.io',
    description: 'App platform that runs Docker images as Fly Machines (micro-VMs) in regions close to users: global app placement, volumes, private networking (WireGuard), managed Postgres.',
    icon: 'Cloud',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: { natures: ['build', 'call'], interfaceKinds: ['data', 'queue', 'service', 'telemetry'], providers: ['fly-io'] },
    defaultMetadata: { environment: 'production', primaryRegion: 'iad' },
    metadataSchema: {
      environment: { type: 'enum', label: 'Environment', default: 'production', options: ['production', 'staging'] },
      primaryRegion: {
        type: 'string',
        label: 'Primary region',
        description: 'Fly region code (iad, fra, syd…); placement IS the product; contained nodes inherit it',
        default: 'iad',
      },
    },
  },
  {
    id: 'desktop-device',
    label: 'Desktop Device',
    description: 'A desktop or laptop computer (macOS, Windows or Linux) that hosts an installed desktop application and whatever runs beside it: a companion service, a local database or cache, a driver.',
    icon: 'Monitor',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: [
      'backend-service', 'cache', 'cli-tool', 'database', 'desktop-app', 'frontend-app',
      'game-client', 'inference-service', 'kernel-module', 'worker',
    ],
    defaultMetadata: { platform: 'cross-platform', autoUpdate: true, installMethod: 'installer' },
    metadataSchema: {
      platform: {
        type: 'enum',
        label: 'Platform',
        description: 'The operating system the device runs',
        default: 'cross-platform',
        options: ['macos', 'windows', 'linux', 'cross-platform'],
      },
      autoUpdate: {
        type: 'boolean',
        label: 'Updates itself',
        description: 'The app fetches and applies its own updates',
        default: true,
      },
      installMethod: {
        type: 'enum',
        label: 'Install method',
        description: 'How the app reaches the machine',
        default: 'installer',
        options: ['installer', 'store', 'package-manager', 'portable'],
      },
    },
  },
  {
    id: 'edge-device',
    label: 'Edge Device',
    description: 'A device in the field that runs software without a server: the firmware on a microcontroller, an embedded Linux service, a kernel module or driver, a local model, and the sensors and actuators wired to it.',
    icon: 'CircuitBoard',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: [
      'actuator', 'backend-service', 'cache', 'database', 'embedded-device', 'firmware-service',
      'inference-service', 'kernel-module', 'microcontroller', 'ros2-node', 'sensor', 'worker',
    ],
    defaultMetadata: { deviceClass: 'microcontroller', fieldUpdatable: true },
    metadataSchema: {
      deviceClass: {
        type: 'enum',
        label: 'Device class',
        description: 'What kind of hardware the device is',
        default: 'microcontroller',
        options: ['microcontroller', 'single-board-computer', 'industrial-controller', 'appliance'],
      },
      connectivity: {
        type: 'multiselect',
        label: 'Connectivity',
        description: 'The links the device has; none ticked means none',
        options: ['wifi', 'ethernet', 'cellular', 'lora', 'ble'],
      },
      fieldUpdatable: {
        type: 'boolean',
        label: 'Updated in the field',
        description: 'The device takes firmware or software updates without a site visit',
        default: true,
      },
    },
  },
  {
    id: 'gateway-device',
    label: 'IoT Gateway',
    description: 'Edge gateway device bridging local IoT devices to cloud services via protocol translation',
    icon: 'Router',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: ['actuator', 'firmware-service', 'microcontroller', 'sensor'],
    defaultMetadata: {},
    metadataSchema: {},
  },
  {
    id: 'robot',
    label: 'Robot',
    description: 'Robotic system integrating sensors, actuators, controllers, and ROS 2 nodes',
    icon: 'Bot',
    layer: 'runtime',
    containerStyle: 'hosting',
    canContain: ['actuator', 'firmware-service', 'microcontroller', 'ros2-node', 'sensor'],
    defaultMetadata: {},
    metadataSchema: {},
  },
  {
    id: 'game-engine-project',
    label: 'Game Engine Project',
    description: 'Deprecated: use game-client instead; the game itself (the Unity/Godot/Unreal project) is a buildable node, not a workspace container. Game engine project containing gameplay, physics, and rendering systems',
    icon: 'Gamepad2',
    layer: 'logical',
    containerStyle: 'logical-boundary',
    canContain: [
      'backend-service', 'database', 'frontend-app', 'game-client', 'game-server',
      'inference-service', 'queue', 'realtime-service', 'shared-library', 'vector-database', 'worker',
    ],
    defaultMetadata: {},
    metadataSchema: {},
  },
];
